######################################################################
# Binary Sensor: Alarms
######################################################################

- platform: template
  sensors:
    alarms:
      friendly_name: Allarmi
      entity_id: input_boolean.alarms
      value_template: >-
        {{ is_state('input_boolean.alarms', 'on') }}
      icon_template: >-
        {% if is_state('input_boolean.alarms', 'on') %}
           mdi:alarm-light
        {% else %}
           mdi:alarm-light-outline
        {% endif %}
