######################################################################
# Binary Sensor: Car Doors Lock
######################################################################

- platform: template
  sensors:
    car_doors_lock:
      friendly_name: Vettura Bloccata
      device_class: lock
      entity_id: sensor.ff590mr_door_lock_vehicle
      value_template: >-
        {{ not is_state('sensor.ff590mr_door_lock_vehicle', '2') }}
      icon_template: >-
        {% if is_state('sensor.ff590mr_door_lock_vehicle', '2') %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}

######################################################################
# Binary Sensor: Car Windows Lock
######################################################################

- platform: template
  sensors:
    car_windows_lock:
      friendly_name: Chiusura Finestrini
      device_class: lock
      entity_id: 
        - sensor.ff590mr_window_front_left 
        - sensor.ff590mr_window_front_right
        - sensor.ff590mr_window_rear_left
        - sensor.ff590mr_window_rear_right
      value_template: >-
        {{ not (is_state('sensor.ff590mr_window_front_left', '2') 
           and is_state('sensor.ff590mr_window_front_right', '2')
           and is_state('sensor.ff590mr_window_rear_left', '2')
           and is_state('sensor.ff590mr_window_rear_right', '2') ) }}
      icon_template: >-
        {% if is_state('sensor.ff590mr_window_front_left', '2') 
           and is_state('sensor.ff590mr_window_front_right', '2')
           and is_state('sensor.ff590mr_window_rear_left', '2')
           and is_state('sensor.ff590mr_window_rear_right', '2') %}
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}