######################################################################
# Binary Sensor: Doors Lock
######################################################################

- platform: template
  sensors:
    ff590mr_lock:
      friendly_name: Vettura Bloccata
      entity_id: lock.ff590mr_lock
      value_template: >-
        {{ is_state('lock.ff590mr_lock', 'locked') }}
      icon_template: >-
        {% if is_state('lock.ff590mr_lock', 'unlocked') %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}
      device_class: lock

######################################################################
# Binary Sensor: Doors Closed
######################################################################

- platform: template
  sensors:
    ff590mr_doors_closed:
      friendly_name: Chiusura Porte
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ is_state('sensor.ff590mr_lock', 'true') }}
      icon_template: >-
        {% if is_state('sensor.ff590mr_lock', 'true') %}
          mdi:car-door
        {% else %}
          mdi:car-door
        {% endif %}
      device_class: lock

######################################################################
# Binary Sensor: Decklid Status
######################################################################

- platform: template
  sensors:
    ff590mr_status_decklid:
      friendly_name: Bagagliaio
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ not is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_LOCKED') }}
      icon_template: >-
        {% if is_state('sensor.ff590mr_lock', 'CLOSED_AND_LOCKED') %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}
      device_class: opening

######################################################################
# Binary Sensor: Warning Brake fluid
######################################################################

- platform: template
  sensors:
    ff590mr_warning_brakefluid:
      friendly_name: Liquido freni
      entity_id: binary_sensor.ff590mr_engine_light_warning
      value_template: >-
        {{ is_state_attr('binary_sensor.ff590mr_engine_light_warning', 'warningbrakefluid', 'true') }}
      device_class: problem

######################################################################
# Binary Sensor: Warning Wash Water
######################################################################

- platform: template
  sensors:
    ff590mr_warning_washwater:
      friendly_name: Liquido lavacristalli
      entity_id: binary_sensor.ff590mr_engine_light_warning
      value_template: >-
        {{ is_state_attr('binary_sensor.ff590mr_engine_light_warning', 'warningwashwater', 'true') }}
      device_class: problem

######################################################################
# Binary Sensor: Warning Coolant Level Low
######################################################################

- platform: template
  sensors:
    ff590mr_warning_coolantlevellow:
      friendly_name: Liquido raffreddamento
      entity_id: binary_sensor.ff590mr_engine_light_warning
      value_template: >-
        {{ is_state_attr('binary_sensor.ff590mr_engine_light_warning', 'warningcoolantlevellow', 'true') }}
      device_class: problem
