######################################################################
# Binary Sensor: Doors Lock
######################################################################

- platform: template
  sensors:
    ff590mr_locked:
      friendly_name: Vettura Bloccata
      entity_id: lock.ff590mr_lock
      value_template: >-
        {{ not is_state('sensor.ff590mr_lock', 'True') }}
      icon_template: >-
        {% if is_state('sensor.ff590mr_lock', 'True') %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}
      device_class: lock

######################################################################
# Binary Sensor: Doors Closed
######################################################################

- platform: template
  sensors:
    ff590mr_doors_closed:
      friendly_name: Porte
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ not is_state_attr('sensor.ff590mr_lock', 'doorsClosed', true) }}
      icon_template: >-
        {% if is_state_attr('sensor.ff590mr_lock', 'doorsClosed', true) %}
          mdi:car-door
        {% else %}
          mdi:car-door
        {% endif %}
      device_class: opening

######################################################################
# Binary Sensor: Door Front Left
######################################################################

- platform: template
  sensors:
    ff590mr_door_front_left:
      friendly_name: Anteriore Sinistra
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ not (is_state_attr('sensor.ff590mr_lock', 'doorStateFrontLeft', 'DOOR_CLOSED_AND_DOOR_LOCKED') or
                is_state_attr('sensor.ff590mr_lock', 'doorStateFrontLeft', 'DOOR_CLOSED_AND_DOOR_UNLOCKED')) }}
      icon_template: mdi:car-door
      device_class: opening

######################################################################
# Binary Sensor: Door Front Right
######################################################################

- platform: template
  sensors:
    ff590mr_door_front_right:
      friendly_name: Anteriore Destra
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ not (is_state_attr('sensor.ff590mr_lock', 'doorStateFrontRight', 'DOOR_CLOSED_AND_DOOR_LOCKED') or
                is_state_attr('sensor.ff590mr_lock', 'doorStateFrontRight', 'DOOR_CLOSED_AND_DOOR_UNLOCKED')) }}
      icon_template: mdi:car-door
      device_class: opening

######################################################################
# Binary Sensor: Door Rear Left
######################################################################

- platform: template
  sensors:
    ff590mr_door_rear_left:
      friendly_name: Posteriore Sinistra
      entity_id: sensor.ff590mr_lock
      value_template: >-     
        {{ not (is_state_attr('sensor.ff590mr_lock', 'doorStateRearLeft', 'DOOR_CLOSED_AND_DOOR_LOCKED') or
                is_state_attr('sensor.ff590mr_lock', 'doorStateRearLeft', 'DOOR_CLOSED_AND_DOOR_UNLOCKED')) }}
      icon_template: mdi:car-door
      device_class: opening

######################################################################
# Binary Sensor: Door Rear Right
######################################################################

- platform: template
  sensors:
    ff590mr_door_rear_right:
      friendly_name: Posteriore Destra
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ not (is_state_attr('sensor.ff590mr_lock', 'doorStateRearRight', 'DOOR_CLOSED_AND_DOOR_LOCKED') or
                is_state_attr('sensor.ff590mr_lock', 'doorStateRearRight', 'DOOR_CLOSED_AND_DOOR_UNLOCKED')) }}
      icon_template: mdi:car-door
      device_class: opening

######################################################################
# Binary Sensor: Trunk
######################################################################

- platform: template
  sensors:
    ff590mr_trunk:
      friendly_name: Bagagliaio
      entity_id: sensor.ff590mr_lock
      value_template: >-
        {{ not (is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_LOCKED') or
                is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_UNLOCKED')) }}
      icon_template: >-
        {% if (is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_LOCKED') or 
               is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_UNLOCKED')) %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}
      device_class: opening

######################################################################
# Binary Sensor: Windows Closed
######################################################################

- platform: template
  sensors:
    ff590mr_windows_closed_2:
      friendly_name: Finestrini
      entity_id: binary_sensor.ff590mr_windows_closed
      value_template: >-
        {{ not (is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontleft', 'CLOSED') and
                is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontright', 'CLOSED') and
                is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearleft', 'CLOSED') and
                is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearright', 'CLOSED')) }}
      icon_template: >-
        {% if (is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontleft', 'CLOSED') and
               is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontright', 'CLOSED') and
               is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearleft', 'CLOSED') and
               is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearright', 'CLOSED')) %}
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}      
      device_class: opening

######################################################################
# Binary Sensor: Window Front Left
######################################################################

- platform: template
  sensors:
    ff590mr_window_front_left:
      friendly_name: Anteriore Sinistro
      entity_id: binary_sensor.ff590mr_windows_closed
      value_template: >-
        {{ not is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontleft', 'CLOSED') }}
      icon_template: >-
        {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontleft', 'CLOSED') %}
        mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}      
      device_class: opening

######################################################################
# Binary Sensor: Window Front Right
######################################################################

- platform: template
  sensors:
    ff590mr_window_front_right:
      friendly_name: Anteriore Destro
      entity_id: binary_sensor.ff590mr_windows_closed
      value_template: >-
        {{ not is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontright', 'CLOSED') }}
      icon_template: >-
        {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontright', 'CLOSED') %}
        mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}   
      device_class: opening

######################################################################
# Binary Sensor: Window Rear Left
######################################################################

- platform: template
  sensors:
    ff590mr_window_rear_left:
      friendly_name: Posteriore Sinistro
      entity_id: binary_sensor.ff590mr_windows_closed
      value_template: >-
        {{ not is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearleft', 'CLOSED') }}
      icon_template: >-
        {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearleft', 'CLOSED') %}
        mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}   
      device_class: opening

######################################################################
# Binary Sensor: Window Rear Right
######################################################################

- platform: template
  sensors:
    ff590mr_window_rear_right:
      friendly_name: Posteriore Destro
      entity_id: binary_sensor.ff590mr_windows_closed
      value_template: >-
        {{ not is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearright', 'CLOSED') }}
      icon_template: >-
        {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearright', 'CLOSED') %}
        mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}   
      device_class: opening

######################################################################
# Binary Sensor: Warning Brake fluid
######################################################################

- platform: template
  sensors:
    ff590mr_warning_brakefluid:
      friendly_name: Liquido freni
      entity_id: binary_sensor.ff590mr_engine_light_warning
      value_template: >-
        {{ is_state_attr('binary_sensor.ff590mr_engine_light_warning', 'warningbrakefluid', 'true') }}
      device_class: problem

######################################################################
# Binary Sensor: Warning Wash Water
######################################################################

- platform: template
  sensors:
    ff590mr_warning_washwater:
      friendly_name: Liquido lavacristalli
      entity_id: binary_sensor.ff590mr_engine_light_warning
      value_template: >-
        {{ is_state_attr('binary_sensor.ff590mr_engine_light_warning', 'warningwashwater', 'true') }}
      device_class: problem

######################################################################
# Binary Sensor: Warning Coolant Level Low
######################################################################

- platform: template
  sensors:
    ff590mr_warning_coolantlevellow:
      friendly_name: Liquido raffreddamento
      entity_id: binary_sensor.ff590mr_engine_light_warning
      value_template: >-
        {{ is_state_attr('binary_sensor.ff590mr_engine_light_warning', 'warningcoolantlevellow', 'true') }}
      device_class: problem
