######################################################################
# Xiaomi MiJia Door & Window Contact Sensor (MCCGQ01LM)
######################################################################

- platform: "mqtt"
  name: "Porta Casa"
  state_topic: "zigbee2mqtt/0x00158d0003e79145"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

######################################################################
# Xiaomi Aqara Door & Window Contact Sensor (MCCGQ11LM)
######################################################################

- platform: "mqtt"
  name: "Porta Casa 2"
  state_topic: "zigbee2mqtt/0x00158d0002caf32f"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"
