######################################################################
# Xiaomi MiJia Door & Window Contact Sensor (MCCGQ01LM)
######################################################################

- platform: "mqtt"
  name: "Porta Casa: Stato"
  state_topic: "zigbee2mqtt/0x00158d0003e79145"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

######################################################################
# Xiaomi Aqara Door & Window Contact Sensor (MCCGQ11LM)
######################################################################

- platform: "mqtt"
  name: "Porta Casa 2: Stato"
  state_topic: "zigbee2mqtt/0x00158d0002caf32f"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

######################################################################
# Shelly Door/Window
######################################################################

#- platform: mqtt
#  name: "Porta Casa: Stato"
#  state_topic: "shellies/shellydw-B88F53/sensor/state"
#  payload_on: "open"
#  payload_off: "close"
#  #availability_topic: "shellies/shellydw-B88F53/online"
#  #payload_available: "true"
#  #payload_not_available: "false"
#  qos: 0
#  device_class: opening

