######################################################################
# Binary Sensor: Home Mode
######################################################################

- platform: template
  sensors:
    home_mode:
      friendly_name: Modalità Casa
      entity_id: sensor.home_mode
      value_template: >-
        {{ is_state('sensor.home_mode', 'giorno') 
           or is_state('sensor.home_mode', 'notte')
           or is_state('sensor.home_mode', 'vacanza') }}
      icon_template: >-
        {% if is_state('sensor.home_mode', 'giorno') %}
           mdi:white-balance-sunny
        {% elif is_state('sensor.home_mode', 'notte') %}
           mdi:weather-night
        {% elif is_state('sensor.home_mode', 'vacanza') %}
           mdi:airplane-takeoff
        {% endif %}

######################################################################
# Binary Sensor: Guard Mode
######################################################################

- platform: template
  sensors:
    guard_mode:
      friendly_name: Modalità Guardia
      entity_id: input_boolean.guard_mode
      value_template: >-
        {{ is_state('input_boolean.guard_mode', 'on') }}
      icon_template: >-
        {% if is_state('input_boolean.guard_mode', 'on') %}
           mdi:shield-home
        {% else %}
           mdi:shield-off
        {% endif %}

######################################################################
# Binary Sensor: Text Notification
######################################################################

- platform: template
  sensors:
    text_notifications:
      friendly_name: Notifiche testuali
      entity_id: input_boolean.text_notifications
      value_template: >-
        {{ is_state('input_boolean.text_notifications', 'on') }}
      icon_template: >-
        {% if is_state('input_boolean.text_notifications', 'on') %}
          mdi:message-bulleted
        {% else %}
          mdi:message-bulleted-off
        {% endif %}

######################################################################
# Binary Sensor: Speech Notification
######################################################################

- platform: template
  sensors:
    speech_notifications:
      friendly_name: Notifiche vocali
      entity_id: input_boolean.speech_notifications
      value_template: >-
        {{ is_state('input_boolean.speech_notifications', 'on') }}
      icon_template: >-
        {% if is_state('input_boolean.speech_notifications', 'on') %}
          mdi:speaker-wireless
        {% else %}
          mdi:speaker-off
        {% endif %}
