
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

home_latitude: 0
home_longitude: 0
home_elevation: 0
hitachi_latitude: 0
hitachi_longitude: 0
varazze_latitude: 0
varazze_longitude: 0
morgex_latitude: 0
morgex_longitude: 0
torretti_latitude: 0
torretti_longitude: 0
cisl_latitude: 0
cisl_longitude: 0

base_url: http://localhost

mail_server: localhost
mail_sender: email@domain.com
mail_recipient: email@domain.com

shelly_user: user
shelly_password: password

google_project: project
google_agent: 00
google_pin: "0000"

google_maps_username: email@domain.com
google_maps_password: password

google_calendar_id: id
google_calendar_secret: password

proxmox_host: host
proxmox_user: user
proxmox_password: password
proxmox_node: node

vapid_pub_key: 00
vapid_prv_key: 00
vapid_email: email@domain.com

nas_host: host
nas_mac: 00:00:00:00:00:00
nas_username: user

docker_host: host
docker_username: user

darksky_key: 0

hacs_token: 0

mb_vin: vin

netatmo_client_id: client_id
netatmo_client_secret: password

telegram_bot_name: "name_bot"
telegram_bot_username: "telegram_bot"
telegram_bot_access_token: token
telegram_bot_chat_id_group: 0
telegram_bot_chat_id_giorgio: 0
telegram_bot_chat_id_laura: 0
