language: python

python: "3.9"

before_install:
  - cp .secrets_travis.yaml secrets.yaml
  - cp credentials/.google_travis.json credentials/google.json
  # Replace pirateweather wather integration with darksky
  - sed -i  "s/pirateweather/darksky/" components/weather.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog
  - pip3 install python-dateutil

script:
  - hass -c . --script check_config --info all
