language: python

python: "3.7"

before_install:

install:
  - pip3 install homeassistant
  - pip3 install colorlog
  - pip3 install python-dateutil
  - cp .secrets_travis.yaml secrets.yaml
  - cp credentials/.google_travis.json credentials/google.json
  
script:
  - hass -c . --script check_config --info all
