language: python

python: "3.8"

before_install:
  - cp .secrets_travis.yaml secrets.yaml
  - cp credentials/.google_travis.json credentials/google.json

install:
  - pip3 install homeassistant
  - pip3 install colorlog
  - pip3 install python-dateutil

script:
  - hass -c . --script check_config --info all
