homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa Ravera-Testa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization folder
  customize: !include_dir_merge_named customizations/
  # Packages:
  packages: !include_dir_named packages/

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Lovelace UI Mode
lovelace: !include lovelace.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: !secret base_url
   # ssl_certificate: /config/certs/fullchain.pem
   # ssl_key: /config/certs/privkey.pem
   use_x_forwarded_for: true
   trusted_proxies:
     - 127.0.0.1       # traefik and home assistant in host mode
#     - 172.18.0.1      # traefik in host mode and homeassistant in network mode
#     - 172.18.0.200    # traefik and home in network mode
     - 192.168.0.1
   ip_ban_enabled: True
   login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
#  ignore:
#    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history: !include log/history.yaml

# View all events in a logbook
logbook: !include log/logbook.yaml

# Log Management
logger: !include log/logger.yaml

# Record Management
recorder: !include log/recorder.yaml

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Allow diagnosing system problems
system_health:

# Cloud
# cloud:

# Sensors
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/

# Lights
light: !include_dir_merge_list light/ 

# Covers
cover: !include_dir_merge_list cover/

# Switches
switch: !include_dir_merge_list switch/

# Multimedia
media_player: !include_dir_merge_list media_player/

# Inputs
input_boolean: !include_dir_merge_named input_boolean/
input_text: !include_dir_merge_named input_text/
input_datetime: !include_dir_merge_named input_datetime/
#input_number: !include_dir_merge_list input_number/

# Shell commands
shell_command: !include_dir_merge_named shell_command/

# Device Tracker
device_tracker: !include_dir_merge_list device_tracker/

# Person:
# person: !include_dir_merge_list person/

# Notification
notify: !include_dir_merge_list notify/

# Zones
zone: !include_dir_list zone/

# Group
group: !include_dir_merge_named group/

# Automations
automation: !include_dir_merge_list automation/

# Scripts
script: !include_dir_merge_named script/

# Mobile App
mobile_app:

# Wake on Lan
wake_on_lan:

# Components:
# Google Cast
cast: !include components/cast.yaml

# UPNP
upnp:

# Text to speech
tts: !include components/tts.yaml

# MQTT
mqtt: !include components/mqtt.yaml

# EQ3 Max Cube
maxcube: !include components/eq3max.yaml

# Google Assistant
google_assistant: !include components/google_assistant.yaml

# Weather
weather: !include components/weather.yaml

# Speed Test
speedtestdotnet: !include components/speedtest.yaml

###########################################################
# Custom Components
###########################################################

# Mercedes Me
mercedesmeapi: !include components/mercedesme.yaml

# HACS
hacs: !include components/hacs.yaml
