######################################################################
# Main Config
######################################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa Ravera-Testa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # URL
  internal_url: !secret base_url
  external_url: !secret base_url
  # Customization folder
  customize: !include_dir_merge_named customizations/
  # Packages:
  packages: !include_dir_named packages/

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Lovelace UI Mode (moved to UI)
#lovelace: !include lovelace.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   # ssl_certificate: /config/certs/fullchain.pem
   # ssl_key: /config/certs/privkey.pem
   use_x_forwarded_for: true
   trusted_proxies:
     - 127.0.0.1       # traefik and home assistant in host mode
#     - 172.18.0.1      # traefik in host mode and homeassistant in network mode
#     - 172.18.0.200    # traefik and home in network mode
     - 192.168.0.1
   ip_ban_enabled: True
   login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Allow diagnosing system problems
system_health:

# Cloud
# cloud:

# Mobile App
mobile_app:

# Text to speech
tts: !include components/tts.yaml

# Zones
zone: !include_dir_list zone/

# Group
group: !include_dir_merge_named groups/

# Automations
automation: !include_dir_merge_list automations/

# Scripts
script: !include_dir_merge_named scripts/

# Scene
#scene: !include_dir_merge_list scenes.yaml

######################################################################
# Logs
######################################################################

# Enables support for tracking state changes over time
history: !include log/history.yaml

# View all events in a logbook
logbook: !include log/logbook.yaml

# Log Management
logger: !include log/logger.yaml

# Record Management
recorder: !include log/recorder.yaml

######################################################################
# Main Elements
######################################################################

# Covers
cover: !include_dir_merge_list cover/

# Inputs
input_boolean: !include_dir_merge_named input_boolean/
input_datetime: !include_dir_merge_named input_datetime/
#input_number: !include_dir_merge_list input_number/
#input_select: !include_dir_merge_list input_select/
input_text: !include_dir_merge_named input_text/

# Lights
light: !include_dir_merge_list light/

# Sensors
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/

# Switches
#switch: !include_dir_merge_list switch/

# Utility Meter
utility_meter: !include_dir_merge_named utility_meter/

######################################################################
# Discovery Protocols
######################################################################

# Discover some devices automatically
discovery:

# Provides network configuration for integrations such as Zeroconf
network:

# Simple Service Discovery Protocol (SSDP)
ssdp:

# Zero-configuration networking (zeroconf)
zeroconf:

######################################################################
# Additional Components
######################################################################

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Device Tracker
device_tracker: !include_dir_merge_list device_tracker/

# Notification
notify: !include_dir_merge_list notify/

# Shell commands
shell_command: !include_dir_merge_named shell_command/

# Wake on Lan
wake_on_lan:

# Weather
weather: !include components/weather.yaml

######################################################################
# Integrations
######################################################################

# Google Assistant
google_assistant: !include components/google_assistant.yaml

# Google Calendar
google: !include components/google_calendar.yaml

# Homekit
homekit: !include components/homekit.yaml

# Netatmo
netatmo: !include components/netatmo.yaml

# Telegram
telegram_bot: !include components/telegram.yaml

# LG WebOS TV
webostv: !include components/webostv.yaml

###########################################################
# Custom Components
###########################################################

# Mercedes Me
#mercedesmeapi: !include components/mercedesme.yaml
