######################################################################
# Main Config
######################################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa Ravera-Testa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # Country
  country: IT
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Pick your currency code from the column Code of Wikipedia’s list of ISO 4217 active codes
  currency: EUR
  # URL
  external_url: !secret base_url
  internal_url: !secret base_url
  # Customization folder
  customize: !include_dir_merge_named customizations/
  media_dirs:
    media: "media"
  # Packages:
  packages: !include_dir_named packages/

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  # ssl_certificate: /config/certs/fullchain.pem
  # ssl_key: /config/certs/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1       # traefik and home assistant in host mode
    #- 172.18.0.1      # traefik in host mode and homeassistant in network mode
    #- 172.18.0.200    # traefik and home in network mode
    - 192.168.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

######################################################################
# Main Elements
######################################################################

# Automations
automation: !include automations.yaml
automation manual: !include_dir_merge_list automations/

# Backup
backup:

# Enables configuration UI
config:

# Counter
counter: !include_dir_merge_named counters/

# Energy
energy:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Go2rtc stream protocol
# got2rtc

# Hardware
# hardware:

# Home Assistant Alerts
homeassistant_alerts:

# Home Assistant Cloud
# cloud:

# Image upload
image_upload:

# Inputs
input_boolean: !include_dir_merge_named input_boolean/
input_button: !include_dir_merge_named input_button/
input_datetime: !include_dir_merge_named input_datetime/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/
input_text: !include_dir_merge_named input_text/

# Media Source
media_source:

# Mobile App Support
mobile_app:

# My Home Assistant
my:

# Person
person:

# Schedule
schedule:

# Scene
# scene: !include_dir_merge_list scenes.yaml

# Scripts
script: !include scripts.yaml
script manual: !include_dir_merge_named scripts/

# Stream
# stream:

# Track the sun
sun:

# Allow diagnosing system problems
system_health:

# Tags
tag:

# Timer
timer:

# Webhooks
webhook:

# Zones
zone: !include_dir_list zone/

######################################################################
# Logs
######################################################################

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook: !include log/logbook.yaml

# Log Management
logger: !include log/logger.yaml

# Record Management
recorder: !include log/recorder.yaml

######################################################################
# Discovery Protocols
######################################################################

# Bluetooth
# bluetooth:

# Discover DHCP requests for supported devices and services.
dhcp:

# Auto detection is based on the system routing next hop for the mDNS broadcast address
network:

# Simple Service Discovery Protocol (SSDP)
ssdp:

# USB Discovery
# usb:

# Zero-configuration networking (zeroconf)
zeroconf:

######################################################################
# Voice Interface
######################################################################

# Assist pipeline
# assist_pipeline:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

######################################################################
# Additional Components
######################################################################

# Binary Sensors
binary_sensor: !include_dir_merge_list binary_sensor/

# Covers
cover: !include_dir_merge_list cover/

# Device Tracker
device_tracker: !include_dir_merge_list device_tracker/

# Group
group: !include_dir_merge_named groups/

# Lights
light: !include_dir_merge_list light/

# Notification
notify: !include_dir_merge_list notify/

# Sensors
sensor: !include_dir_merge_list sensor/

# Shell commands
shell_command: !include_dir_merge_named shell_command/

# Switches
switch: !include_dir_merge_list switch/

# Utility Meter
utility_meter: !include_dir_merge_named utility_meter/

# Text to speech
tts: !include components/tts.yaml

# Templates
template: !include_dir_merge_list template/

######################################################################
# Integrations
######################################################################

# Amazon Alexa
alexa: !include components/amazon_alexa.yaml

# Google Assistant
google_assistant: !include components/google_assistant.yaml

# Homekit
homekit: !include components/homekit.yaml

# MQTT
mqtt:
  light: !include_dir_merge_list mqtt/light/

# Proxmox
proxmoxve: !include components/proxmox.yaml

# Monitor Docker
monitor_docker: !include components/monitor_docker.yaml

# Wake on Lan
wake_on_lan:
