######################################################################
# Lovelace UI - Panoramica
######################################################################

title: Casa Ravera-Testa
background: var(--background-image)
views:
######################################################################
# Main View
######################################################################
  - title: Principale
    id: main
    icon: mdi:home
    badges:
      - device_tracker.google_maps_115265981849847357125
      - device_tracker.google_maps_103158638433668748797
      - device_tracker.wdd1760081v167576    
      - sensor.time
      - binary_sensor.porta_casa
      - binary_sensor.home_mode
      - binary_sensor.guard_mode
      - binary_sensor.speech_notifications
      #- binary_sensor.text_notifications
      - binary_sensor.alarms
      - sensor.potenza_istantanea
    cards:
    - type: picture-glance
      title: Cucina
      show_state: true
      state_image:
        "on": /local/images/rooms/cucina_on.jpg
        "off": /local/images/rooms/cucina_off.jpg
      entity: light.luce_cucina
      entities:
      - light.luce_cucina
      - cover.tapparella_cucina
      - climate.cucina_termostato_cucina
      - media_player.google_home

    - type: picture-glance
      title: Sala
      show_state: true
      state_image:
        "on": /local/images/rooms/sala_on.jpg
        "off": /local/images/rooms/sala_off.jpg
      entity: group.lights_livingroom
      entities: 
      - light.luce_sala
      - light.luce_divano
      #- light.luce_divano_bianca
      - cover.tapparella_sala
      - climate.sala_termostato_sala
      - media_player.tv_sala

    - type: picture-glance
      title: Corridoio
      show_state: true
      state_image:
        "on": /local/images/rooms/corridoio_on.jpg
        "off": /local/images/rooms/corridoio_off.jpg
      entity: light.luce_corridoio
      image: 
      entities: 
      - light.luce_corridoio

    - type: picture-glance
      title: Bagno
      show_state: true
      state_image:
        "on": /local/images/rooms/bagno_on.jpg
        "off": /local/images/rooms/bagno_off.jpg
      entity: group.lights_bathroom
      entities: 
      - light.luce_bagno
      - light.luce_specchio
      - climate.bagno_termostato_bagno

    - type: picture-glance
      title: Studio
      show_state: true
      state_image:
        "on": /local/images/rooms/studio_on.jpg
        "off": /local/images/rooms/studio_off.jpg
      entity: light.luce_studio
      entities: 
      - light.luce_studio
      - cover.tapparella_studio
      - climate.studio_termostato_studio

    - type: picture-glance
      title: Camera
      show_state: true
      state_image:
        "on": /local/images/rooms/camera_on.jpg
        "off": /local/images/rooms/camera_off.jpg
      entity: light.luce_camera
      entities: 
      - light.luce_camera
      - cover.tapparella_camera
      - climate.camera_termostato_camera

    - type: picture-glance
      title: Balcone
      show_state: true
      state_image:
        "on": /local/images/rooms/balcone_on.jpg
        "off": /local/images/rooms/balcone_off.jpg
      entity: light.luce_balcone
      entities: 
      - light.luce_balcone

    - type: entities
      title: Modalità Casa
      show_header_toggle: false
      entities:
      - input_boolean.home_mode_day
      - input_boolean.home_mode_night
      - input_boolean.home_mode_away
      - input_boolean.guard_mode
      
    - type: sensor
      entity: sensor.potenza_istantanea
      name: Consumo Energetico
      graph: line
      unit: W
      detail: 2

    - type: entities
      title: Controlli Vari
      show_header_toggle: false
      entities:
      - script.speech_status
      - script.speech_consumption
      - automation.risveglio_giorgio

    - type: entities
      title: Eventi
      show_header_toggle: false
      entities:
      - input_datetime.away_mode_end

    - type: entity-filter
      title: Eventi da Segnalare
      entities:
        - input_boolean.alarms
        - input_boolean.door_alarm
        - input_boolean.update      
        - binary_sensor.ff590mr_engine_light_warning
        - binary_sensor.ff590mr_warning_brakefluid
        - binary_sensor.ff590mr_warning_washwater
        - binary_sensor.ff590mr_warning_coolantlevellow
      state_filter:
      - "on"

######################################################################
# Lights
######################################################################
  - title: Luci
    id: light
    icon: mdi:lightbulb
    badges:
      - light.luce_cucina
      - light.luce_corridoio
      - light.luce_sala
      - light.luce_divano
      - light.luce_bagno
      - light.luce_specchio
      - light.luce_studio
      - light.luce_camera
      - light.luce_balcone
    cards:
    - type: entities
      title: Comandi luci
      show_header_toggle: false
      entities:
        - light.luci_casa
        - light.luce_cucina
        - light.luce_corridoio
        - light.luci_sala
        - light.luce_sala
        - light.luce_divano
        - light.luci_bagno
        - light.luce_bagno
        - light.luce_specchio
        - light.luce_studio
        - light.luce_camera
        - light.luce_balcone
    
    - type: light
      name: Luci Casa
      entity: light.luci_casa

    - type: light
      name: Luce Cucina
      entity: light.luce_cucina

    - type: light
      name: Luce Corridoio
      entity: light.luce_corridoio

    - type: light
      name: Luci Sala
      entity: light.luci_sala

    - type: light
      name: Luce Divano
      entity: light.luce_divano

    - type: light
      name: Luci Bagno
      entity: light.luci_bagno

    - type: light
      name: Luce Bagno
      entity: light.luce_bagno

    - type: light
      name: Luce Specchio
      entity: light.luce_specchio

    - type: light
      name: Luce Studio
      entity: light.luce_studio

    - type: light
      name: Luce Camera
      entity: light.luce_camera

    - type: light
      name: Luce Balcone
      entity: light.luce_balcone

######################################################################
# Covers
######################################################################
  - title: Tapparelle
    id: covers
    #icon: mdi:window-closed
    icon: mdi:window-shutter
    badges:
      - sensor.tapparella_cucina
      - sensor.tapparella_sala
      - sensor.tapparella_studio
      - sensor.tapparella_camera
    cards:
      - type: entities
        title: Comandi tapparelle
        show_header_toggle: false
        entities:
          - cover.tapparelle_casa
          - type: custom:slider-entity-row
            entity: cover.tapparelle_casa
            full_row: true
          - cover.tapparella_cucina
          - type: custom:slider-entity-row
            entity: cover.tapparella_cucina
            full_row: true
          - cover.tapparella_sala
          - type: custom:slider-entity-row
            entity: cover.tapparella_sala
            full_row: true
          - cover.tapparella_studio
          - type: custom:slider-entity-row
            entity: cover.tapparella_studio
            full_row: true
          - cover.tapparella_camera
          - type: custom:slider-entity-row
            entity: cover.tapparella_camera
            full_row: true

######################################################################
# Climate
######################################################################
  - title: Termostato
    id: climate
    icon: mdi:thermometer
    badges:
      - sensor.termostato_cucina
      - sensor.termostato_sala
      - sensor.termostato_bagno
      - sensor.termostato_studio
      - sensor.termostato_camera
    cards:
      - type: thermostat
        entity: climate.cucina_termostato_cucina
      - type: thermostat
        entity: climate.sala_termostato_sala
      - type: thermostat
        entity: climate.bagno_termostato_bagno
      - type: thermostat
        entity: climate.studio_termostato_studio
      - type: thermostat
        entity: climate.camera_termostato_camera
        
      - type: entities
        title: Operazione sui Dispositivi
        show_header_toggle: false
        entities:
        - type: call-service
          name: Cucina
          action_name: Attiva Boost
          service: climate.set_preset_mode
          service_data:
            entity_id: climate.cucina_termostato_cucina
            preset_mode: boost
        - type: call-service
          name: Sala
          action_name: Attiva Boost
          service: climate.set_preset_mode
          service_data:
            entity_id: climate.sala_termostato_sala
            preset_mode: boost
        - type: call-service
          name: Bagno
          action_name: Attiva Boost
          service: climate.set_preset_mode
          service_data:
            entity_id: climate.bagno_termostato_bagno
            preset_mode: boost
        - type: call-service
          name: Studio
          action_name: Attiva Boost
          service: climate.set_preset_mode
          service_data:
            entity_id: climate.studio_termostato_studio
            preset_mode: boost
        - type: call-service
          name: Camera
          action_name: Attiva Boost
          service: climate.set_preset_mode
          service_data:
            entity_id: climate.camera_termostato_camera
            preset_mode: boost

######################################################################
# People
######################################################################
  - title: People
    id: people
    icon: mdi:account-multiple
    badges:
      - device_tracker.google_maps_115265981849847357125
      - device_tracker.google_maps_103158638433668748797
      - device_tracker.google_maps_113099283296073047871
      - device_tracker.google_maps_108517379615429477419
    cards:
      - type: map
        #title: Giorgio
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_115265981849847357125
        hours_to_show: 48
      - type: map
        #title: Laura
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_103158638433668748797
        hours_to_show: 48
      - type: map
        #title: Anna
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_113099283296073047871
        hours_to_show: 48
      - type: map
        #title: Assunta
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_108517379615429477419
        hours_to_show: 48

######################################################################
# Car
######################################################################
  - title: Auto
    id: car
    icon: mdi:car
    badges:
      - device_tracker.wdd1760081v167576  
      - sensor.ff590mr_odometer
      - sensor.ff590mr_fuel_level
#      - binary_sensor.ff590mr_park_brake_status
#      - binary_sensor.ff590mr_engine_light_warning
      - binary_sensor.ff590mr_locked
      - binary_sensor.ff590mr_doors_closed
      - binary_sensor.ff590mr_windows_closed_2
    cards:
      #- type: gauge
      #  title: "Livello Carburante"
      #  unit: '%'
      #  entity: sensor.ff590mr_tank_level
      #  severity:
      #    red: 0
      #    yellow: 30
      #    green: 60
      #- type: entity-button
      #  name: Blocco/Sblocco Vettura
      #  icon: mdi:key
      #  entity: lock.ff590mr_lock
      - type: entities
        title: "Mercedes A200d: Sensori"
        show_header_toggle: false
        entities:
          #- lock.ff590mr_lock
          - switch.ff590mr_lock
          - binary_sensor.ff590mr_doors_closed
          - binary_sensor.ff590mr_windows_closed_2
          #- binary_sensor.ff590mr_park_brake_status
          #- device_tracker.wdd1760081v167576
      - type: entities
        title: "Mercedes A200d: Allarmi"
        show_header_toggle: false
        entities:
          - binary_sensor.ff590mr_engine_light_warning
          - binary_sensor.ff590mr_warning_brakefluid
          - binary_sensor.ff590mr_warning_washwater
          - binary_sensor.ff590mr_warning_coolantlevellow
      - type: entities
        title: "Mercedes A200d: Pneumatici"
        show_header_toggle: false
        entities:
          - sensor.ff590mr_tire_pressure_front_left
          - sensor.ff590mr_tire_pressure_front_right
          - sensor.ff590mr_tire_pressure_rear_left
          - sensor.ff590mr_tire_pressure_rear_right
      - type: entities
        title: "Mercedes A200d: Porte"
        show_header_toggle: false
        entities:
          - binary_sensor.ff590mr_door_front_left
          - binary_sensor.ff590mr_door_front_right
          - binary_sensor.ff590mr_door_rear_left
          - binary_sensor.ff590mr_door_rear_right
          - binary_sensor.ff590mr_trunk
          - binary_sensor.ff590mr_fuel_lid
      - type: entities
        title: "Mercedes A200d: Finestrini"
        show_header_toggle: false
        entities:
          - binary_sensor.ff590mr_window_front_left
          - binary_sensor.ff590mr_window_front_right
          - binary_sensor.ff590mr_window_rear_left
          - binary_sensor.ff590mr_window_rear_right
      - type: entities
        title: "Mercedes A200d: Dati"
        show_header_toggle: false
        entities:
          - sensor.ff590mr_odometer
          - sensor.ff590mr_distance_since_start
          - sensor.ff590mr_distance_since_reset
          - sensor.ff590mr_fuel_level
          - sensor.ff590mr_liquid_consumption_start
          - sensor.ff590mr_liquid_consumption_reset
          - sensor.ff590mr_service_interval_days
      - type: map
        #title: Mercedes
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.wdd1760081v167576

######################################################################
# Train
######################################################################
#  - title: Treni
#    id: train
#    icon: mdi:train
#    cards:
#      - type: entities
#        title: "Savona - Genova Sampierdarena"
#        show_header_toggle: false
#        entities:
#          #- sensor.train_11341
#          #- sensor.train_11233
#          - sensor.treno_7_35
#          #- sensor.train_11283
#      - type: entities
#        title: "Genova Sampierdarena - Savona"
#        show_header_toggle: false
#        entities:
#          - sensor.train_2188
#          - sensor.train_11354

######################################################################
# Power Status
######################################################################
  - title: Monitoraggio Energetico
    id: power
    icon: mdi:flash
    badges:
      - sensor.potenza_istantanea
      - sensor.potenza_reattiva
      - sensor.tensione
    cards:
      - type: sensor
        entity: sensor.potenza_istantanea
        name: Consumo Energetico
        graph: line
        unit: W
        detail: 2
#      - type: sensor
#        entity: sensor.potenza_reattiva
#        name: Potenza Reattiva
#        graph: line
#        unit: var
#        detail: 1
#      - type: sensor
#        entity: sensor.energia_assorbita
#        name: Energia Assorbita
#        graph: line
#        unit: KVh
#        detail: 1
#      - type: sensor
#        entity: sensor.voltaggio
#        name: Voltaggio
#        graph: line
#        unit: V
#        detail: 1

######################################################################
# Alarms
######################################################################
  - title: Allarmi
    id: allarmi
    icon: mdi:alarm-light-outline
    badges:
      - binary_sensor.alarms
    cards:
    - type: entities
      title: Allarmi Casa
      show_header_toggle: false
      entities:
      - input_boolean.alarms
      #- input_boolean.door_alarm
      
######################################################################
# Weather
######################################################################
  - title: Meteo
    id: meteo
    icon: mdi:weather-sunny
    badges:
      - sun.sun
      - sensor.yr_symbol
    cards:
      - type: weather-forecast
        entity: weather.meteo_savona
      - type: weather-forecast
        entity: weather.meteo_morgex
#      - type: entities
#        title: Oggi
#        show_header_toggle: false
#        entities:
#        - sensor.dark_sky_summary
#        - sensor.dark_sky_temperature
#        - sensor.dark_sky_cloud_coverage
#        - sensor.dark_sky_precip_probability
#        - sensor.dark_sky_precip_intensity
#        - sensor.dark_sky_wind_speed
#        - sensor.dark_sky_visibility
#        - sensor.dark_sky_humidity
#        - sensor.dark_sky_pressure
#        - sensor.dark_sky_uv_index
#      - type: entities
#        title: Domani
#        show_header_toggle: false
#        entities:
#        - sensor.dark_sky_summary_0
#        - sensor.dark_sky_daytime_high_temperature_0
#        - sensor.dark_sky_overnight_low_temperature_0
#        - sensor.dark_sky_cloud_coverage_0
#        - sensor.dark_sky_precip_probability_0
#        - sensor.dark_sky_precip_intensity_0
#        - sensor.dark_sky_wind_speed_0
#        - sensor.dark_sky_visibility_0
#        - sensor.dark_sky_humidity_0
#        - sensor.dark_sky_pressure_0
#        - sensor.dark_sky_uv_index_0
