######################################################################
# Lovelace UI Configuration
######################################################################

title: Casa Ravera-Testa
views:

######################################################################
# Main View
######################################################################
  - title: Principale
    id: main
    icon: mdi:home
    badges:
      - device_tracker.google_maps_115265981849847357125
      - device_tracker.google_maps_103158638433668748797
      - device_tracker.wdd1760081v167576    
      - sensor.time
      - binary_sensor.home_mode
      - binary_sensor.speech_notifications
      - binary_sensor.text_notifications
    cards:
    - type: picture-glance
      title: Cucina
      show_state: true
      state_image:
        "on": /local/rooms/cucina_on.jpg
        "off": /local/rooms/cucina_off.jpg
      entity: light.luce_cucina
      entities:
      - light.luce_cucina
      - cover.tapparella_cucina
      - climate.cucina_termostato_cucina
      - media_player.google_home

    - type: picture-glance
      title: Sala
      show_state: true
      state_image:
        "on": /local/rooms/sala_on.jpg
        "off": /local/rooms/sala_off.jpg
      entity: light.luce_divano
      entities: 
      - light.luce_divano
      - light.luce_divano_bianca
      - cover.tapparella_sala
      - climate.sala_termostato_sala
      - media_player.tv_sala

    - type: picture-glance
      title: Corridoio
      show_state: true
      state_image:
        "on": /local/rooms/corridoio_on.jpg
        "off": /local/rooms/corridoio_off.jpg
      entity: light.luce_corridoio
      image: 
      entities: 
      - light.luce_corridoio

    - type: picture-glance
      title: Bagno
      show_state: true
      state_image:
        "on": /local/rooms/bagno_on.jpg
        "off": /local/rooms/bagno_off.jpg
      entity: light.luce_bagno
      entities: 
      - light.luce_bagno
      - light.luce_specchio
      - climate.bagno_termostato_bagno

    - type: picture-glance
      title: Studio
      show_state: true
      state_image:
        "on": /local/rooms/studio_on.jpg
        "off": /local/rooms/studio_off.jpg
      entity: light.luce_studio
      entities: 
      - light.luce_studio
      - cover.tapparella_studio
      - climate.studio_termostato_studio

    - type: picture-glance
      title: Camera
      show_state: true
      state_image:
        "on": /local/rooms/camera_on.jpg
        "off": /local/rooms/camera_off.jpg
      entity: light.luce_camera
      entities: 
      - light.luce_camera
      - cover.tapparella_camera
      - climate.camera_termostato_camera

    - type: entities
      title: Modalità Casa
      show_header_toggle: false
      entities:
      - input_boolean.home_mode_day
      - input_boolean.home_mode_night
      - input_boolean.home_mode_away
      
    - type: entities
      title: Controlli Vari
      show_header_toggle: false
      entities:
      - script.speech_status

######################################################################
# Lights
######################################################################
  - title: Luci
    id: light
    icon: mdi:lightbulb
    badges:
      - light.luce_cucina
      - light.luce_corridoio
      - light.luce_divano
      - light.luce_bagno
      - light.luce_specchio
      - light.luce_studio
      - light.luce_camera
    cards:
    - type: entities
      title: Comandi luci
      show_header_toggle: false
      entities:
        - light.luci_casa
        - light.luce_cucina
        - light.luce_corridoio
        - light.luci_sala
        - light.luce_divano
        - light.luce_divano_bianca
        - light.luci_bagno
        - light.luce_bagno
        - light.luce_specchio
        - light.luce_studio
        - light.luce_camera
    
    - type: light
      name: Luci Casa
      entity: light.luci_casa

    - type: light
      name: Luce Cucina
      entity: light.luce_cucina

    - type: light
      name: Luce Corridoio
      entity: light.luce_corridoio

    - type: light
      name: Luci Sala
      entity: light.luci_sala

    - type: light
      name: Luce Divano
      entity: light.luce_divano

    - type: light
      name: Luce Divano Bianca
      entity: light.luce_divano_bianca

    - type: light
      name: Luci Bagno
      entity: light.luci_bagno

    - type: light
      name: Luce Bagno
      entity: light.luce_bagno

    - type: light
      name: Luce Specchio
      entity: light.luce_specchio

    - type: light
      name: Luce Studio
      entity: light.luce_studio

    - type: light
      name: Luce Camera
      entity: light.luce_camera

######################################################################
# Covers
######################################################################
  - title: Tapparelle
    id: covers
    icon: mdi:window-closed
    badges:
      - sensor.tapparella_cucina
      - sensor.tapparella_sala
      - sensor.tapparella_studio
      - sensor.tapparella_camera
    cards:
      - type: entities
        title: Comandi tapparelle
        show_header_toggle: false
        entities:
          - cover.tapparelle_casa
          - cover.tapparella_cucina
          - cover.tapparella_sala
          - cover.tapparella_studio
          - cover.tapparella_camera

######################################################################
# Climate
######################################################################
  - title: Termostato
    id: climate
    icon: mdi:thermometer
    badges:
      - sensor.termostato_cucina
      - sensor.termostato_sala
      - sensor.termostato_bagno
      - sensor.termostato_studio
      - sensor.termostato_camera
    cards:
      - type: thermostat
        entity: climate.cucina_termostato_cucina
      - type: thermostat
        entity: climate.sala_termostato_sala
      - type: thermostat
        entity: climate.bagno_termostato_bagno
      - type: thermostat
        entity: climate.studio_termostato_studio
      - type: thermostat
        entity: climate.camera_termostato_camera

######################################################################
# Multimedia
######################################################################
  - title: Dispositivi Multimediali
    id: multimedia
    icon: mdi:television
    cards:
      - type: entities
        title: Google Home Cucina
        show_header_toggle: false
        entities:
        - media_player.google_home
        - input_text.google_home_speak

      - type: vertical-stack
        title: TV Sala
        cards:
        - type: media-control
          entity: media_player.tv_sala
        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: script.tv_volume_up
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.tv_volume_up
          - type: entity-button
            entity: script.tv_volume_down
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.tv_volume_down
          - type: entity-button
            entity: script.tv_volume_mute          
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.tv_volume_mute

        - type: horizontal-stack
          cards:
          - type: entity-button
            entity: script.tv_play_pause
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.tv_play_pause
          - type: entity-button
            entity: script.tv_toggle
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.tv_toggle
          - type: entity-button
            entity: input_text.tv_change_channel

      - type: vertical-stack
        title: TV Sala
        cards:
        - type: horizontal-stack
          cards:
          - type: entity-button
            name: Affare
            icon: mdi:numeric-1
            entity: script.laura_voice
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.laura_voice_1
          - type: entity-button
            name: Belan
            icon: mdi:numeric-2
            entity: script.laura_voice
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.laura_voice_2
          - type: entity-button
            name: Schifezza
            icon: mdi:numeric-3
            entity: script.laura_voice
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.laura_voice_3

######################################################################
# People
######################################################################
  - title: People
    id: people
    icon: mdi:account-multiple
    badges:
      - device_tracker.google_maps_115265981849847357125
      - device_tracker.google_maps_103158638433668748797
      - device_tracker.google_maps_113099283296073047871
      - device_tracker.google_maps_108517379615429477419
    cards:
      - type: map
        #title: Giorgio
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_115265981849847357125
      - type: map
        #title: Laura
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_103158638433668748797
      - type: map
        #title: Anna
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_113099283296073047871
      - type: map
        #title: Assunta
        aspect_ratio: 16:9
        default_zoom: 15
        entities:
        - device_tracker.google_maps_108517379615429477419

######################################################################
# Car
######################################################################
  - title: Auto
    id: car
    icon: mdi:car
    badges:
      - device_tracker.wdd1760081v167576  
      - sensor.ff590mr_odometer
      - sensor.ff590mr_fuel_level
#      - binary_sensor.ff590mr_park_brake_status
#      - binary_sensor.ff590mr_status_decklid
      - binary_sensor.ff590mr_engine_light_warning
      #- binary_sensor.ff590mr_tire_warning
      - binary_sensor.ff590mr_doors_closed
      - binary_sensor.ff590mr_windows_closed
      - lock.ff590mr_lock
    cards:
      #- type: gauge
      #  title: "Livello Carburante"
      #  unit: '%'
      #  entity: sensor.ff590mr_tank_level
      #  severity:
      #    red: 0
      #    yellow: 30
      #    green: 60

      - type: entities
        title: "Mercedes A200d: Sensori"
        show_header_toggle: false
        entities:
          - binary_sensor.ff590mr_park_brake_status
          - binary_sensor.ff590mr_status_decklid
          - binary_sensor.ff590mr_warning_brakefluid
          - binary_sensor.ff590mr_warning_washwater
          - binary_sensor.ff590mr_warning_coolantlevellow
          #- device_tracker.wdd1760081v167576

      - type: entities
        title: "Mercedes A200d: Ruote"
        show_header_toggle: false
        entities:
          - sensor.ff590mr_tire_pressure_front_left
          - sensor.ff590mr_tire_pressure_front_right
          - sensor.ff590mr_tire_pressure_rear_left
          - sensor.ff590mr_tire_pressure_rear_right
      
      - type: entities
        title: "Mercedes A200d: Finestrini"
        show_header_toggle: false
        entities:
          - sensor.ff590mr_window_front_left
          - sensor.ff590mr_window_front_right
          - sensor.ff590mr_window_rear_left
          - sensor.ff590mr_window_rear_right
      
      - type: entities
        title: "Mercedes A200d: Porte"
        show_header_toggle: false
        entities:
          - sensor.ff590mr_door_front_left
          - sensor.ff590mr_door_front_right
          - sensor.ff590mr_door_rear_left
          - sensor.ff590mr_door_rear_right

      - type: entities
        title: "Mercedes A200d: Sblocco serrature"
        show_header_toggle: false
        entities:
          - sensor.ff590mr_door_lock_vehicle
          - sensor.ff590mr_door_lock_front_left
          - sensor.ff590mr_door_lock_front_right
          - sensor.ff590mr_door_lock_rear_left
          - sensor.ff590mr_door_lock_rear_right
          - sensor.ff590mr_door_lock_gas
          - sensor.ff590mr_door_lock_decklid

      - type: entities
        title: "Mercedes A200d: Dati"
        show_header_toggle: false
        entities:
          #- sensor.ff590mr_electric_range_skip_indicator
          #- sensor.ff590mr_electric_consumption_reset
          #- sensor.ff590mr_electric_consumption_start
          - sensor.ff590mr_licenseplate
          - sensor.ff590mr_liquid_consumption_reset
          - sensor.ff590mr_liquid_consumption_start
          - sensor.ff590mr_odometer_2
          #- sensor.ff590mr_liquid_range
          #- sensor.ff590mr_electric_distance_since_start
          #- sensor.ff590mr_tank_level
          #- sensor.ff590mr_electric_distance_ctritical_reset
          - sensor.ff590mr_distance_since_reset
          - sensor.ff590mr_distance_since_start

######################################################################
# Train
######################################################################
#  - title: Treni
#    id: train
#    icon: mdi:train
#    cards:
#      - type: entities
#        title: "Savona - Genova Sampierdarena"
#        show_header_toggle: false
#        entities:
#          #- sensor.train_11341
#          #- sensor.train_11233
#          - sensor.treno_7_35
#          #- sensor.train_11283
#      - type: entities
#        title: "Genova Sampierdarena - Savona"
#        show_header_toggle: false
#        entities:
#          - sensor.train_2188
#          - sensor.train_11354
 
######################################################################
# Network
######################################################################
  - title: Dispositivi di Rete
    id: network
    icon: mdi:lan
    cards:
      - type: glance
        name: External IP 
        entities:
          - sensor.ip_1
          - sensor.ip_2
      - type: glance
        title: Speed Test
        entities:
        - sensor.speedtest_ping
        - sensor.speedtest_download
        - sensor.speedtest_upload          
      - type: glance
        title: pfSense
        entities: 
          - sensor.freebsd_router_kbyte_sec_received
          - sensor.freebsd_router_kbyte_sec_sent

######################################################################
# Weather
######################################################################
  - title: Meteo
    id: meteo
    icon: mdi:weather-sunny
    badges:
      - sun.sun
      - sensor.yr_symbol
    cards:
      - type: weather-forecast
        entity: weather.meteo_savona
      - type: weather-forecast
        entity: weather.meteo_morgex
#      - type: entities
#        title: Oggi
#        show_header_toggle: false
#        entities:
#        - sensor.dark_sky_summary
#        - sensor.dark_sky_temperature
#        - sensor.dark_sky_cloud_coverage
#        - sensor.dark_sky_precip_probability
#        - sensor.dark_sky_precip_intensity
#        - sensor.dark_sky_wind_speed
#        - sensor.dark_sky_visibility
#        - sensor.dark_sky_humidity
#        - sensor.dark_sky_pressure
#        - sensor.dark_sky_uv_index
#      - type: entities
#        title: Domani
#        show_header_toggle: false
#        entities:
#        - sensor.dark_sky_summary_0
#        - sensor.dark_sky_daytime_high_temperature_0
#        - sensor.dark_sky_overnight_low_temperature_0
#        - sensor.dark_sky_cloud_coverage_0
#        - sensor.dark_sky_precip_probability_0
#        - sensor.dark_sky_precip_intensity_0
#        - sensor.dark_sky_wind_speed_0
#        - sensor.dark_sky_visibility_0
#        - sensor.dark_sky_humidity_0
#        - sensor.dark_sky_pressure_0
#        - sensor.dark_sky_uv_index_0

######################################################################
# Settings
######################################################################
  - title: Configurazione
    id: settings
    icon: mdi:settings
    badges:
      - binary_sensor.home_mode
      - binary_sensor.speech_notifications
      - binary_sensor.text_notifications
    cards:
      - type: entities
        title: Automazioni
        show_header_toggle: false
        entities:
        - group.all_automations        
      - type: entities
        title: Configurazione Notifiche
        show_header_toggle: false
        entities:
        - input_boolean.speech_notifications
        - input_boolean.text_notifications

      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: entities
            title: Controlli
            show_header_toggle: false
            entities:
            - script.homeassistant_restart
            - script.homeassistant_clearlog
            - script.homeassistant_upgrade
#          - type: entity-button
#            entity: script.homeassistant_restart
#            tap_action:
#              action: call-service
#              service: script.turn_on
#              service_data:
#                entity_id: script.homeassistant_restart
#          - type: entity-button
#            entity: script.homeassistant_clearlog
#            tap_action:
#              action: call-service
#              service: script.turn_on
#              service_data:
#                entity_id: script.homeassistant_clearlog
#          - type: entity-button
#            entity: script.homeassistant_upgrade
#            tap_action:
#              action: call-service
#              service: script.turn_on
#              service_data:
#                entity_id: script.homeassistant_upgrade

        - type: horizontal-stack
          cards:          
          - type: entities
            title: Operazione sui Dispositivi
            show_header_toggle: false
            entities:
            - script.shelly_upgrade
#          - type: entity-button
#            entity: script.shelly_upgrade
#            tap_action:
#              action: call-service
#              service: script.turn_on
#              service_data:
#                entity_id: script.shelly_upgrade
