######################################################################
# Mercedes Package - Customizations
######################################################################

homeassistant:
  customize:
    # Binary Sensors
    binary_sensor.ff590mr_engine_light_warning:
      friendly_name: Stato Generale
      device_class: problem
      icon: mdi:hazard-lights
      # warningbrakefluid, warningwashwater, warningcoolantlevellow, warninglowbattery
    binary_sensor.ff590mr_park_brake_status:
      friendly_name: Freno a mano
      device_class: plug
      icon: mdi:car-brake-parking
      # preWarningBrakeLiningWear
    binary_sensor.ff590mr_tire_warning:
      friendly_name: Allarme Pneumatici
      device_class: problem
      icon: mdi:car-tire-alert
      # tirepressureRearLeft, tirepressureRearRight, tirepressureFrontRight, tirepressureFrontLeft, 
      # tirewarningsrdk, tirewarningsprwtireMarkerFrontRight, tireMarkerFrontLeft, tireMarkerRearLeft, tireMarkerRearRight, 
      # tireWarningRollup, lastTirepressureTimestamp
    binary_sensor.ff590mr_windows_closed:
      friendly_name: Finestrini
      device_class: opening
      icon: mdi:window-closed
      # windowstatusrearleft, windowstatusrearright, windowstatusfrontright, windowstatusfrontleft

    # Lock
    lock.ff590mr_lock:
      friendly_name: Blocco Sblocco 
      icon: mdi:lock-open
      
    # Sensors
    sensor.ff590mr_fuel_level:
      friendly_name: Livello Carburante
      icon: mdi:gas-station
    sensor.ff590mr_lock:
      friendly_name: Veicolo
      icon: mdi:lock-open
      # doorStateFrontLeft, doorStateFrontRight, doorStateRearLeft, doorStateRearRight, 
      # frontLeftDoorLocked, frontRightDoorLocked, rearLeftDoorLocked, rearRightDoorLocked, 
      # frontLeftDoorClosed, frontRightDoorClosed, rearLeftDoorClosed, rearRightDoorClosed, 
      # doorsClosed, trunkStateRollup, sunroofstatus
    sensor.ff590mr_odometer:
      friendly_name: Km Percorsi
      icon: mdi:road-variant
      # distanceReset, distanceStart, liquidconsumptionstart, liquidconsumptionreset, liquidRangeSkipIndication, serviceintervaldays, tanklevelpercent, tankReserveLamp
