######################################################################
# Mercedes Package - Doors Sensors
######################################################################

binary_sensor:
  ######################################################################
  # Binary Sensor: Doors Lock
  #
  # ff590mr_lock:
  # 0 -> unlocked
  # 1 -> internal locked
  # 2 -> external locked
  ######################################################################
  - platform: template
    sensors:
      ff590mr_locked:
        friendly_name: Blocco Vettura
        value_template: >-
          {% if not is_state('sensor.ff590mr_lock', '2') %}
            true
          {% else %}
            false
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2') %}
            mdi:lock
          {% else %}
            mdi:lock-open
          {% endif %}
        device_class: lock

  ######################################################################
  # Binary Sensor: Doors Closed
  #
  # doorStatusOverall:
  #   1 -> closed
  #   0 -> opened
  ######################################################################
  - platform: template
    sensors:
      ff590mr_doors_closed:
        friendly_name: Porte
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorStatusOverall', '0') }}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2') %}
            mdi:car-door-lock
          {% else %}
            {% if is_state_attr('sensor.ff590mr_lock', 'doorStatusOverall', '1') %}
              mdi:car-door
            {% else %}
              mdi:car-door
            {% endif %}
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Front Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_front_left:
        friendly_name: Anteriore Sinistra
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusfrontleft', true) }}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2',) %}
            mdi:car-door-lock
          {% else %}
            {% if not is_state_attr('sensor.ff590mr_lock', 'doorstatusfrontleft', true) %}
              mdi:car-door
            {% else %}
              mdi:car-door
            {% endif %}
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Front Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_front_right:
        friendly_name: Anteriore Destra
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusfrontright', true) }}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2',) %}
            mdi:car-door-lock
          {% else %}
            {% if not is_state_attr('sensor.ff590mr_lock', 'doorstatusfrontright', true) %}
              mdi:car-door
            {% else %}
              mdi:car-door
            {% endif %}
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Rear Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_rear_left:
        friendly_name: Posteriore Sinistra
        value_template: >-     
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusrearleft', true) }}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2',) %}
            mdi:car-door-lock
          {% else %}
            {% if not is_state_attr('sensor.ff590mr_lock', 'doorstatusrearleft', true) %}
              mdi:car-door
            {% else %}
              mdi:car-door
            {% endif %}
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Rear Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_rear_right:
        friendly_name: Posteriore Destra
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusrearright', true) }}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2',) %}
            mdi:car-door-lock
          {% else %}
            {% if not is_state_attr('sensor.ff590mr_lock', 'doorstatusrearright', true) %}
              mdi:car-door
            {% else %}
              mdi:car-door
            {% endif %}
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Decklid
  ######################################################################
  - platform: template
    sensors:
      ff590mr_decklid:
        friendly_name: Bagagliaio
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'decklidstatus', true) }}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2',) %}
            mdi:car-door-lock
          {% else %}
            {% if not is_state_attr('sensor.ff590mr_lock', 'decklidstatus', true) %}
              mdi:car-door
            {% else %}
              mdi:car-door
            {% endif %}
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Serbatoio
  ######################################################################
  #- platform: template
  #  sensors:
  #    ff590mr_fuellid:
  #      friendly_name: Serbatoio
  #      value_template: >-
  #        {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusgas', true) }}
  #      icon_template: >-
  #        {% if is_state_attr('sensor.ff590mr_lock', 'doorstatusgas', true) %}
  #          mdi:gas-station
  #        {% else %}
  #          mdi:gas-station
  #        {% endif %}
  #      device_class: opening
