######################################################################
# Mercedes Package - Customizations
######################################################################

homeassistant:
  customize:
    # Stato Generale - warningenginelight
    binary_sensor.ff590mr_engine_light_warning:
      friendly_name: Stato Generale
      device_class: problem
      icon: mdi:hazard-lights
      # warningbrakefluid, warningwashwater, warningcoolantlevellow, warninglowbattery
    
    # Freno a Mano - parkbrakestatus
    #binary_sensor.ff590mr_park_brake_status:
    #  friendly_name: Freno a mano
    #  device_class: plug
    #  icon: mdi:car-brake-parking
    #  # preWarningBrakeLiningWear

    # Freni
    binary_sensor.ff590mr_low_brake_fluid_warning:
      friendly_name: Liquido Freni
      device_class: problem
      #icon: mdi:car-brake-alert

    # Liquido Raffreddamento
    binary_sensor.ff590mr_low_coolant_level_warning:
      friendly_name: Liquido Raffreddamento
      device_class: problem
      #icon: mdi:coolant-temperature
      
    # Liquido Lavacristalli
    binary_sensor.ff590mr_low_wash_water_warning:
      friendly_name: Liquido Lavacristalli
      device_class: problem
      #icon: mdi:wiper-wash

    # Pneumatici - tirewarninglamp
    binary_sensor.ff590mr_tire_warning:
      friendly_name: Pneumatici
      device_class: problem
      #icon: mdi:car-tire-alert
      # tirepressureRearLeft, tirepressureRearRight, tirepressureFrontRight, tirepressureFrontLeft, 
      # tireMarkerFrontRight, tireMarkerFrontLeft,tireMarkerRearLeft, tireMarkerRearRight, tirewarningsrdk, tirewarningsprw

    # Finestrini
    binary_sensor.ff590mr_windows_closed:
      friendly_name: Finestrini
      device_class: opening
      icon: mdi:window-closed
      # windowstatusrearleft, windowstatusrearright, windowstatusfrontright, windowstatusfrontleft

    # Device Tracker
    device_tracker.ff590mr_device_tracker:
      friendly_name: Mercedes A200d
      entity_picture: /local/images/device-trackers/mercedes.jpg

    # Lock
    lock.ff590mr_lock:
      friendly_name: Blocco Auto 
      icon: mdi:lock
      
    # Sensore Carburante
    sensor.ff590mr_fuel_level:
      friendly_name: Livello Carburante
      icon: mdi:gas-station
      # tankLevelAdBlue
    
    # Blocco Veicolo - lock
    sensor.ff590mr_lock:
      friendly_name: Veicolo
      icon: mdi:lock-open
      # doorLockStatusOverall, doorlockstatusvehicle, doorStatusOverall,
      # doorlockstatusfrontleft,doorlockstatusfrontright, doorlockstatusrearleft, doorlockstatusrearright, doorlockstatusdecklid, doorlockstatusgas,
      # doorstatusrearleft, doorstatusfrontright, doorstatusrearright, doorstatusfrontleft, decklidstatus,
      # rooftopstatus, sunroofstatus
      
    # Odometria
    sensor.ff590mr_odometer:
      friendly_name: Km Percorsi
      icon: mdi:road-variant
      # distanceReset, distanceStart, averageSpeedReset, averageSpeedStart, distanceZEReset, 
      # drivenTimeZEReset, drivenTimeReset, drivenTimeStart, ecoscoretotal, ecoscorefreewhl, ecoscorebonusrange, ecoscoreconst, ecoscoreaccel, 
      # gasconsumptionstart, gasconsumptionreset, gasTankRange, gasTankLevel, 
      # liquidconsumptionstart, liquidconsumptionreset, liquidRangeSkipIndication, rangeliquid, serviceintervaldays, tanklevelpercent, tankReserveLamp, 
      # batteryState, tankLevelAdBlue

    # Sensore Avviamento
    sensor.ff590mr_ignition_state:
      friendly_name: Sensore Avviamento
      icon: mdi:power

    # Sensore Dati Connessione
    sensor.ff590mr_car:
      friendly_name: Sensore Auto
      icon: mdi:car-connected
      # full_update_messages_received, partital_update_messages_received, last_message_received, 
      # last_command_type, last_command_state, 
      # last_command_error_code, last_command_error_message
