######################################################################
# Mercedes Package - Sensor
######################################################################

sensor:
  ######################################################################
  # Sensor: Tire Pressure Front Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_tire_pressure_front_left:
        friendly_name: Anteriore Sinistra
        unit_of_measurement: 'kPa'
        value_template: "{{ state_attr('binary_sensor.ff590mr_tire_warning', 'tirepressureFrontLeft') }}"
        icon_template: mdi:car-tire-alert
        device_class: pressure
      
  ######################################################################
  # Sensor: Tire Pressure Front Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_tire_pressure_front_right:
        friendly_name: Anteriore Destra
        unit_of_measurement: 'kPa'
        value_template: "{{ state_attr('binary_sensor.ff590mr_tire_warning', 'tirepressureFrontRight') }}"
        icon_template: mdi:car-tire-alert
        device_class: pressure
      
  ######################################################################
  # Sensor: Tire Pressure Rear Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_tire_pressure_rear_left:
        friendly_name: Posteriore Sinistra
        unit_of_measurement: 'kPa'
        value_template: "{{ state_attr('binary_sensor.ff590mr_tire_warning', 'tirepressureRearLeft') }}"
        icon_template: mdi:car-tire-alert
        device_class: pressure

  ######################################################################
  # Sensor: Tire Pressure Rear Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_tire_pressure_rear_right:
        friendly_name: Posteriore Destra
        unit_of_measurement: 'kPa'
        value_template: "{{ state_attr('binary_sensor.ff590mr_tire_warning', 'tirepressureRearRight') }}"
        icon_template: mdi:car-tire-alert
        device_class: pressure

  ######################################################################
  # Sensor: Distance from Start
  ######################################################################
  - platform: template
    sensors:
      ff590mr_distance_since_start:
        friendly_name: Distanza dalla partenza
        unit_of_measurement: 'Km'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'distanceStart') }}"
        icon_template: mdi:road-variant

  ######################################################################
  # Sensor: Distance from Reset
  ######################################################################
  - platform: template
    sensors:
      ff590mr_distance_since_reset:
        friendly_name: Distanza dal reset
        unit_of_measurement: 'Km'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'distanceReset') }}"
        icon_template: mdi:road-variant

  ######################################################################
  # Sensor: Liquid Consumption from Start
  ######################################################################
  #- platform: template
  #  sensors:
  #    ff590mr_liquid_consumption_start:
  #      friendly_name: Consumo dalla partenza
  #      unit_of_measurement: 'l/100Km'
  #      value_template: "{{ state_attr('sensor.ff590mr_odometer', 'liquidconsumptionstart') }}"
  #      icon_template: mdi:gas-station

  ######################################################################
  # Sensor: Liquid Consumption from Reset
  ######################################################################
  - platform: template
    sensors:
      ff590mr_liquid_consumption_reset:
        friendly_name: Consumo dal reset
        unit_of_measurement: 'l/100Km'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'liquidconsumptionreset') }}"
        icon_template: mdi:gas-station

  ######################################################################
  # Sensor: Service Interval Days
  ######################################################################
  - platform: template
    sensors:
      ff590mr_service_interval_days:
        friendly_name: Prossimo Tagliando
        unit_of_measurement: 'giorni'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'serviceintervaldays') }}"
        icon_template: mdi:wrench
