######################################################################
# Mercedes Package - Binary Sensor
######################################################################

binary_sensor:
  ######################################################################
  # Binary Sensor: Doors Lock
  ######################################################################
  - platform: template
    sensors:
      ff590mr_locked:
        friendly_name: Blocco Vettura
        value_template: >-
          {% if not is_state('sensor.ff590mr_lock', '2') %}
            true
          {% else %}
            false
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.ff590mr_lock', '2') %}
            mdi:lock
          {% else %}
            mdi:lock-open
          {% endif %}
        device_class: lock

  ######################################################################
  # Binary Sensor: Doors Closed
  ######################################################################
  - platform: template
    sensors:
      ff590mr_doors_closed:
        friendly_name: Porte
        value_template: >-
          {{ (is_state_attr('binary_sensor.ff590mr_windows_closed', 'doorstatusfrontleft', 'false') and
              is_state_attr('binary_sensor.ff590mr_windows_closed', 'doorstatusfrontright', 'false') and
              is_state_attr('binary_sensor.ff590mr_windows_closed', 'doorstatusrearleft', 'false') and
              is_state_attr('binary_sensor.ff590mr_windows_closed', 'doorstatusrearright', 'false')) }}
        icon_template: mdi:car-door
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Front Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_front_left:
        friendly_name: Anteriore Sinistra
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusfrontleft', '2') }}
        icon_template: mdi:car-door
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Front Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_front_right:
        friendly_name: Anteriore Destra
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusfrontright', '2') }}
        icon_template: mdi:car-door
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Rear Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_rear_left:
        friendly_name: Posteriore Sinistra
        value_template: >-     
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusrearleft', '2') }}
        icon_template: mdi:car-door
        device_class: opening

  ######################################################################
  # Binary Sensor: Door Rear Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_door_rear_right:
        friendly_name: Posteriore Destra
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'doorstatusrearright', '2') }}
        icon_template: mdi:car-door
        device_class: opening

  ######################################################################
  # Binary Sensor: Trunk
  ######################################################################
  #- platform: template
  #  sensors:
  #    ff590mr_trunk:
  #      friendly_name: Bagagliaio
  #      value_template: >-
  #        {{ not (is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_LOCKED') or
  #                is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_UNLOCKED')) }}
  #      icon_template: >-
  #        {% if (is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_LOCKED') or 
  #               is_state_attr('sensor.ff590mr_lock', 'trunkStateRollup', 'CLOSED_AND_UNLOCKED')) %}
  #          mdi:lock
  #        {% else %}
  #          mdi:lock-open
  #        {% endif %}
  #      device_class: opening

  ######################################################################
  # Binary Sensor: Deck Lid
  ######################################################################
  - platform: template
    sensors:
      ff590mr_fuel_lid:
        friendly_name: Serbatoio
        value_template: >-
          {{ is_state_attr('sensor.ff590mr_lock', 'decklidstatus', true) }}
        icon_template: >-
          {% if is_state_attr('sensor.ff590mr_lock', 'decklidstatus', true) %}
            mdi:gas-station
          {% else %}
            mdi:gas-station
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Windows Closed
  ######################################################################
  - platform: template
    sensors:
      ff590mr_windows_closed_2:
        friendly_name: Finestrini
        value_template: >-
          {{ is_state('binary_sensor.ff590mr_windows_closed', 'true') }}
        icon_template: >-
          {% if not is_state('binary_sensor.ff590mr_windows_closed', '2') %}
            mdi:window-closed
          {% else %}
            mdi:window-open
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Window Front Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_window_front_left:
        friendly_name: Anteriore Sinistro
        value_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontleft', '2') %}
            false
          {% else %}
            true
          {% endif %}
        icon_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontleft', '2') %}
            mdi:window-closed
          {% else %}
            mdi:window-open
          {% endif %}
        device_class: opening

  ######################################################################
  # Binary Sensor: Window Front Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_window_front_right:
        friendly_name: Anteriore Destro
        value_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontright', '2') %}
            false
          {% else %}
            true
          {% endif %}
        icon_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusfrontright', '2') %}
            mdi:window-closed
          {% else %}
            mdi:window-open
          {% endif %}   
        device_class: opening

  ######################################################################
  # Binary Sensor: Window Rear Left
  ######################################################################
  - platform: template
    sensors:
      ff590mr_window_rear_left:
        friendly_name: Posteriore Sinistro
        value_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearleft', '2') %}
            false
          {% else %}
            true
          {% endif %}
        icon_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearleft', '2') %}
            mdi:window-closed
          {% else %}
            mdi:window-open
          {% endif %}   
        device_class: opening

  ######################################################################
  # Binary Sensor: Window Rear Right
  ######################################################################
  - platform: template
    sensors:
      ff590mr_window_rear_right:
        friendly_name: Posteriore Destro
        value_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearright', '2') %}
            false
          {% else %}
            true
          {% endif %}
        icon_template: >-
          {% if is_state_attr('binary_sensor.ff590mr_windows_closed', 'windowstatusrearright', '2') %}
            mdi:window-closed
          {% else %}
            mdi:window-open
          {% endif %}   
        device_class: opening
