######################################################################
# Mercedes Package - Customizations
######################################################################

homeassistant:
  customize:
    ######################################################################
    # Binary Sensors
    ######################################################################
    # Liquido Lavacristalli - warningwashwater
    binary_sensor.ff590mr_low_wash_water_warning:
      friendly_name: Liquido Lavacristalli
      device_class: problem
      #icon: mdi:wiper-wash

    # Liquido Raffreddamento - warningcoolantlevellow
    binary_sensor.ff590mr_low_coolant_level_warning:
      friendly_name: Liquido Raffreddamento
      device_class: problem
      #icon: mdi:coolant-temperature

    # Liquido Freni - warningbrakefluid
    binary_sensor.ff590mr_low_brake_fluid_warning:
      friendly_name: Liquido Freni
      device_class: problem
      #icon: mdi:car-brake-alert

    # Stato Generale - warningenginelight
    binary_sensor.ff590mr_engine_light_warning:
      friendly_name: Stato Generale
      device_class: problem
      icon: mdi:hazard-lights
      # warningbrakefluid, warningwashwater, warningcoolantlevellow, warninglowbattery

    # Freno a Mano - parkbrakestatus
    #binary_sensor.engine_light_warning:
    #  friendly_name: Freno a mano
    #  device_class: plug
    #  icon: mdi:car-brake-parking
    #  # preWarningBrakeLiningWear

    # Pneumatici - tirewarninglamp
    binary_sensor.ff590mr_tire_warning:
      friendly_name: Pneumatici
      device_class: problem
      #icon: mdi:car-tire-alert
      #tirepressureRearLeft, tirepressureRearRight, tirepressureFrontRight, tirepressureFrontLeft, tireMarkerFrontRight, tireMarkerFrontLeft,tireMarkerRearLeft, tireMarkerRearRight, tirewarningsrdk, tirewarningsprw, tireTemperatureRearLeft, tireTemperatureFrontRight,
      #tireTemperatureRearRight, tireTemperatureFrontLeft

    # Finestrini - windowsClosed
    binary_sensor.ff590mr_windows_closed:
      friendly_name: Finestrini
      device_class: opening
      icon: mdi:window-closed
      # windowstatusrearleft, windowstatusrearright, windowstatusfrontright, windowstatusfrontleft

    ######################################################################
    # Device Tracker
    ######################################################################
    device_tracker.ff590mr_device_tracker:
      friendly_name: Mercedes A200d
      entity_picture: /local/images/device-trackers/mercedes.jpg

    ######################################################################
    # Locks
    ######################################################################
    lock.ff590mr_lock:
      friendly_name: Blocco Auto
      icon: mdi:lock
    lock.ff590mr_lock_no_pin:
      friendly_name: Blocco Auto
      icon: mdi:lock

    ######################################################################
    # Sensors
    ######################################################################
    # Blocco Veicolo - lock
    sensor.ff590mr_lock:
      friendly_name: Veicolo
      icon: mdi:lock-open
      # doorLockStatusOverall, doorlockstatusvehicle, doorStatusOverall,
      # doorlockstatusfrontleft,doorlockstatusfrontright, doorlockstatusrearleft, doorlockstatusrearright, doorlockstatusdecklid, doorlockstatusgas,
      # doorstatusrearleft, doorstatusfrontright, doorstatusrearright, doorstatusfrontleft, decklidstatus,
      # rooftopstatus, sunroofstatus

    # Sensore Carburante - Fuel Level
    sensor.ff590mr_fuel_level:
      friendly_name: Livello Carburante
      icon: mdi:gas-station
      # tankLevelAdBlue

    # Violazione Geolocalizzazione - Geofencing Violation
    sensor.ff590mr_geofencing_violation:
      friendly_name: Violazione Geolocalizzazione
      icon: mdi:map-marker-radius

    # Odometria - odometer
    sensor.ff590mr_odometer:
      friendly_name: Km Percorsi
      icon: mdi:road-variant
      # distanceReset, distanceStart, averageSpeedReset, averageSpeedStart, distanceZEReset,
      # drivenTimeZEReset, drivenTimeReset, drivenTimeStart, ecoscoretotal, ecoscorefreewhl, ecoscorebonusrange, ecoscoreconst, ecoscoreaccel,
      # gasconsumptionstart, gasconsumptionreset, gasTankRange, gasTankLevel,
      # liquidconsumptionstart, liquidconsumptionreset, liquidRangeSkipIndication, rangeliquid, serviceintervaldays, tanklevelpercent, tankReserveLamp,
      # batteryState, tankLevelAdBlue
    sensor.ff590mr_distance_reset:
      friendly_name: Distanza dal reset
    sensor.ff590mr_distance_start:
      friendly_name: Distanza dalla partenza
    sensor.ff590mr_liquid_consumption_start:
      friendly_name: Consumo dalla partenza
    sensor.ff590mr_liquid_consumption_reset:
      friendly_name: Consumo dal reset

    # Sensore Avviamento
    sensor.ff590mr_ignition_state:
      friendly_name: Stato Accensione
      icon: mdi:key-wireless

    ######################################################################
    # Diagnostic Sensors
    ######################################################################
    # Sensore Dati Connessione
    sensor.ff590mr_car:
      friendly_name: Messaggi Auto
      icon: mdi:car-connected
      # full_update_messages_received, partital_update_messages_received, last_message_received,
      # last_command_type, last_command_state,
      # last_command_error_code, last_command_error_message

    # Sensore Configurazione Estesa
    sensor.ff590mr_rcp_features:
      friendly_name: Configurazione Estesa
      icon: mdi:car-cog
      # rcp_supported_settings (List of all remote configuration options, I'll implement them step by step as services or buttons)
