######################################################################
# Mercedes Package - Odometer Sensor
######################################################################

sensor:
  ######################################################################
  # Sensor: Distance from Start
  ######################################################################
  - platform: template
    sensors:
      ff590mr_distance_since_start:
        friendly_name: Distanza dalla partenza
        unit_of_measurement: 'Km'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'distanceStart') }}"
        icon_template: mdi:road-variant

  ######################################################################
  # Sensor: Distance from Reset
  ######################################################################
  - platform: template
    sensors:
      ff590mr_distance_since_reset:
        friendly_name: Distanza dal reset
        unit_of_measurement: 'Km'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'distanceReset') }}"
        icon_template: mdi:road-variant

  ######################################################################
  # Sensor: Liquid Consumption from Start
  ######################################################################
  #- platform: template
  #  sensors:
  #    ff590mr_liquid_consumption_start:
  #      friendly_name: Consumo dalla partenza
  #      unit_of_measurement: 'l/100Km'
  #      value_template: "{{ state_attr('sensor.ff590mr_odometer', 'liquidconsumptionstart') }}"
  #      icon_template: mdi:gas-station

  ######################################################################
  # Sensor: Liquid Consumption from Reset
  ######################################################################
  - platform: template
    sensors:
      ff590mr_liquid_consumption_reset:
        friendly_name: Consumo dal reset
        unit_of_measurement: 'l/100Km'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'liquidconsumptionreset') }}"
        icon_template: mdi:gas-station

  ######################################################################
  # Sensor: Service Interval Days
  ######################################################################
  - platform: template
    sensors:
      ff590mr_service_interval_days:
        friendly_name: Prossimo Tagliando
        unit_of_measurement: 'giorni'
        value_template: "{{ state_attr('sensor.ff590mr_odometer', 'serviceintervaldays') }}"
        icon_template: mdi:wrench
