######################################################################
# Netatmo Package - On/Off Engine - Input Boolean
######################################################################

input_boolean:
  valvola_zona_giorno:
    name: Valvola Zona Giorno
    initial: true
    icon: mdi:thermometer
  valvola_cucina:
    name: Valvola Cucina
    initial: true
    icon: mdi:thermometer
  valvola_sala:
    name: Valvola Sala
    initial: true
    icon: mdi:thermometer
  valvola_studio:
    name: Valvola Studio
    initial: true
    icon: mdi:thermometer
  valvola_bagno_piccolo:
    name: Valvola Bagno Piccolo
    initial: true
    icon: mdi:thermometer
  valvola_bagno_grande:
    name: Valvola Bagno Grande
    initial: true
    icon: mdi:thermometer
  valvola_camera:
    name: Valvola Camera
    initial: true
    icon: mdi:thermometer

######################################################################
# Netatmo Package - On/Off Engine - Input Number
######################################################################

# Input number for manual temperature set (in minutes)
input_number:
  netatmo_manual_temperature:
    name: "Durata impostazioni manuali"
    initial: 180
    min: 5
    max: 720
    step: 1
    mode: slider
    icon: mdi:timer-edit-outline

######################################################################
# Netatmo Package - On/Off Engine - Timer
######################################################################

timer:
  # Timer for manual set (10800 sec = 3 hour)
  valvola_zona_giorno:
    name: Valvola Zona Giorno
    duration: 10800
    icon: mdi:timer-edit-outline
  valvola_cucina:
    name: Valvola Cucina
    duration: 10800
    icon: mdi:timer-edit-outline
  valvola_sala:
    name: Valvola Sala
    duration: 10800
    icon: mdi:timer-edit-outline
  valvola_studio:
    name: Valvola Studio
    duration: 10800
    icon: mdi:timer-edit-outline
  valvola_bagno_piccolo:
    name: Valvola Bagno Piccolo
    duration: 10800
    icon: mdi:timer-edit-outline
  valvola_bagno_grande:
    name: Valvola Bagno Grande
    duration: 10800
    icon: mdi:timer-edit-outline
  valvola_camera:
    name: Valvola Camera
    duration: 10800
    icon: mdi:timer-edit-outline

######################################################################
# Netatmo Package - On/Off Engine - Automations
######################################################################

automation:

  ######################################################################
  # Switch On Valve
  ######################################################################
  - alias: "Termosifoni: Accensione"
    id: termosifoni_accensione

    trigger:
      - trigger: state
        entity_id:
          - input_boolean.valvola_zona_giorno
          - input_boolean.valvola_cucina
          - input_boolean.valvola_sala
          - input_boolean.valvola_studio
          - input_boolean.valvola_bagno_piccolo
          - input_boolean.valvola_bagno_grande
          - input_boolean.valvola_camera
        to: "on"

    action:
      - action: climate.turn_on
        data:
          entity_id: >
            {{ (state_attr('sensor.netatmo_valve_map', 'boolean_to_climate') | from_json)[trigger.entity_id] }}

      - action: timer.cancel
        data:
          entity_id: >
            {{ (state_attr('sensor.netatmo_valve_map', 'boolean_to_timer') | from_json)[trigger.entity_id] }}


  ######################################################################
  # Switch Off Valve
  ######################################################################
  - alias: "Termosifoni: Spegnimento"
    id: termosifoni_spegnimento

    triggers:
      - trigger: state
        entity_id:
          - input_boolean.valvola_zona_giorno
          - input_boolean.valvola_cucina
          - input_boolean.valvola_sala
          - input_boolean.valvola_studio
          - input_boolean.valvola_bagno_piccolo
          - input_boolean.valvola_bagno_grande
          - input_boolean.valvola_camera
        to: "off"

    actions:
      - action: climate.turn_off
        data:
          entity_id: >
            {{ (state_attr('sensor.netatmo_valve_map', 'boolean_to_climate') | from_json)[trigger.entity_id] }}

      - action: timer.start
        data:
          entity_id: >
            {{ (state_attr('sensor.netatmo_valve_map', 'boolean_to_timer') | from_json)[trigger.entity_id] }}
          duration: "{{ states('input_number.netatmo_manual_temperature') | int * 60 }}"

  ######################################################################
  # Automation triggered after manual temperature set timeout elapsed
  ######################################################################
  - alias: "Termosifoni: Scadenza timeout impostazione manuale"
    id: termosifoni_scadenza_timeout_impostazione_manuale
    mode: parallel

    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id:
            - timer.valvola_zona_giorno
            - timer.valvola_cucina
            - timer.valvola_sala
            - timer.valvola_studio
            - timer.valvola_bagno_piccolo
            - timer.valvola_bagno_grande
            - timer.valvola_camera

    actions:
      - action: input_boolean.turn_on
        data:
          entity_id: >
            {{ (state_attr('sensor.netatmo_valve_map', 'timer_to_boolean') | from_json)[trigger.event.data.entity_id] }}

      - action: script.notify_all
        data:
          title: "Home Assistant - Termosifoni"
          message: >
            Il termosifone {{
              trigger.event.data.entity_id
              | replace('timer.valvola_', '')
              | replace('_', ' ')
            }} si è riacceso
          destination: all
