######################################################################
# Netatmo Package - Boost Engine Script
######################################################################

input_boolean:
  boost_valvola_zona_giorno:
    name: Boost Valvola Zona Giorno
    icon: mdi:thermometer-plus
  boost_valvola_cucina:
    name: Boost Valvola Cucina
    icon: mdi:thermometer-plus
  boost_valvola_sala:
    name: Boost Valvola Sala
    icon: mdi:thermometer-plus
  boost_valvola_studio:
    name: Boost Valvola Studio
    icon: mdi:thermometer-plus
  boost_valvola_bagno_piccolo:
    name: Boost Valvola Bagno Piccolo
    icon: mdi:thermometer-plus
  boost_valvola_bagno_grande:
    name: Boost Valvola Bagno Grande
    icon: mdi:thermometer-plus
  boost_valvola_camera:
    name: Boost Valvola Camera
    icon: mdi:thermometer-plus

######################################################################
# Netatmo Package - Boost Engine Automations
######################################################################

automation:
  ######################################################################
  # Automation: Start Boost
  ######################################################################
  - alias: "Termosifoni: Attivazione Boost"
    id: termosifoni_attivazione_boost
    mode: parallel

    trigger:
      - trigger: state
        entity_id:
          - input_boolean.boost_valvola_zona_giorno
          - input_boolean.boost_valvola_cucina
          - input_boolean.boost_valvola_sala
          - input_boolean.boost_valvola_studio
          - input_boolean.boost_valvola_bagno_piccolo
          - input_boolean.boost_valvola_bagno_grande
          - input_boolean.boost_valvola_camera
        to: "on"

    variables:
      climate_entity: >
        {{
          (state_attr('sensor.netatmo_valve_map', 'boost_boolean_to_climate')
          | default('{}') | from_json)[trigger.entity_id]
        }}

    action:
      #- action: climate.set_preset_mode
      #  data_template:
      #    entity_id: "{{ entity_id }}"
      #    preset_mode: boost
      - action: climate.set_temperature
        data_template:
          entity_id: "{{ climate_entity }}"
          temperature: 30
      - delay: "00:05:00"
      - action: climate.turn_on
        data_template:
          entity_id: "{{ climate_entity }}"
      - action: input_boolean.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"

  ######################################################################
  # Automation: Stop Boost
  ######################################################################
  - alias: "Termosifoni: Disattivazione Boost"
    id: termosifoni_disattivazione_boost
    mode: parallel

    trigger:
      - trigger: state
        entity_id:
          - input_boolean.boost_valvola_zona_giorno
          - input_boolean.boost_valvola_cucina
          - input_boolean.boost_valvola_sala
          - input_boolean.boost_valvola_studio
          - input_boolean.boost_valvola_bagno_piccolo
          - input_boolean.boost_valvola_bagno_grande
          - input_boolean.boost_valvola_camera
        to: "off"

      - trigger: homeassistant
        event: start

    variables:
      climate_entity: >
        {{
          (state_attr('sensor.netatmo_valve_map', 'boost_boolean_to_climate')
          | default('{}') | from_json)[trigger.entity_id]
          if trigger.entity_id is not none else none
        }}

    action:
      # home assistant start
      - choose:
          - conditions: "{{ trigger.platform == 'homeassistant' }}"
            sequence:
              - action: input_boolean.turn_off
                target:
                  entity_id:
                    - input_boolean.boost_valvola_zona_giorno
                    - input_boolean.boost_valvola_cucina
                    - input_boolean.boost_valvola_sala
                    - input_boolean.boost_valvola_studio
                    - input_boolean.boost_valvola_bagno_piccolo
                    - input_boolean.boost_valvola_bagno_grande
                    - input_boolean.boost_valvola_camera
        default:
          - action: climate.turn_on
            data_template:
              entity_id: "{{ climate_entity }}"
          - action: input_boolean.turn_off
            data_template:
              entity_id: "{{ trigger.entity_id }}"
 
