######################################################################
# Netamo Package - Main
######################################################################

homeassistant:
  customize:

    ######################################################################
    # Netamo Package - Main - General Package Settings
    ######################################################################

    package.netatmo:
      customize: &customize
        package: 'netatmo'
        version: 1.3.0

    ######################################################################
    # Netatmo Package - Main - Entities
    ######################################################################

    group.climate:
      <<: *customize
    sensor.valvola_zona_giorno_temperature:
      <<: *customize
    sensor.valvola_cucina_temperature:
      <<: *customize
    sensor.valvola_sala_temperature:
      <<: *customize
    sensor.valvola_studio_temperature:
      <<: *customize
    sensor.valvola_bagno_piccolo_temperature:
      <<: *customize
    sensor.valvola_bagno_grande_temperature:
      <<: *customize
    sensor.valvola_camera_temperature:
      <<: *customize
    sensor.valvola_zona_giorno_state:
      <<: *customize
    sensor.valvola_cucina_state:
      <<: *customize
    sensor.valvola_sala_state:
      <<: *customize
    sensor.valvola_studio_state:
      <<: *customize
    sensor.valvola_bagno_piccolo_state:
      <<: *customize
    sensor.valvola_bagno_grande_state:
      <<: *customize
    sensor.valvola_camera_state:
      <<: *customize
    input_boolean.valvola_zona_giorno:
      <<: *customize
    input_boolean.valvola_cucina:
      <<: *customize
    input_boolean.valvola_sala:
      <<: *customize
    input_boolean.valvola_studio:
      <<: *customize
    input_boolean.valvola_bagno_piccolo:
      <<: *customize
    input_boolean.valvola_bagno_grande:
      <<: *customize
    input_boolean.valvola_camera:
      <<: *customize
    automation.termosifoni_accensione:
      <<: *customize
    automation.termosifoni_spegnimento:
      <<: *customize
    automation.termosifoni_scadenza_timeout_impostazione_manuale:
      <<: *customize
    input_boolean.boost_valvola_zona_giorno:
      <<: *customize
    input_boolean.boost_valvola_cucina:
      <<: *customize
    input_boolean.boost_valvola_sala:
      <<: *customize
    input_boolean.boost_valvola_studio:
      <<: *customize
    input_boolean.boost_valvola_bagno_grande:
      <<: *customize
    input_boolean.boost_valvola_bagno_piccolo:
      <<: *customize
    input_boolean.boost_valvola_camera:
      <<: *customize
    input_number.netatmo_manual_temperature:
      <<: *customize
    timer.valvola_zona_giorno:
      <<: *customize
    timer.valvola_cucina:
      <<: *customize
    timer.valvola_sala:
      <<: *customize
    timer.valvola_studio:
      <<: *customize
    timer.valvola_bagno_piccolo:
      <<: *customize
    timer.valvola_bagno_grande:
      <<: *customize
    timer.valvola_camera:
      <<: *customize
    automation.termosifoni_attivazione_boost:
      <<: *customize
    automation.termosifoni_disattivazione_boost:
      <<: *customize
    script.climate_away_mode_on:
      <<: *customize
    script.climate_away_mode_off:
      <<: *customize
    automation.termosifoni_sincronizzazione_con_riscaldamento_centralizzato:
      <<: *customize
    automation.netatmo_notifica_disconnessione:
      <<: *customize
