######################################################################
# Netatmo Package - Away Mode Scripts
######################################################################

script:
  ######################################################################
  # Away Mode On
  ######################################################################
  climate_away_mode_on:
    sequence:
      - service: climate.set_preset_mode
        data:
          entity_id:
            - climate.cucina
            - climate.sala
            - climate.studio
            - climate.bagno
            - climate.camera
          preset_mode: away

  ######################################################################
  # Away Mode Off
  ######################################################################
  climate_away_mode_off:
    sequence:
      - service: climate.set_hvac_mode
        data:
          entity_id:
            - climate.cucina
            - climate.sala
            - climate.studio
            - climate.bagno
            - climate.camera
          hvac_mode: auto

######################################################################
# Netatmo Package - Away Mode Automations
######################################################################

automation:
  ######################################################################
  # Sync with central heating
  ######################################################################
  - alias: "Termosifoni: Sincronizzazione con Riscaldamento Centralizzato"

    trigger:
      - platform: state
        entity_id: input_boolean.central_heating
        to: 'on'
      - platform: state
        entity_id: input_boolean.central_heating
        to: 'off'

    condition: []

    action:
      - choose:
          # Switch On
          - conditions:
              - condition: state
                entity_id: input_boolean.central_heating
                state: "off"
            sequence:
              - service: script.turn_on
                data:
                  entity_id: script.climate_away_mode_on
          # Switch Off
          - conditions:
              - condition: and
                conditions:
                    - condition: state
                      entity_id: input_boolean.central_heating
                      state: "on"
                    - condition: state
                      entity_id: input_boolean.home_mode_away
                      state: 'off'
            sequence:
              - service: script.turn_on
                data:
                  entity_id: script.climate_away_mode_off
