######################################################################
# Netatmo Package - Operations - Automations
######################################################################

automation:
  # Notification when a device becomes unavailable
  - alias: "Netatmo: Notifica disconnessione"
    id: "netatmo_notifica_disconnessione"

    variables:
      disconnected_devices_list: >
        {{ expand('group.climate')
          | selectattr('state','eq','unavailable')
          | map(attribute='entity_id')
          | list
        }}

    trigger:
      - trigger: state
        entity_id: climate.zona_giorno
        to: 'unavailable'
      - trigger: state
        entity_id: climate.cucina
        to: 'unavailable'
      - trigger: state
        entity_id: climate.sala
        to: 'unavailable'
      - trigger: state
        entity_id: climate.studio
        to: 'unavailable'
      - trigger: state
        entity_id: climate.bagno_piccolo
        to: 'unavailable'
      - trigger: state
        entity_id: climate.bagno_grande
        to: 'unavailable'
      - trigger: state
        entity_id: climate.camera
        to: 'unavailable'

    action:
      - action: script.notify_text
        data_template:
          title: "Netatmo - Dispositivi disconnessi"
          message: >
            Ci sono {{disconnected_devices_list | count }} dispositivi disconnessi:
            {% for entity_id in disconnected_devices_list %}
                -> {{ state_attr(entity_id, 'friendly_name')}}
            {%- endfor -%}
          notification_id: "update"
          enable_persistent: true
