######################################################################
# Netatmo Package - On/Off Engine - Input Boolean
######################################################################

input_boolean:
  valvola_cucina:
    name: Valvola Cucina
    initial: on
    icon: mdi:thermometer
  valvola_sala:
    name: Valvola Sala
    initial: on
    icon: mdi:thermometer
  valvola_studio:
    name: Valvola Studio
    initial: on
    icon: mdi:thermometer
  valvola_bagno:
    name: Valvola Bagno
    initial: on
    icon: mdi:thermometer
  valvola_camera:
    name: Valvola Camera
    initial: on
    icon: mdi:thermometer

######################################################################
# Netatmo Package - On/Off Engine - Automations
######################################################################

automation:
  ######################################################################
  # Switch On Valve
  ######################################################################
  - alias: "Termosifoni: Accensione"
    id: "termosifoni_accensione"

    trigger:
      platform: state
      entity_id: input_boolean.valvola_cucina,
                 input_boolean.valvola_sala,
                 input_boolean.valvola_studio,
                 input_boolean.valvola_bagno,
                 input_boolean.valvola_camera
      to: 'on'

    action:
      - service: climate.turn_on
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_boolean.valvola_cucina' %}
              climate.cucina
            {% elif trigger.entity_id == 'input_boolean.valvola_sala' %}
              climate.sala
            {% elif trigger.entity_id == 'input_boolean.valvola_studio' %}
              climate.studio
            {% elif trigger.entity_id == 'input_boolean.valvola_bagno' %}
              climate.bagno
            {% elif trigger.entity_id == 'input_boolean.valvola_camera' %}
              climate.camera
            {% endif %}

  ######################################################################
  # Switch Off Valve
  ######################################################################
  - alias: "Termosifoni: Spegnimento"
    id: "termosifoni_spegnimento"

    trigger:
      platform: state
      entity_id: input_boolean.valvola_cucina,
                 input_boolean.valvola_sala,
                 input_boolean.valvola_studio,
                 input_boolean.valvola_bagno,
                 input_boolean.valvola_camera
      to: 'off'

    action:
      - service: climate.turn_off
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_boolean.valvola_cucina' %}
              climate.cucina
            {% elif trigger.entity_id == 'input_boolean.valvola_sala' %}
              climate.sala
            {% elif trigger.entity_id == 'input_boolean.valvola_studio' %}
              climate.studio
            {% elif trigger.entity_id == 'input_boolean.valvola_bagno' %}
              climate.bagno
            {% elif trigger.entity_id == 'input_boolean.valvola_camera' %}
              climate.camera
            {% endif %}
