######################################################################
# Netatmo Package - On/Off Engine - Input Boolean
######################################################################

input_boolean:
  valvola_zona_giorno:
    name: Valvola Zona Giorno
    initial: on
    icon: mdi:thermometer
  valvola_cucina:
    name: Valvola Cucina
    initial: on
    icon: mdi:thermometer
  valvola_sala:
    name: Valvola Sala
    initial: on
    icon: mdi:thermometer
  valvola_studio:
    name: Valvola Studio
    initial: on
    icon: mdi:thermometer
  valvola_bagno_piccolo:
    name: Valvola Bagno Piccolo
    initial: on
    icon: mdi:thermometer
  valvola_bagno_grande:
    name: Valvola Bagno Grande
    initial: on
    icon: mdi:thermometer
  valvola_camera:
    name: Valvola Camera
    initial: on
    icon: mdi:thermometer

######################################################################
# Netatmo Package - On/Off Engine - Automations
######################################################################

automation:
  ######################################################################
  # Switch On Valve
  ######################################################################
  - alias: "Termosifoni: Accensione"
    id: "termosifoni_accensione"

    trigger:
      trigger: state
      entity_id: input_boolean.valvola_zona_giorno,
                 input_boolean.valvola_cucina,
                 input_boolean.valvola_sala,
                 input_boolean.valvola_studio,
                 input_boolean.valvola_bagno_piccolo,
                 input_boolean.valvola_bagno_grande,
                 input_boolean.valvola_camera
      to: 'on'

    action:
      - action: climate.turn_on
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_boolean.valvola_zona_giorno' %}
              climate.zona_giorno
            {% elif trigger.entity_id == 'input_boolean.valvola_cucina' %}
              climate.cucina
            {% elif trigger.entity_id == 'input_boolean.valvola_sala' %}
              climate.sala
            {% elif trigger.entity_id == 'input_boolean.valvola_studio' %}
              climate.studio
            {% elif trigger.entity_id == 'input_boolean.valvola_bagno_piccolo' %}
              climate.bagno_piccolo
            {% elif trigger.entity_id == 'input_boolean.valvola_bagno_grande' %}
              climate.bagno_grande
            {% elif trigger.entity_id == 'input_boolean.valvola_camera' %}
              climate.camera
            {% endif %}

  ######################################################################
  # Switch Off Valve
  ######################################################################
  - alias: "Termosifoni: Spegnimento"
    id: "termosifoni_spegnimento"

    trigger:
      trigger: state
      entity_id: input_boolean.valvola_zona_giorno,
                 input_boolean.valvola_cucina,
                 input_boolean.valvola_sala,
                 input_boolean.valvola_studio,
                 input_boolean.valvola_bagno_piccolo,
                 input_boolean.valvola_bagno_grande,
                 input_boolean.valvola_camera
      to: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_boolean.valvola_zona_giorno' %}
              climate.zona_giorno
            {% elif trigger.entity_id == 'input_boolean.valvola_cucina' %}
              climate.cucina
            {% elif trigger.entity_id == 'input_boolean.valvola_sala' %}
              climate.sala
            {% elif trigger.entity_id == 'input_boolean.valvola_studio' %}
              climate.studio
            {% elif trigger.entity_id == 'input_boolean.valvola_bagno_piccolo' %}
              climate.bagno_piccolo
            {% elif trigger.entity_id == 'input_boolean.valvola_bagno_grande' %}
              climate.bagno_grande
            {% elif trigger.entity_id == 'input_boolean.valvola_camera' %}
              climate.camera
            {% endif %}
