######################################################################
# Netatmo Package - Script
######################################################################

script:
  ######################################################################
  # Activating Valve Boost
  ######################################################################
  climate_valve_boost:
    alias: "Valvole: Boost"
    sequence:
      - service: climate.set_preset_mode
        data_template:
          entity_id: "{{ entity_id }}"
          preset_mode: boost
      - delay: 300
      - service: climate.set_hvac_mode
        data_template:
          entity_id: "{{ entity_id }}"
          hvac_mode: auto

  ######################################################################
  # Away Mode On
  ######################################################################
  climate_away_mode_on:
    sequence:
      - service: climate.set_preset_mode
        data:
          entity_id: 
            - climate.netatmo_cucina
            - climate.netatmo_sala
            - climate.netatmo_studio
            - climate.netatmo_bagno
            - climate.netatmo_camera_da_letto
          preset_mode: away

  ######################################################################
  # Away Mode Off
  ######################################################################
  climate_away_mode_off:
    sequence:
      - service: climate.set_hvac_mode
        data:
          entity_id: 
            - climate.netatmo_cucina
            - climate.netatmo_sala
            - climate.netatmo_studio
            - climate.netatmo_bagno
            - climate.netatmo_camera_da_letto
          hvac_mode: auto

######################################################################
# Netatmo Package - Automations
######################################################################

automation:

  ######################################################################
  # Sync with central heating
  ######################################################################
  - alias: "Termosifoni: Sincronizzazione con Riscaldamento Centralizzato"

    trigger:
      - platform: state
        entity_id: input_boolean.central_heating
        to: 'on'
      - platform: state
        entity_id: input_boolean.central_heating
        to: 'off'

    condition: []

    action:
      - choose:
        # Switch On
        - conditions:
          - condition: state
            entity_id: input_boolean.central_heating
            state: "off"
          sequence:
            - service: script.turn_on
              data:
                entity_id: script.climate_away_mode_on
        # Switch Off
        - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.central_heating
                state: "on"
              - condition: state
                entity_id: input_boolean.home_mode_away
                state: 'off'
          sequence:
            - service: script.turn_on
              data:
                entity_id: script.climate_away_mode_off
