######################################################################
# BTcino Classe 300eos with Netatmo Package - Customizations
######################################################################

homeassistant:
  customize:

    ######################################################################
    # BTcino Classe 300eos with Netatmo Package - Customizations - General Package Settings
    ######################################################################

    package.bticino_300eos:
      customize: &customize
        package: 'bticino_300eos'
        version: 1.0.0

    ######################################################################
    # BTcino Classe 300eos with Netatmo Package - Customizations - Entities
    ######################################################################

    input_boolean.portone:
      <<: *customize
    switch.portone:
      <<: *customize

######################################################################
# BTcino Classe 300eos with Netatmo - Input boolean
######################################################################

input_boolean:
  portone:
    name: "Portone"
    initial: false
    icon: mdi:door

######################################################################
# BTcino Classe 300eos with Netatmo Package - Switch
######################################################################

switch:
  - platform: template
    switches:
      portone:
        value_template: "{{ is_state('input_boolean.portone', 'on') }}"
        icon_template: mdi:door
        turn_on:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.portone
          - delay: 1
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.portone
        turn_off:
          action: input_boolean.turn_off
          target:
            entity_id: input_boolean.portone

######################################################################
# BTcino Classe 300eos with Netatmo Package - Lock
######################################################################

#lock:
#  - platform: template
#    name: Portone
#    value_template: "{{ is_state('input_boolean.portone', 'off') }}"
#    lock:
#      action: input_boolean.turn_off
#      target:
#        entity_id: input_boolean.portone
#    unlock:
#      - action: input_boolean.turn_on
#        target:
#          entity_id: input_boolean.portone
#      - delay: 1
#      - action: input_boolean.turn_off
#        target:
#          entity_id: input_boolean.portone

######################################################################
# BTcino Classe 300eos with Netatmo Package - Google Assistant
######################################################################

google_assistant:
  entity_config:
    switch.portone:
      name: Portone
      expose: true
      room: Condominio

######################################################################
# BTcino Classe 300eos with Netatmo Package - Amazon Alexa
######################################################################

alexa:
  smart_home:
    filter:
      include_entities:
        - switch.portone
    entity_config:
      switch.portone:
        name: "Routine Portone"
        description: "Routine per l'apertura del portone condominiale"

######################################################################
# BTcino Classe 300eos with Netatmo Package - Logbook
######################################################################

#logbook:
#  exclude:
#    entities:
#      - lock.portone

######################################################################
# BTcino Classe 300eos with Netatmo Package - Recorder
######################################################################

#recorder:
#  exclude:
#    entities:
#      - lock.portone
