######################################################################
# BTicino Package - Customization
######################################################################

homeassistant:
  customize:

    # BTI-NT4411C - Dimmer 0x0004740001583a4a
    #light.0x0004740001583a4a:
    #  supported_color_modes: null
    #  supported_features: 0
    switch.0x0004740001583a4a_device_mode:
      friendly_name: "Funzione Dimmer"
    switch.0x0004740001583a4a_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x0004740001583a4a_led_in_dark:
      friendly_name: "LED se spento"
    number.0x0004740001583a4a_ballast_maximum_level:
      friendly_name: "Illuminazione massima"
    number.0x0004740001583a4a_ballast_minimum_level:
      friendly_name: "Illuminazione minima"

    # BTI-4411C - Dimmer 0x0004740000254d99
    #light.0x0004740000254d99:
    #  supported_color_modes: null
    #  supported_features: 0
    switch.0x0004740000254d99_device_mode:
      friendly_name: "Funzione Dimmer"
    switch.0x0004740000254d99_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x0004740000254d99_led_in_dark:
      friendly_name: "LED se spento"
    number.0x0004740000254d99_ballast_maximum_level:
      friendly_name: "Illuminazione massima"
    number.0x0004740000254d99_ballast_minimum_level:
      friendly_name: "Illuminazione minima"

    # BTI-NT4027C - Tapparella 0x000474000159053e
    cover.0x000474000159053e:
      supported_features: 15
    switch.0x000474000159053e_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x000474000159053e_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella 0x00047400015a3e19
    cover.0x00047400015a3e19:
      supported_features: 15
    switch.0x00047400015a3e19_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x00047400015a3e19_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella 0x00047400015ada4b
    cover.0x00047400015ada4b:
      supported_features: 15
    switch.0x00047400015ada4b_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x00047400015ada4b_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella 0x00047400015adb10
    cover.0x00047400015adb10:
      supported_features: 15
    switch.0x00047400015adb10_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x00047400015adb10_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella 0x00047400015ada3d
    cover.0x00047400015ada3d:
      supported_features: 15
    switch.0x00047400015ada3d_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x00047400015ada3d_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella 0x00047400015ada3f
    cover.0x00047400015ada3f:
      supported_features: 15
    switch.0x00047400015ada3f_led_if_on:
      friendly_name: "LED se acceso"
    switch.0x00047400015ada3f_led_in_dark:
      friendly_name: "LED se spento"
