######################################################################
# BTcino Customizations
######################################################################

homeassistant:
  customize:

    ######################################################################
    # BTcino Customizations - General Package Settings
    ######################################################################

    package.bticino:
      customize: &customize
        package: 'bticino'
        version: 0.0.5

    ######################################################################
    # BTcino Customizations - Entities
    ######################################################################

    group.bticino:
      <<: *customize
    script.bticino_update:
      <<: *customize
      icon: mdi:package-up
    automation.bticino_update_notification:
      <<: *customize
