######################################################################
# BTicino Package - Customization
######################################################################

homeassistant:
  customize:
    # BTI-NT4027C - Tapparella Cucina Grande (0x00047400015ada4b)
    cover.tapparella_cucina_grande:
      supported_features: 15
    switch.tapparella_cucina_grande_led_if_on:
      friendly_name: "LED se acceso"
    switch.tapparella_cucina_grande_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella Tapparella Cucina Piccola (0x00047400015adb10)
    cover.tapparella_cucina_piccola:
      supported_features: 15
    switch.tapparella_cucina_piccola_led_if_on:
      friendly_name: "LED se acceso"
    switch.tapparella_cucina_piccola_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella Sala (0x00047400015ada3d)
    cover.tapparella_sala:
      supported_features: 15
    switch.tapparella_sala_led_if_on:
      friendly_name: "LED se acceso"
    switch.tapparella_sala_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella Studio (0x00047400015a3e19)
    cover.tapparella_studio:
      supported_features: 15
    switch.tapparella_studio_led_if_on:
      friendly_name: "LED se acceso"
    switch.tapparella_studio_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-N4027C - Tenda Bagno (0x0004740001729a60)
    cover.tenda_bagno:
      supported_features: 15
    switch.tenda_bagno_led_if_on:
      friendly_name: "LED se acceso"
    switch.tenda_bagno_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella Bagno (0x000474000159053e)
    cover.tapparella_bagno:
      supported_features: 15
    switch.tapparella_bagno_led_if_on:
      friendly_name: "LED se acceso"
    switch.tapparella_bagno_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-NT4027C - Tapparella Camera (0x00047400015ada3f)
    cover.tapparella_camera:
      supported_features: 15
    switch.tapparella_camera_led_if_on:
      friendly_name: "LED se acceso"
    switch.tapparella_camera_led_in_dark:
      friendly_name: "LED se spento"

    # BTI-4411C - Luce Sala (0x00047400002bd3ad)
    #light.luce_sala:
    #  supported_color_modes: null
    #  supported_features: 0
    switch.luce_sala_device_mode:
      friendly_name: "Funzione Dimmer"
    switch.luce_sala_led_if_on:
      friendly_name: "LED se acceso"
    switch.luce_sala_led_in_dark:
      friendly_name: "LED se spento"
    number.luce_sala_ballast_maximum_level:
      friendly_name: "Illuminazione massima"
    number.luce_sala_ballast_minimum_level:
      friendly_name: "Illuminazione minima"

    # BTI-4411C - Luce Camera (0x0004740000292ec9)
    #light.luce_camera:
    #  supported_color_modes: null
    #  supported_features: 0
    switch.luce_camera_device_mode:
      friendly_name: "Funzione Dimmer"
    switch.luce_camera_led_if_on:
      friendly_name: "LED se acceso"
    switch.luce_camera_led_in_dark:
      friendly_name: "LED se spento"
    number.luce_camera_ballast_maximum_level:
      friendly_name: "Illuminazione massima"
    number.luce_camera_ballast_minimum_level:
      friendly_name: "Illuminazione minima"
