######################################################################
# Electrolux Package - Main
######################################################################

homeassistant:
  customize:

    ######################################################################
    # Electrolux Package - Main - General Package Settings
    ######################################################################

    package.netatmo:
      customize: &customize
        package: 'electrolux'
        version: 1.1.0
