######################################################################
# Electrolux Package - Customization
######################################################################

homeassistant:
  customize:
    binary_sensor.electrolux_forno_apl_status:
      friendly_name: "Stato Forno"
    binary_sensor.electrolux_forno_ov1_doorstate:
      friendly_name: "Porta Forno"
    button.electrolux_forno_ov1_executecommand_0:
      friendly_name: "Spegni Forno"
    button.electrolux_forno_ov1_executecommand_1:
      friendly_name: "Accendi Forno"
    button.electrolux_forno_ov1_executecommand_2:
      friendly_name: "Avvia Cottura"
    button.electrolux_forno_ov1_executecommand_3:
      friendly_name: "Ferma Cottura"
    button.electrolux_forno_ov1_executecommand_5:
      friendly_name: "Riprendi Cottura"
    sensor.electrolux_forno_niu_linkqualityindicator:
      friendly_name: "Potenza Segnale WiFi"
    sensor.electrolux_forno_niu_ssid:
      friendly_name: "SSI WiFi"
    sensor.electrolux_forno_ov1_appliancestate:
      friendly_name: "Stato Forno"
    sensor.electrolux_forno_ov1_displayfoodprobetemperature:
      friendly_name: "Temperatura Cibo"
    sensor.electrolux_forno_ov1_displaytemperature:
      friendly_name: "Temperatura Forno"
    sensor.electrolux_forno_ov1_remotecontrol:
      friendly_name: "Controllo Remoto"
    sensor.electrolux_forno_ov1_runningtime:
      friendly_name: "Tempo Totale di Funzionamento"
    sensor.electrolux_forno_ov1_starttime:
      friendly_name: "Avvio Cottura"
    sensor.electrolux_forno_ov1_targetmicrowavepower:
      friendly_name: "Temperatura Desiderata"
    sensor.electrolux_forno_ov1_targettemperature:
      friendly_name: "Temperatura Desiderata"
    sensor.electrolux_forno_ov1_timetoend:
      friendly_name: "Tempo Cottura Rimanenete"
    sensor.electrolux_forno_ov1_ovenprocessidentifier:
      friendly_name: "Tipologia di Cottura"
