######################################################################
# Global Light
######################################################################

- platform: group
  name: "Luci Casa"
  entities:
    - light.luce_corridoio
    - light.luce_cucina
    - light.luce_divano
    - light.luce_bagno
    - light.luce_specchio
    - light.luce_studio
    - light.luce_camera
