######################################################################
# Badroom Light
######################################################################

- platform: mqtt
  name: Luce Camera
  command_topic: "shellies/shelly1-24D1A8/relay/0/command"
  state_topic: "shellies/shelly1-24D1A8/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false
  qos: 0
  optimistic: false
