######################################################################
# Living Room Global
######################################################################

- platform: template
  lights:
    luci_sala:
      friendly_name: "Luci Sala"
      turn_on:
        service: light.turn_on
        entity_id: "light.luce_sala, light.luce_divano"
      turn_off:
        service: light.turn_off
        entity_id: "light.luce_sala, light.luce_divano"
      value_template: >-
        {% if is_state('light.luce_sala', 'on') or is_state('light.luce_divano', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      icon_template: mdi:lightbulb
