######################################################################
# Living Room Light
######################################################################

- platform: mqtt
  name: Luce Sala
  command_topic: "shellies/shelly1-C426F9/relay/0/command"
  state_topic: "shellies/shelly1-C426F9/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false
  qos: 0
  optimistic: false

######################################################################
# Living Room Couch Light (Color)
######################################################################

- platform: mqtt
  name: Luce Divano
  schema: template
  command_topic: "shellies/shellybulb-BC8610/color/0/set"
  state_topic: "shellies/shellybulb-BC8610/color/0/status"
  command_on_template: >
    {
      "turn": "on",
      "mode": "color",
      {%- if red is defined and green is defined and blue is defined -%}
        "red": {{ red }},
        "green": {{ green }},
        "blue": {{ blue }},
      {%- endif -%}
      {%- if white_value is defined -%}
        "white": {{ white_value }},
      {%- endif -%}
      {%- if brightness is defined -%}
        "gain": {{ (brightness/255*100) | int }},
      {%- endif -%}
      {%- if effect is defined -%}
        {%- if effect == 'Pioggia di Meteore' -%}
          "effect": 1
        {%- elif effect == 'Cambio Graduale' -%}
          "effect": 2
        {%- elif effect == 'Respiro' -%}
          "effect": 3
        {%- elif effect == 'Flash' -%}
          "effect": 4
        {%- elif effect == 'On/Off Graduale' -%}
          "effect": 5
        {%- elif effect == 'Rosso/Verde' -%}
          "effect": 6
        {%- else -%}
          "effect": 0
        {%- endif -%}
      {%- else -%}
        "effect": 0
      {%- endif -%}
    }
  command_off_template: >
    {
      "turn": "off",
      "mode": "color"
    }  
  state_template: >
    {% if value_json.ison == true and value_json.mode == "color" %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: '{{ (value_json.gain/100*255) | int }}'
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'    
  effect_template: >
    {%- if value_json.effect == 1 -%}
      Pioggia di Meteore
    {%- elif value_json.effect == 2 -%}
      Cambio Graduale
    {%- elif value_json.effect == 3 -%}
      Respiro
    {%- elif value_json.effect == 4 -%}
      Flash
    {%- elif value_json.effect == 5 -%}
      On/Off Graduale
    {%- elif value_json.effect == 6 -%}
      Rosso/Verde
    {%- else -%}
      Off
    {%- endif -%}
  effect_list:
    - "Off"
    - Pioggia di Meteore
    - Cambio Graduale
    - Respiro
    - Flash
    - On/Off Graduale
    - Rosso/Verde
  retain: false
  qos: 0
  optimistic: false

######################################################################
# Living Room Couch Light (White)
######################################################################

#- platform: mqtt
#  name: Luce Divano Bianca
#  schema: template
#  command_topic: "shellies/shellybulb-BC8610/color/0/set"
#  state_topic: "shellies/shellybulb-BC8610/color/0/status"
#  command_on_template: >
#    {
#      "turn": "on",
#      "mode": "white",
#      {%- if color_temp is defined -%}
#        "temp": {{ (1000000/(((float(color_temp)-153)/354*180)+153)-35) | int }},
#      {%- endif -%}
#      {%- if brightness is defined -%}
#        "brightness": {{ (brightness/255*100) | int }},
#      {%- endif -%}
#      "effect": 0
#    }
#  command_off_template: >
#    {
#      "turn": "off",
#      "mode": "white",
#      "effect": 0
#    }  
#  state_template: >
#    {% if value_json.ison == true and value_json.mode == "white" %}
#      on
#    {% else %}
#      off
#    {% endif %}
#  brightness_template: '{{ (value_json.brightness/100*255)|int }}'
#  color_temp_template: "{{ (1000000/(((float(value_json.temp)-3000)/3500*4500)+2000)) | int }}"
#  retain: false
#  qos: 0
#  optimistic: false

######################################################################
# Living Room Global
######################################################################

- platform: template
  lights:
    luci_sala:
      friendly_name: "Luci Sala"
      turn_on:
        service: light.turn_on
        entity_id: "light.luce_sala, light.luce_divano"
      turn_off:
        service: light.turn_off
        entity_id: "light.luce_sala, light.luce_divano"
      value_template: >-
        {% if is_state('light.luce_sala', 'on') or is_state('light.luce_divano', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      icon_template: mdi:lightbulb
