######################################################################
# Studio Light
######################################################################

- platform: mqtt
  name: Luce Studio
  command_topic: "shellies/shelly1-59E18C/relay/0/command"
  state_topic: "shellies/shelly1-59E18C/relay/0"
  payload_on: "on"
  payload_off: "off"
  retain: false
  qos: 0
  optimistic: false
