######################################################################
# Alarms Package - Triggers - Automations
######################################################################

automation:
  ######################################################################
  # Alarm Door
  #
  # Actions:
  # - script.start_alarm
  ######################################################################
  - alias: "Allarmi: Porta Casa"

    trigger:
      - platform: state
        entity_id: group.doors
        to: 'on'

    condition:
      - condition: state
        entity_id: binary_sensor.guard_mode
        state: 'on'

    action:
      - service: script.start_alarm
        data_template:
          entity_id: input_boolean.door_alarm
          message: "È stata rilevata una presenza non autorizzata."
          level: 1

  ######################################################################
  # Alarm Water
  #
  # Actions:
  # - script.start_alarm
  ######################################################################
  - alias: "Allarmi: Perdita Acqua"

    trigger:
      - platform: state
        entity_id: group.water
        to: 'on'

    action:
      - service: script.start_alarm
        data_template:
          entity_id: input_boolean.water_alarm
          message: >
            Sono state rilevate perdite di acqua da: {{ expand(trigger.to_state.attributes.entity_id)|selectattr('state','eq', 'on')|map(attribute='name')|list|join(', - ') }}
          level: 1

  ######################################################################
  # Alarm Car
  #
  # Actions:
  # - script.start_alarm
  ######################################################################
  - alias: "Allarmi: Auto"

    trigger:
      - platform: state
        entity_id: group.car_alarm
        to: 'on'

    action:
      - service: script.start_alarm
        data_template:
          entity_id: input_boolean.car_alarm
          message: "Si è attivato un allarme sull'auto."
          level: 1
