######################################################################
# Alarm Package - Alarm Engine - Binary Sensors
######################################################################

template:
  - binary_sensor:
      - name: "alarms"
        unique_id: alarms
        state: "{{ is_state('group.alarms', 'on') }}"
        device_class: safety
        icon: >
          {% if is_state('group.alarms', 'on') %}
            mdi:alarm-light
          {% else %}
            mdi:alarm-light-outline
          {% endif %}

######################################################################
# Alarm Package - Alarm Engine - Automations
######################################################################

automation:

  ######################################################################
  # Alarm Automation: Aknowledge Alarms
  #
  # Actions:
  # - script.stop_alarm
  ######################################################################
  - alias: "Allarmi: Riconoscimento Allarmi"
    id: "allarmi_riconoscimento_allarmi"

    trigger:
      trigger: state
      entity_id: group.alarms
      to: 'off'

    action:
      - action: script.stop_alarm
