######################################################################
# Alarm Package - Alarm Engine - Binary Sensors
######################################################################

binary_sensor:
  # Generic Alarms
  - platform: template
    sensors:
      alarms:
        friendly_name: Allarmi
        value_template: >-
          {{ is_state('group.alarms', 'on') }}
        icon_template: >-
          {% if is_state('group.alarms', 'on') %}
             mdi:alarm-light
          {% else %}
             mdi:alarm-light-outline
          {% endif %}

######################################################################
# Alarm Package - Alarm Engine - Automations
######################################################################

automation:
  ######################################################################
  # Alarm Automation: Aknowledge Alarms
  #
  # Actions:
  # - script.stop_alarm
  ######################################################################
  - alias: "Allarmi: Riconoscimento Allarmi"

    trigger:
      platform: state
      entity_id: group.alarms
      to: 'off'

    action:
      - service: script.stop_alarm
