######################################################################
# Alarm Package - Guard Mode - Binary Sensor
######################################################################

binary_sensor:
  - platform: template
    sensors:
      guard_mode:
        friendly_name: Modalità Guardia
        entity_id: input_boolean.guard_mode
        value_template: >-
          {{ is_state('input_boolean.guard_mode', 'on') }}
        icon_template: >-
          {% if is_state('input_boolean.guard_mode', 'on') %}
             mdi:shield-home
          {% else %}
             mdi:shield-off
          {% endif %}

######################################################################
# Alarm Package - Guard Mode - Input Booleans
######################################################################

input_boolean:

  # Guard Mode
  guard_mode:
    name: Modalità Guardia
    icon: mdi:shield-home

######################################################################
# Alarm Package - Guard Mode - Automations
######################################################################

automation:

  ######################################################################
  # Guard Mode: Enable
  ######################################################################

  - alias: "Modalità Guardia: Attivazione"
    initial_state: 'on'

    trigger:
      - platform: state
        entity_id: group.residents
        from: 'home'
      - platform: homeassistant
        event: start  

    condition:
      condition: template
      value_template: >-
         {{ not is_state('group.residents', 'home') }}

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.guard_mode

  ######################################################################
  # Guard Mode: Disable
  ######################################################################

  - alias: "Modalità Guardia: Disattivazione"
    initial_state: 'on'

    trigger:
      - platform: state
        entity_id: group.residents
        to: 'home'
      - platform: homeassistant
        event: start 

    condition:
      condition: template
      value_template: >-
         {{ is_state('group.residents', 'home') }}

    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.guard_mode
