######################################################################
# Alarms Package - Automation Triggers
######################################################################

automation:

  ######################################################################
  # Alarm Door
  #
  # Actions:
  # - script.notify_all
  ######################################################################

  - alias: "Allarme Porta Casa"
    initial_state: 'on'

    trigger:
      - platform: state
        entity_id: binary_sensor.porta_casa
        to: 'on'
      
    condition:
      - condition: state
        entity_id: binary_sensor.guard_mode
        state: 'on'

    action:
      - service: script.start_alarm
        data_template:
          title: "Presenza non autorizzata"
          message: "È stata rilevata una presenza non autorizzata."
          level: 1
