######################################################################
# Away Mode - Covers Management
######################################################################

automation:
  ######################################################################
  # Automation to manage cover in away mode
  ######################################################################
  - alias: "Modalità Vacanza: Gestione Tapparelle"
    id: "modalita_vacanza_gestione_tapparelle"
    #initial_state: 'on'

    trigger:
      - trigger: time
        at: '08:00:00'
      - trigger: time
        at: '20:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.home_mode_away
        state: 'on'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id:
            - cover.tapparella_studio
            - cover.tapparella_sala
            - cover.tapparella_camera
          position: >
            {% if now().strftime('%H')|int >= 6 and now().strftime('%H')|int < 16 %}
              80
            {% else %}
              0
            {% endif %}
