######################################################################
# Away Mode - Climate Management
######################################################################

automation:
  ######################################################################
  # Automation to manage thermostatic valve in away mode
  ######################################################################
  - alias: "Modalità Vacanza: Gestione Termosifoni"
    id: "modalita_vacanza_gestione_termosifoni"

    trigger:
      - platform: state
        entity_id: input_boolean.home_mode_away
        to: 'on'
      - platform: state
        entity_id: input_boolean.home_mode_away
        to: 'off'

    condition: []

    action:
      - choose:
          # Switch On
          - conditions:
              - condition: state
                entity_id: input_boolean.home_mode_away
                state: "on"
            sequence:
              - service: script.turn_on
                data:
                  entity_id: script.climate_away_mode_on
          # Switch Off
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.home_mode_away
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.central_heating
                    state: 'on'
            sequence:
              - service: script.turn_on
                data:
                  entity_id: script.climate_away_mode_off
