######################################################################
# Away Mode - Engine
######################################################################

automation:

  ######################################################################
  # Away Mode: Enable Action
  ######################################################################
  - alias: "Modalità Vacanza: Azione on"
    initial_state: 'on'

    trigger:
      - platform: state
        entity_id: input_boolean.home_mode_away
        to: 'on'

    action:
      - service: script.notify_voice
        data_template:
          message: "Modalità vacanza abilitata"

  ######################################################################
  # Away Mode: Disable Action
  ######################################################################
  - alias: "Modalità Vacanza: Azione off"
    initial_state: 'on'

    trigger:
      # Manual Disable
      - platform: state
        entity_id: input_boolean.home_mode_away
        to: 'off'
      # Back home
      - platform: state
        entity_id: group.residents
        to: 'home'
      # End of Away Period
      - platform: time
        at: input_datetime.away_mode_end

    condition:
      condition: or
      conditions:
        - condition: template
          value_template: >-
            {% if trigger.entity_id == 'input_boolean.home_mode_away' %}
              true
            {% else %}
              false
            {% endif %}
        - condition: state
          entity_id: input_boolean.home_mode_away
          state: 'on'

    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.home_mode_away
      - service: script.notify_voice
        data_template:
          message: "Modalità vacanza disabilitata"
