######################################################################
# Switch: Lock
######################################################################

- platform: template
  switches:
    ff590mr_lock:
      friendly_name: Blocco Auto
      entity_id: lock.ff590mr_lock
      value_template: "{{ is_state('lock.ff590mr_lock', 'locked') }}"
      turn_on:
        - service: lock.lock
          entity_id: lock.ff590mr_lock
      turn_off:
      - service: lock.unlock
        entity_id: lock.ff590mr_lock      
      icon_template: >-
        {% if is_state('lock.ff590mr_lock', 'locked') %}
          mdi:lock
        {% else %}
          mdi:lock-open
        {% endif %}
