######################################################################
# Customization: Automations
######################################################################

automation.risveglio_giorgio:
  icon: mdi:alarm

automation.home_assistant_startup_restart_on_error:
  icon: mdi:restart-alert

automation.home_assistant_startup_google_sync:
  icon: mdi:google-home
