######################################################################
# Customization: Automations
######################################################################

automation.risveglio_giorgio:
  icon: mdi:alarm
