######################################################################
# Climate: Away Mode On
# - script.turn_on
######################################################################

- alias: "Termosifoni: Attiva Modalità vacanza"

  trigger:
    - platform: state
      entity_id: input_boolean.home_mode_away
      to: 'on'

  condition: []

  action:
    - service: script.turn_on
      data:
        entity_id: script.climate_away_mode_on

######################################################################
# Climate: Away Mode Off
# Note: in summer away mode off is disabled
# - climate.set_hvac_mode
######################################################################

- alias: "Termosifoni: Disattiva Modalità vacanza"

  trigger:
    - platform: state
      entity_id: input_boolean.home_mode_away
      to: 'off'

  condition: "{{ now().month > 10 or now().month < 5 }}"

  action:
    - service: script.turn_on
      data:
        entity_id: script.climate_away_mode_off

######################################################################
# Climate: Schedule according to Condominium
# - script.turn_on
######################################################################

- alias: "Termosifoni: Gestione automatica riscaldamento"

  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '00:00:00'

  condition:
    condition: or
    conditions:
      - '{{ now().month == 11 and now().day == 1}}'   # Winter
      - '{{ now().month == 4 and now().day == 15 }}'  # Summer

  action:
    - service: script.turn_on
      data_template:
        entity_id: >- 
          {% if now().month > 10 or now().month < 5 %}
            script.climate_away_mode_off
          {% else %}
            script.climate_away_mode_on
          {% endif %}
