######################################################################
# Home Door: Switch on Lights
#
# Actions:
# - light.turn_on
# - delay
#
# Note: delay is necessary to avoid multiple opening in 5 minutes
######################################################################

- alias: "Porta Casa: Accendi Luci - Corridoio"
  id: "porta_casa_accendi_luci_corridoio"
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.porta_casa_contact
      to: 'on'

  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: 1
      - condition: time
        after: "15:00:00"
        before: "05:00:00"


  action:
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.luce_corridoio
    - delay: '00:05:00'
