######################################################################
# Energy: Power Consumption Notifications
######################################################################

- alias: "Allarmi: Consumo Energetico Elevato"

  trigger:
    - platform: numeric_state
      entity_id: sensor.shelly_em_channel_1_power
      above: 2950

  action:
    service: script.notify_all
    data_template:
      title: "Home Assistant - Consumo Energetico Elevato"
      message: "Consumo energetico elevato ({{ states.sensor.shelly_em_channel_1_power.state }})."
      enable_persistent: false
      volume_level: 0.4
