######################################################################
# Home Assistant: Management of the Home Mode Button
######################################################################

- alias: "Home Assistant: Cambio modalità On"
  id: "home_assistant_cambio_modalita_on"

  trigger:
    trigger: state
    entity_id: input_boolean.home_mode_day,
               input_boolean.home_mode_night,
               input_boolean.home_mode_away
    to: 'on'

  action:
    - action: input_boolean.turn_off
      data_template:
        entity_id: >
          {% set booleans = [ 'input_boolean.home_mode_day', 'input_boolean.home_mode_night', 'input_boolean.home_mode_away' ] | reject('equalto', trigger.entity_id) %}
          {{ booleans | list | join(', ') }}

- alias: "Home Assistant: Cambio modalità Off"

  trigger:
    trigger: state
    entity_id: input_boolean.home_mode_day,
               input_boolean.home_mode_night,
               input_boolean.home_mode_away
    to: 'off'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_mode_day
        state: 'off'
      - condition: state
        entity_id: input_boolean.home_mode_night
        state: 'off'
      - condition: state
        entity_id: input_boolean.home_mode_away
        state: 'off'

  action:
    - action: input_boolean.turn_on
      data_template:
        entity_id: >
          {% if now().strftime('%H')|int >= 8 and now().strftime('%H')|int < 23 %}
            input_boolean.home_mode_day
          {% else %}
            input_boolean.home_mode_night
          {% endif %}

######################################################################
# Home Assistant: Management of Day/Night Mode
######################################################################

- alias: "Home Assistant: Modalità Giorno/Notte"
  id: "home_assistant_modalita_giorno_notte"

  trigger:
    - trigger: time
      at: '08:00:00'
    - trigger: time
      at: '23:00:00'
    - trigger: homeassistant
      event: start

  condition:
    condition: state
    entity_id: input_boolean.home_mode_away
    state: 'off'

  action:
    - action: input_boolean.turn_on
      data_template:
        entity_id: >-
          {% if now().strftime('%H')|int >= 8 and now().strftime('%H')|int < 23 %}
            input_boolean.home_mode_day
          {% else %}
            input_boolean.home_mode_night
          {% endif %}

    - action: script.volume_manager

######################################################################
# Home Assistant: Management of Speech Notifications
######################################################################

- alias: "Home Assistant: Gestione notifiche vocali"
  id: "home_assistant_gestione_notifiche_vocali"

  trigger:
    - trigger: state
      entity_id: input_boolean.home_mode_night
      to: 'on'
    - trigger: state
      entity_id: input_boolean.home_mode_night
      to: 'off'

  action:
    - action: >-
        {% if trigger.to_state.state == 'on' %}
          input_boolean.turn_off
        {% else %}
          input_boolean.turn_on
        {% endif %}
      data:
        entity_id: input_boolean.speech_notifications

######################################################################
# Home Assistant: Weekly Clean Log
# - script.homeassistant_clearlog
######################################################################

- alias: "Home Assistant: Pulitura settimanale log"
  id: "home_assistant_pulitura_settimanale_log"

  trigger:
    - trigger: time
      at: '00:00:00'

  condition:
    - condition: time
      weekday: [mon]

  action:
    - action: script.homeassistant_clearlog
