######################################################################
# Google Home: speeak message
# - script.notify_voice
######################################################################

- alias: "Google Home: Pronuncia testo"
  id: "google_home_pronuncia_testo"

  trigger:
    - trigger: state
      entity_id: input_text.google_home_speak
    - trigger: state
      entity_id: input_text.google_anna_speak

  condition: []

  action:
    - action: script.speech_engine
      data_template:
        media_player: >
          {% if trigger.entity_id == 'input_text.google_anna_speak' %}
            media_player.google_anna
          {% else %}
            media_player.google_home
          {% endif %}
        message: "{{ trigger.to_state.state }}"
