######################################################################
# Google Home: speeak message
# - script.notify_voice
######################################################################

- alias: "Google Home: Pronuncia testo"

  trigger:
    - platform: state
      entity_id: input_text.google_home_speak

  condition: []

  action:
    - service: script.speech_engine
      data_template:
        media_player: "media_player.google_home"
        message: "{{ trigger.to_state.state }}"
