######################################################################
# NFC: Notification
######################################################################

- alias: "NFC Notifica Scansione"
  id: "nfc_notifica_scansione"
  mode: single
  max_exceeded: silent

  variables:
    allowed_devices:
      !secret giorgio_smartphone_nfc:
        name: "Giorgio"
      !secret laura_smartphone_nfc:
        name: "Laura"
    allowed_tags:
      !secret nfc_1:
        name: "NFC_1"

  trigger:
    trigger: event
    event_type: tag_scanned

  action:
    - variables:
        detected_tag: "{{ trigger.event.data.tag_id }}"
        detected_device: "{{ trigger.event.data.device_id }}"

    - choose:
        - conditions:
            - "{{ detected_tag in allowed_tags }}"
            - "{{ detected_device in allowed_devices }}"
          sequence:
            - action: script.notify_text
              data_template:
                title: "Home Assistant - Lettura NFC"
                message: "Letto tag NFC {{ allowed_tags[detected_tag].name }} dal dispositivo {{ allowed_devices[detected_device].name }}."
                enable_telegram: false

        - conditions:
            - "{{ detected_tag in allowed_tags }}"
            - "{{ detected_device not in allowed_devices }}"
          sequence:
            - action: script.notify_text
              data_template:
                title: "Home Assistant - Lettura NFC"
                message: "Letto tag NFC {{ allowed_tags[detected_tag].name }} da dispositivo non valido ({{ detected_device }})."
                enable_telegram: false

        - conditions:
            - "{{ detected_tag not in allowed_tags }}"
            - "{{ detected_device in allowed_devices }}"
          sequence:
            - action: script.notify_text
              data_template:
                title: "Home Assistant - Lettura NFC"
                message: "Letto tag NFC non riconosciuto ({{ detected_tag }}) dal dispositivo {{ allowed_devices[detected_device].name }}."
                enable_telegram: false

      default:
        - action: script.notify_text
          data_template:
            title: "Home Assistant - Lettura NFC"
            message: "Letto tag NFC non valido ({{ detected_tag }}) da dispositivo non valido ({{ detected_device }})."
            enable_telegram: false
