######################################################################
# Night Time
# - Switch off all covers
######################################################################

- alias: "Modalità Notte"
  id: "modalita_notte"
  initial_state: false

  triggers:
    - trigger: state
      entity_id: input_boolean.home_mode_night
      to: 'on'

  actions:
    - action: cover.set_cover_position
      data:
        position: 0
        entity_id:
          - cover.tapparella_cucina_grande
          - cover.tapparella_sala
          - cover.tapparella_studio
          - cover.tapparella_camera
