######################################################################
# Welcome message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: Saluto di benvenuto
  id: "saluto_di_benvenuto"
  mode: parallel

  trigger:
    - trigger: zone
      entity_id:
        - person.giorgio
        - person.laura
        # - person.anna
      zone: zone.home
      event: enter

  condition: []

  action:
    - wait_for_trigger:
        - trigger: state
          entity_id: binary_sensor.porta_casa_contact
          to: "on"
      timeout:
        minutes: 30
      continue_on_timeout: false

    - delay: 00:00:05

    - action: script.speech_engine
      data_template:
        message: !include ../template_messages/welcome.yaml
        enable_greeting: 0

######################################################################
# Hourly message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: "Saluto orario"
  initial_state: false

  trigger:
    - trigger: time
      at: '12:00:00'

  condition: []

  action:
    - action: script.speech_engine
      data_template:
        message: >-
          {% set hour = now().strftime('%H') %}
          "Sono le {{ hour }} e tutto va bene."
