######################################################################
# Welcome message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: Saluto di benvenuto
  mode: parallel

  trigger:
    - platform: zone
      entity_id:
        - person.giorgio
        - person.laura
        # - person.anna
      zone: zone.home
      event: enter

  condition: []

  action:
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.main_door_contact
          to: "on"
      timeout: 
        minutes: 30
      continue_on_timeout: false

    - delay: 00:00:05

    - service: script.speech_engine
      data_template:
        message: !include ../templates/welcome_message.yaml
        enable_greeting: 0

######################################################################
# Hourly message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: "Saluto orario"
  initial_state: false
  
  trigger:
    - platform: time
      at: '12:00:00'

  condition: []

  action:
    - service: script.speech_engine
      data_template:
        message: >- 
          {% set hour = now().strftime('%H') %}
          "Sono le {{ hour }} e tutto va bene."
