######################################################################
# Startup Automation: Restart on Error
######################################################################

- alias: "Home Assistant - Startup: Restart on Error"
  id: "home_assistant_startup_restart_on_error"

  trigger:
    - platform: homeassistant
      event: start

  action:
    - delay: 00:00:60
    - condition: state
      entity_id: persistent_notification.invalid_config
      state: 'notifying'
    - service: script.homeassistant_restart

######################################################################
# Startup Automation: Google Sync
######################################################################

- alias: "Home Assistant - Startup: Google Sync"
  id: "home_assistant_startup_google_sync"

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: script.homeassistant_google_home_sync
