######################################################################
# Startup Automation: Google Sync
######################################################################

- alias: "Home Assistant - Startup: Google Sync"
  id: "home_assistant_startup_google_sync"

  triggers:
    - trigger: homeassistant
      event: start

  actions:
    - action: script.homeassistant_google_home_sync
