######################################################################
# Test Mode: Enable Action
######################################################################

- alias: "Modalità Test: Azione on"

  trigger:
    - platform: state
      entity_id: input_boolean.test_mode
      to: 'on'

  action:

    - service: automation.turn_off
      entity_id: automation.startup_restart_on_error

    - service: automation.turn_off
      entity_id: automation.startup_google_sync

######################################################################
# Test Mode: Disable Action
######################################################################

- alias: "Modalità Test: Azione off"

  trigger:
    - platform: state
      entity_id: input_boolean.test_mode
      to: 'off'

  action:
    - service: automation.turn_on
      entity_id: automation.startup_restart_on_error

    - service: automation.turn_on
      entity_id: automation.startup_google_sync
