######################################################################
# Themes: Management of Day/Night Mode
######################################################################

- alias: "Home Assistant - Temi: Modalità Giorno/Notte"
  id: "home_assistant_temi_modalita_giorno_notte"

  trigger:
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: input_boolean.home_mode_day
      to: 'on'
    - trigger: state
      entity_id: input_boolean.home_mode_night
      to: 'on'
    - trigger: state
      entity_id: input_boolean.home_mode_away
      to: 'on'

  action:
    - delay:
        milliseconds: 50
    - action: frontend.set_theme
      data_template:
        name: >-
          {% if is_state('sensor.home_mode', 'giorno') %}
            default
          {% endif %}
          {% if is_state('sensor.home_mode', 'notte') %}
            darkish
          {% endif %}
          {% if is_state('sensor.home_mode', 'vacanza') %}
            reeder_dark
          {% endif %}
