######################################################################
# Themes: Management of Day/Night Mode
######################################################################

- alias: "Temi: Modalità giorno/Notte"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: input_boolean.home_mode_day
      to: 'on'
    - platform: state
      entity_id: input_boolean.home_mode_night
      to: 'on'
    - platform: state
      entity_id: input_boolean.home_mode_away
      to: 'on'

  action:
    - service: frontend.set_theme
      data_template:
        name: >-
          {% if trigger.entity_id == 'input_boolean.home_mode_day' %}
            default
          {% endif %}
          {% if trigger.entity_id == 'input_boolean.home_mode_night' %}
            darkish
          {% endif %}
          {% if trigger.entity_id == 'input_boolean.home_mode_away' %}
            reeder_dark
          {% endif %}
