######################################################################
# Themes: Management of Day/Night Mode
######################################################################

- alias: "Temi: Modalità giorno/Notte"

  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.home_mode_day
      to: 'on'
    - platform: state
      entity_id: input_boolean.home_mode_night
      to: 'on'
    - platform: state
      entity_id: input_boolean.home_mode_away
      to: 'on'

  action:
    - delay:
        milliseconds: 50
    - service: frontend.set_theme
      data_template:
        name: >-
          {% if is_state('sensor.home_mode', 'giorno') %}
            default
          {% endif %}
          {% if is_state('sensor.home_mode', 'notte') %}
            darkish
          {% endif %}
          {% if is_state('sensor.home_mode', 'vacanza') %}
            reeder_dark
          {% endif %}
