######################################################################
# Update Notification: Shelly
######################################################################

- alias: "Update Notification: Shelly"

  trigger:
    - platform: state
      entity_id: group.shelly
      to: 'on'

    - platform: homeassistant
      event: start

  condition:
    condition: state
    entity_id: group.shelly
    state: 'on'

  action:
    - delay: '00:00:10'
    - service: script.notify_text
      data_template:
        title: "Shelly - Aggiornamento"
        message: >
          Sono disponibili aggiornamenti per i dispositivi Shelly:
          {%- for entity_id in states.group.shelly.attributes.entity_id -%}
            {% if is_state(entity_id, 'on') %}
              -> {{ state_attr(entity_id, 'friendly_name')|replace(" - Aggiornamento Firmware", "") }}: {{ state_attr(entity_id, 'latest_version') }}
            {%- endif -%}
          {%- endfor -%}
        notification_id: "update"
        enable_persistent: true

    - service: input_boolean.turn_on
      entity_id: input_boolean.update_shelly

######################################################################
# Update Notification: HACS
######################################################################

- alias: "Update Notification: HACS"

  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0

    - platform: homeassistant
      event: start

  condition:
    condition: numeric_state
    entity_id: sensor.hacs
    above: 0

  action:
    - delay: '00:00:15'
    - service: script.notify_text
      data_template:
        title: "HACS - Aggiornamento"
        message: >
          {% set update_number = states('sensor.hacs') %}
          {% if is_state('sensor.hacs', '1') %}
            E' disponibile un aggiornamento per i moduli HACS:
          {% else %}
            Sono disponibili {{ update_number }} aggiornamenti per i moduli HACS:
          {% endif %}
          {% for update in states.sensor.hacs.attributes['repositories'] %}
            - {{ update['display_name'] }}: {{ update['available_version'] }}
          {%- endfor %}
        notification_id: "update"
        enable_persistent: true

    - service: input_boolean.turn_on
      entity_id: input_boolean.update_hacs

######################################################################
# Update: Aknowledge update
#
# Actions:
# - persistent_notification.dismiss
######################################################################
- alias: "Update: Riconoscimento Aggiornamenti"

  trigger:
    platform: state
    entity_id:
      - input_boolean.update_homeassistant
      - input_boolean.update_shelly
      - input_boolean.update_hacs
    to: 'off'

  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: "update"
