######################################################################
# Global Cover
######################################################################

- platform: group
  name: "Tapparella Globale"
  entities:
  - cover.tapparella_cucina
  - cover.tapparella_sala
  - cover.tapparella_studio
  - cover.tapparella_camera
