######################################################################
# Kitchen Cover
######################################################################

- platform: mqtt
  name: Tapparella Cucina
  command_topic: "shellies/shellyswitch-55980F/roller/0/command"
  position_topic: "shellies/shellyswitch-55980F/roller/0/pos"
  set_position_topic: "shellies/shellyswitch-55980F/roller/0/command/pos"
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  retain: false
  optimistic: false
  qos: 0
