######################################################################
# Sensor: Temperature from Radiator Valve
######################################################################

- platform: template
  sensors:
    valve_cucina_temperature:
      friendly_name: "Temperatura Cucina"
      value_template: "{{ state_attr('climate.netatmo_cucina', 'current_temperature') }}" 
      unit_of_measurement: '°C'
      device_class: temperature
     
- platform: template
  sensors:
    valve_sala_temperature:
      friendly_name: "Temperatura Sala"
      value_template: "{{ state_attr('climate.netatmo_sala', 'current_temperature') }}"
      unit_of_measurement: '°C'
      device_class: temperature

- platform: template
  sensors:
    valve_studio_temperature:
      friendly_name: "Temperatura Studio"
      value_template: "{{ state_attr('climate.netatmo_studio', 'current_temperature') }}"
      unit_of_measurement: '°C'    
      device_class: temperature

- platform: template
  sensors:
    valve_bagno_temperature:
      friendly_name: "Temperatura Bagno"
      value_template: "{{ state_attr('climate.netatmo_bagno', 'current_temperature') }}"
      unit_of_measurement: '°C'
      device_class: temperature

- platform: template
  sensors:
    valve_camera_da_letto_temperature:
      friendly_name: "Temperatura Camera"
      value_template: "{{ state_attr('climate.netatmo_camera_da_letto', 'current_temperature') }}"
      unit_of_measurement: '°C'
      device_class: temperature

######################################################################
# Sensor: Battery from Radiator Valve
######################################################################

- platform: template
  sensors:
    valve_cucina_battery:
      friendly_name: "Batteria Valvola Cucina"
      value_template: "{{ state_attr('climate.netatmo_cucina', 'battery_level') }}" 
      unit_of_measurement: '%'
      device_class: battery
     
- platform: template
  sensors:
    valve_sala_battery:
      friendly_name: "Batteria Valvola Sala"
      value_template: "{{ state_attr('climate.netatmo_sala', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery

- platform: template
  sensors:
    valve_studio_battery:
      friendly_name: "Batteria Valvola Studio"
      value_template: "{{ state_attr('climate.netatmo_studio', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery

- platform: template
  sensors:
    valve_bagno_battery:
      friendly_name: "Batteria Valvola Bagno"
      value_template: "{{ state_attr('climate.netatmo_bagno', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery
    
- platform: template
  sensors:
    valve_camera_da_letto_battery:
      friendly_name: "Batteria Valvola Camera"
      value_template: "{{ state_attr('climate.netatmo_camera_da_letto', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery

######################################################################
# Sensor: State from Radiator Valve
######################################################################

- platform: template
  sensors:
    valve_cucina_state:
      friendly_name: "Stato Valvola Cucina"
      value_template: "{{ state_attr('climate.netatmo_cucina', 'hvac_action') }}" 
      icon_template: >-
        {% if is_state_attr('climate.netatmo_cucina', 'hvac_action', 'idle') %}
          mdi:radiator-disabled
        {% else %}
          mdi:radiator
        {% endif %}

- platform: template
  sensors:
    valve_sala_state:
      friendly_name: "Stato Valvola Sala"
      value_template: "{{ state_attr('climate.netatmo_sala', 'hvac_action') }}"
      icon_template: >-
        {% if is_state_attr('climate.netatmo_sala', 'hvac_action', 'idle') %}
          mdi:radiator-disabled
        {% else %}
          mdi:radiator
        {% endif %}

- platform: template
  sensors:
    valve_studio_state:
      friendly_name: "Stato Valvola Studio"
      value_template: "{{ state_attr('climate.netatmo_studio', 'hvac_action') }}"
      icon_template: >-
        {% if is_state_attr('climate.netatmo_studio', 'hvac_action', 'idle') %}
          mdi:radiator-disabled
        {% else %}
          mdi:radiator
        {% endif %}

- platform: template
  sensors:
    valve_bagno_state:
      friendly_name: "Stato Valvola Bagno"
      value_template: "{{ state_attr('climate.netatmo_bagno', 'hvac_action') }}"
      icon_template: >-
        {% if is_state_attr('climate.netatmo_bagno', 'hvac_action', 'idle') %}
          mdi:radiator-disabled
        {% else %}
          mdi:radiator
        {% endif %}

- platform: template
  sensors:
    valve_camera_da_letto_state:
      friendly_name: "Stato Valvola Camera"
      value_template: "{{ state_attr('climate.netatmo_camera_da_letto', 'hvac_action') }}"
      icon_template: >-
        {% if is_state_attr('climate.netatmo_camera_da_letto', 'hvac_action', 'idle') %}
          mdi:radiator-disabled
        {% else %}
          mdi:radiator
        {% endif %}
