######################################################################
# Sensor: Home Mode
######################################################################

- platform: template
  sensors:
    home_mode:
      friendly_name: Modalità Casa
      value_template: >-
        {% if is_state('input_boolean.home_mode_day', 'on') %}
          giorno
        {% elif is_state('input_boolean.home_mode_night', 'on') %}
          notte
        {% elif is_state('input_boolean.home_mode_away', 'on') %}
          vacanza
        {% endif %}
      icon_template: >-
        {% if is_state('input_boolean.home_mode_day', 'on') %}
          mdi:white-balance-sunny
        {% elif is_state('input_boolean.home_mode_night', 'on') %}
          mdi:weather-night
        {% elif is_state('input_boolean.home_mode_away', 'on') %}
          mdi:airplane-takeoff
        {% endif %}
