######################################################################
# Sensor: Shelly 1
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly1.giorgioravera.it/status
  method: GET
  name: shelly1_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 2
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly2.giorgioravera.it/status
  method: GET
  name: shelly2_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 3
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly3.giorgioravera.it/status
  method: GET
  name: shelly3_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 4
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly4.giorgioravera.it/status
  method: GET
  name: shelly4_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 5
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly5.giorgioravera.it/status
  method: GET
  name: shelly5_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 6
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly6.giorgioravera.it/status
  method: GET
  name: shelly6_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 7
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly7.giorgioravera.it/status
  method: GET
  name: shelly7_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 8
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly8.giorgioravera.it/status
  method: GET
  name: shelly8_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 9
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly9.giorgioravera.it/status
  method: GET
  name: shelly9_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 10
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly10.giorgioravera.it/status
  method: GET
  name: shelly10_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly 11
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shelly11.giorgioravera.it/status
  method: GET
  name: shelly11_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly Bulb
######################################################################

#- platform: rest
#  scan_interval: 43200
#  resource: http://shellybulb.giorgioravera.it/status
#  method: GET
#  name: shellybulb_status
#  #value_template: '{{ value_json.has_update }}'
#  value_template: >-
#    {% if value_json.has_update == True %}
#      on
#    {% else %}
#      off
#    {% endif %}
#  authentication: basic
#  username: !secret shelly_user
#  password: !secret shelly_password
#  json_attributes:
#  #  - wifi_sta
#  #  - mqtt
#  #  - time
#  #  - has_update
#    - mac
#    - update
#    - uptime

######################################################################
# Sensor: Shelly EM
######################################################################

- platform: rest
  scan_interval: 43200
  resource: http://shellyem.giorgioravera.it/status
  method: GET
  name: shellyem_status
  #value_template: '{{ value_json.has_update }}'
  value_template: >-
    {% if value_json.has_update == True %}
      on
    {% else %}
      off
    {% endif %}
  authentication: basic
  username: !secret shelly_user
  password: !secret shelly_password
  json_attributes:
  #  - wifi_sta
  #  - mqtt
  #  - time
  #  - has_update
    - mac
    - update
    - uptime

######################################################################
# Sensor: Shelly Door/Window
######################################################################

#- platform: rest
#  scan_interval: 43200
#  resource: http://shellydw.giorgioravera.it/status
#  method: GET
#  name: shellyplugs_status
#  #value_template: '{{ value_json.has_update }}'
#  value_template: >-
#    {% if value_json.has_update == True %}
#      on
#    {% else %}
#      off
#    {% endif %}
#  authentication: basic
#  username: !secret shelly_user
#  password: !secret shelly_password
#  json_attributes:
#  #  - wifi_sta
#  #  - mqtt
#  #  - time
#  #  - has_update
#    - mac
#    - update
#    - uptime

######################################################################
# Sensor: Shelly Plug S
######################################################################

#- platform: rest
#  scan_interval: 43200
#  resource: http://shellyplugs.giorgioravera.it/status
#  method: GET
#  name: shellyplugs_status
#  #value_template: '{{ value_json.has_update }}'
#  value_template: >-
#    {% if value_json.has_update == True %}
#      on
#    {% else %}
#      off
#    {% endif %}
#  authentication: basic
#  username: !secret shelly_user
#  password: !secret shelly_password
#  json_attributes:
#  #  - wifi_sta
#  #  - mqtt
#  #  - time
#  #  - has_update
#    - mac
#    - update
#    - uptime

######################################################################
# Shelly Door/Window
######################################################################

#- platform: mqtt
#  name: "Porta Casa 3: Batteria"
#  state_topic: "shellies/shellydw-B88F53/sensor/battery"
#  unit_of_measurement: '%'
#  #availability_topic: "shellies/shellydw-B88F53/online"
#  #payload_available: "true"
#  #payload_not_available: "false"
#  qos: 0
#  device_class: battery

#- platform: mqtt
#  name: "Porta Casa 3: Luce"
#  state_topic: "shellies/shellydw-B88F53/sensor/lux"
#  unit_of_measurement: 'lux'
#  #availability_topic: "shellies/shellydw-B88F53/online"
#  #payload_available: "true"
#  #payload_not_available: "false"
#  qos: 0
#  device_class: illuminance
