######################################################################
# Speed Test Sensor
######################################################################

- platform: speedtest
  minute: 0
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
