######################################################################
# Xiaomi MiJia Wireless Switch (WXKG01LM )
######################################################################

- platform: "mqtt"
  name: "Pulsante: Stato"
  state_topic: "zigbee2mqtt/0x00158d0004081917"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"

- platform: "mqtt"
  name: "Pulsante: Batteria"
  state_topic: "zigbee2mqtt/0x00158d0004081917"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Pulsante: Stato Link"
  state_topic: "zigbee2mqtt/0x00158d0004081917"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"