######################################################################
# MCCGQ01LM - Xiaomi MiJia door & window contact sensor
######################################################################

- platform: "mqtt"
  name: "Porta Casa: Batteria"
  state_topic: "zigbee2mqtt/0x00158d0003e79145"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Porta Casa: Stato Link"
  state_topic: "zigbee2mqtt/0x00158d0003e79145"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"

######################################################################
# MCCGQ11LM - Xiaomi Aqara door & window contact sensor
######################################################################

- platform: "mqtt"
  name: "Porta Casa 2: Batteria"
  state_topic: "zigbee2mqtt/0x00158d0002caf32f"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Porta Casa 2: Stato Link"
  state_topic: "zigbee2mqtt/0x00158d0002caf32f"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.linkquality }}"

######################################################################
# WXKG01LM - Xiaomi MiJia wireless switch
######################################################################

- platform: "mqtt"
  name: "Pulsante: Stato"
  state_topic: "zigbee2mqtt/0x00158d0004081917"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"

- platform: "mqtt"
  name: "Pulsante: Batteria"
  state_topic: "zigbee2mqtt/0x00158d0004081917"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Pulsante: Stato Link"
  state_topic: "zigbee2mqtt/0x00158d0004081917"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"
