######################################################################
# Alarm: Aknowledge Alarms
#
# Actions:
# - persistent_notification.dismiss
# - script.stop_alarm
######################################################################
- alias: "Alarms: Riconoscimento Allarmi"
  initial_state: 'on'

  trigger:
    platform: state
    entity_id: input_boolean.alarms
    to: 'off'

  action:
    - service: script.stop_alarm
