######################################################################
# Car: FF590MR lock/unlock Button Management
######################################################################

- alias: "FF590MR Pulsante Blocca Vettura"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: lock.ff590mr_lock
      to: 'locked'
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: lock.ff590mr_lock
      state: 'locked'

  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.ff590mr_lock

- alias: "FF590MR Pulsante Sblocca Vettura"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: lock.ff590mr_lock
      to: 'unlocked'
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: lock.ff590mr_lock
      state: 'unlocked'

  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.ff590mr_lock

######################################################################
# Car: FF590MR lock/unlock
######################################################################

- alias: "FF590MR Blocca Vettura"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: input_boolean.ff590mr_lock
      to: 'on'

  action:
    - service: lock.lock
      entity_id: lock.ff590mr_lock
 
- alias: "FF590MR Sblocca Vettura"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: input_boolean.ff590mr_lock
      to: 'off'

  action:
    - service: lock.unlock
      entity_id: lock.ff590mr_unlock
 
