######################################################################
# Climate: Weekly Schedule
# - script.climate_daily_schedule
######################################################################

- alias: "Termosifoni: Schedulazione giornaliera feriale"
  initial_state: 'off'

  trigger:
    - platform: time
      at: '06:30:00'
    - platform: time
      at: '07:30:00'
    - platform: time
      at: '09:00:00'
    - platform: time
      at: '18:30:00'
    - platform: time
      at: '22:00:00'
#    - platform: state
#      entity_id: input_boolean.home_mode_away
#      to: 'off'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_mode_away
        state: 'off'

      - condition: time
        weekday: [mon, tue, wed, thu, fri]

  action:
    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.cucina_termostato_cucina
        temp1: 20
        temp2: 18
        temp3: 20
        temp4: 20.5
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.sala_termostato_sala
        temp1: 18
        temp2: 18
        temp3: 19.5
        temp4: 20
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.bagno_termostato_bagno
        temp1: 19
        temp2: 18
        temp3: 19
        temp4: 19.5
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.studio_termostato_studio
        temp1: 18
        temp2: 18
        temp3: 19.5
        temp4: 20
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.camera_termostato_camera
        temp1: 19
        temp2: 18
        temp3: 19
        temp4: 19.5
        temp5: 16

######################################################################
# Climate: Away Mode
# - climate.set_operation_mode
# - climate.set_temperature
######################################################################

- alias: "Termosifoni: Modalità vacanza"
  initial_state: 'off'

  trigger:
    - platform: state
      entity_id: input_boolean.home_mode_away
      to: 'on'
    - platform: state
      entity_id: input_boolean.home_mode_away
      to: 'off'

  condition: []

  action:
    - service: script.climate_away_mode
      data_template:
        entity_id: climate.cucina_termostato_cucina

    - service: script.climate_away_mode
      data_template:
        entity_id: climate.sala_termostato_sala
        mode: trigger.to_state.state

    - service: script.climate_away_mode
      data_template:
        entity_id: climate.bagno_termostato_bagno
        mode: trigger.to_state.state
          
    - service: script.climate_away_mode
      data_template:
        entity_id: climate.studio_termostato_studio
        mode: trigger.to_state.state
          
    - service: script.climate_away_mode
      data_template:
        entity_id: climate.camera_termostato_camera
        mode: trigger.to_state.state