######################################################################
# Climate: Weekly Schedule
# - script.climate_daily_schedule
######################################################################

- alias: "Termosifoni: Schedule Feriale"
  trigger:
    - platform: time
      at: '06:30:00'
    - platform: time
      at: '07:30:00'
    - platform: time
      at: '09:00:00'
    - platform: time
      at: '18:30:00'
    - platform: time
      at: '22:00:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.home_mode_away
        state: 'off'

      - condition: time
        weekday: [mon, tue, wed, thu, fri]

  action:
    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.bagno_termostato_cucina
        temp1: 20
        temp2: 18
        temp3: 20
        temp4: 20.5
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.bagno_termostato_sala
        temp1: 18
        temp2: 18
        temp3: 19.5
        temp4: 20
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.bagno_termostato_bagno
        temp1: 19
        temp2: 18
        temp3: 19
        temp4: 29.5
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.bagno_termostato_studio
        temp1: 18
        temp2: 18
        temp3: 19.5
        temp4: 20
        temp5: 16

    - service: script.climate_daily_schedule
      data_template:
        entity_id: climate.bagno_termostato_camera
        temp1: 19
        temp2: 18
        temp3: 19
        temp4: 19.5
        temp5: 16
