######################################################################
# Home Door: Switch on Lights
#
# Actions:
# - light.turn_on
# - delay
#
# Note: delay is necessary to avoid multiple opening in 5 minutes
######################################################################

- alias: "Porta Casa: Accendi Luce Corridoio"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: binary_sensor.porta_casa_stato
      to: 'on'

  condition:
     - condition: numeric_state
       entity_id: sun.sun
       value_template: "{{ state_attr('sun.sun', 'elevation') }}"
       below: -10

  action:
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.luce_corridoio
    - delay: '00:05:00'

######################################################################
# Home Door: Alarm
#
# Actions:
# - script.notify_all
######################################################################

- alias: "Porta Casa: Allarme"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: binary_sensor.porta_casa_stato
      to: 'on'
    
  condition:
    - condition: state
      entity_id: binary_sensor.guard_mode
      state: 'on'

  action:
    - service: script.start_alarm
      data_template:
        title: "Presenza non autorizzata"
        message: "È stata rilevata una presenza non autorizzata."
        level: 1
