######################################################################
# Guard Mode: Enable
######################################################################

- alias: "Modalità Guardia: Attivazione"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: group.residents
      from: 'home'
    - platform: homeassistant
      event: start  

  condition:
    condition: template
    value_template: >-
       {{ not is_state('group.residents', 'home') }}

  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.guard_mode

######################################################################
# Guard Mode: Disable
######################################################################

- alias: "Modalità Guardia: Disattivazione"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
    - platform: homeassistant
      event: start 

  condition:
    condition: template
    value_template: >-
       {{ is_state('group.residents', 'home') }}

  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.guard_mode
