######################################################################
# TV: change channel
# - script.tv_change_channel
######################################################################

- alias: "TV: Cambia canale"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: input_text.tv_change_channel

  condition: []

  action:
    - service: script.tv_change_channel
      data_template:
        tv: "media_player.tv_sala"
        channel: "{{ trigger.to_state.state }}"

######################################################################
# Google Home: speeak message
# - script.notify_voice
######################################################################

- alias: "Google Home: Pronuncia testo"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: input_text.google_home_speak

  condition: []

  action:
    - service: script.speech_engine
      data_template:
        media_player: "media_player.google_home"
        message: "{{ trigger.to_state.state }}"
