######################################################################
# Night Time
# - Switch off all covers
######################################################################

- alias: "Notte: Chiusura tapparelle"
  initial_state: 'off'

  trigger:
    - platform: state
      entity_id: input_boolean.home_mode_night
      to: 'on'

  condition: []
#    condition: state
#    entity_id: input_boolean.home_mode_away
#    state: 'off'

  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.all_covers
        position: 15

    - service: cover.set_cover_position
      data:
        entity_id: cover.tapparella_camera
        position: 0
