######################################################################
# Shelly: Update Available Notifications
######################################################################

- alias: "Shelly: Notifica aggiornamento"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: group.shelly
      to: 'on'

  action:
    service: script.notify_text
    data_template:
      title: "Shelly - Aggiornamento"
      message: "Sono disponibili aggiornamenti per i dispositivi Shelly"
      enable_persistant: true

