######################################################################
# Welcome message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: Saluto di benvenuto
  initial_state: 'on'

  trigger:
    - platform: zone
      entity_id:
        - device_tracker.google_maps_115265981849847357125
        - device_tracker.google_maps_103158638433668748797
        # - device_tracker.google_maps_113099283296073047871
      zone: zone.home
      event: enter
#    - platform: state
#      entity_id: 
#        - device_tracker.s9
#        - device_tracker.a5
#      to: 'home'
#      for: '00:00:30'

  condition: []

  action:
#    - wait_template: >-
#        {# Giorgio #}
#        {% if trigger.entity_id == 'device_tracker.google_maps_115265981849847357125' %}
#          {% if is_state('device_tracker.s9', 'home') %}
#            true
#          {% else %}
#            false
#          {% endif %}
#        
#        {# Laura #}
#        {% elif trigger.entity_id == 'device_tracker.google_maps_103158638433668748797' %}
#          {% if is_state('device_tracker.a5', 'home') %}
#            true
#          {% else %}
#            false
#          {% endif %}
#        
#        {# Anna #}
#        {% elif trigger.entity_id == 'device_tracker.google_maps_113099283296073047871' %}
#          {% if is_state('device_tracker.a3', 'home') %}
#            true
#          {% else %}
#            false
#          {% endif %}
#       
#        {# Others #}
#        {% else %}
#          false
#        {% endif %}
#
#      timeout: '00:30:00'
#      continue_on_timeout: 'false'

    - wait_template: "{{ is_state('binary_sensor.porta_casa', 'on') }}"
      timeout: '00:30:00'
      continue_on_timeout: 'false'

    - delay: 00:00:05

    - service: script.speech_engine
      data_template:
        message: !include ../templates/welcome_message.yaml
        enable_greeting: 0

######################################################################
# Hourly message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: "Saluto orario"
  initial_state: 'off'
  
  trigger:
    - platform: time
      at: '12:00:00'

  condition: []

  action:
    - service: script.speech_engine
      data_template:
        message: >- 
          {% set hour = now().strftime('%H') %}
          "Sono le {{ hour }} e tutto va bene."
