######################################################################
# Welcome message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: Saluto di benvenuto
  initial_state: 'on'

  trigger:
    - platform: zone
      entity_id:
        - device_tracker.google_maps_115265981849847357125
        - device_tracker.google_maps_103158638433668748797
        # - device_tracker.google_maps_113099283296073047871
      zone: zone.home
      event: enter
#    - platform: state
#      entity_id: 
#        - device_tracker.s9
#        - device_tracker.a5
#      to: 'home'
#      for: '00:00:30'

  condition: []

  action:
#    - wait_template: >-
#        {# Giorgio #}
#        {% if trigger.entity_id == 'device_tracker.google_maps_115265981849847357125' %}
#          {% if is_state('device_tracker.s9', 'home') %}
#            true
#          {% else %}
#            false
#          {% endif %}
#        
#        {# Laura #}
#        {% elif trigger.entity_id == 'device_tracker.google_maps_103158638433668748797' %}
#          {% if is_state('device_tracker.a5', 'home') %}
#            true
#          {% else %}
#            false
#          {% endif %}
#        
#        {# Anna #}
#        {% elif trigger.entity_id == 'device_tracker.google_maps_113099283296073047871' %}
#          {% if is_state('device_tracker.a3', 'home') %}
#            true
#          {% else %}
#            false
#          {% endif %}
#       
#        {# Others #}
#        {% else %}
#          false
#        {% endif %}
#
#      timeout: '00:30:00'
#      continue_on_timeout: 'false'

    - wait_template: "{{ is_state('binary_sensor.porta_casa', 'on') }}"
      timeout: '00:30:00'
      continue_on_timeout: 'false'

    - delay: 00:00:05

    - service: script.speech_engine
      data_template:
        language: 'it'
        message: >-
          {% set name = state_attr(trigger.entity_id, 'friendly_name') %}
          {%- macro greeting_sentence(name) -%}
          {{ [
          "Ciao " ~ name + " è un piacere rivederti a casa",
          "Finalmente a casa " ~ name + "!",
          "Indovina chi è a casa? " ~ name + "!",
          name + " è ora a casa!",
          "Che bello! " ~ name + " è a casa",
          name + " sei a casa!",
          "Il sistema di domotica Casa Ravera-Testa notifica che " ~ name + " è a casa!",
          "Annuncio: " ~ name + " è ora a casa!",
          "Rilevo una presenza! " ~ name + " è a casa!",
          "Ciao " ~ name + " che la forza sia con te",
          "Sento un tremito nella forza! " ~ name + " è a casa",
          "Sento un interferenza nella Forza! " ~ name + " è qui",
          "Menomale che sei qui " ~ name + "! Mi sentivo solo",
          "Menomale che sei qui " ~ name + "! La casa è vuota senza di te!",
          "Ciao " ~ name + "! Casa è sempre la casa!"
          ] | random }}
          {%- endmacro -%}
          {{ greeting_sentence(name) }}
        enable_greeting: 0

######################################################################
# Hourly message
#
# Operations:
# - script.speech_engine
######################################################################

- alias: "Saluto orario"
  initial_state: 'off'
  
  trigger:
    - platform: time
      at: '12:00:00'

  condition: []

  action:
    - service: script.speech_engine
      data_template:
        message: >- 
          {% set hour = now().strftime('%H') %}
          "Sono le {{ hour }} e tutto va bene."
