######################################################################
# Themes: Management of Day/Night Mode
######################################################################

- alias: "Temi: Modalità giorno/Notte"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: input_boolean.home_mode_night
      to: 'on'
    - platform: state
      entity_id: input_boolean.home_mode_night
      to: 'off'
      
  action:
    - service: frontend.set_theme
      data_template:
        name: >-
          {% if trigger.to_state.state == 'on' %}
            midnight
          {% else %}
            default
          {% endif %}  
