######################################################################
# Update Notification: Home Assistant
######################################################################

- alias: "Update Notification: Home Assistant"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      to: 'on'

  action:
    service: script.notify_text
    data_template:
      title: "Home Assistant - Aggiornamento"
      message: "E' disponibile un aggiornamento per Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }}. {{now().strftime('%Y-%m-%d %I:%M %p')}}"
      enable_persistant: true

######################################################################
# Update Notification: Shelly
######################################################################

- alias: "Update Notification: Shelly"
  initial_state: 'on'

  trigger:
    - platform: state
      entity_id: group.shelly
      to: 'on'

  action:
    service: script.notify_text
    data_template:
      title: "Shelly - Aggiornamento"
      message: "Sono disponibili aggiornamenti per i dispositivi Shelly"
      enable_persistant: true

######################################################################
# Update Notification: HACS
######################################################################

- alias: "Update Notification: HACS"
  initial_state: 'on'

  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0

  action:
    service: script.notify_text
    data_template:
      title: "HACS - Aggiornamento"
      message: "Sono disponibili aggiornamenti per i dispositivi Shelly"
      enable_persistant: true
