######################################################################
# Welcome message
# - greeting
# - disable away mode
######################################################################

- alias: Saluto di benvenuto
  trigger:
    - platform: state
      entity_id: 
        - device_tracker.google_maps_115265981849847357125
        - device_tracker.google_maps_103158638433668748797
      to: 'Casa'
      for: '00:00:30'

  condition: []

  action:
    - wait_template: >- 
        {# Giorgio #}
        {% if is_state_attr('trigger.to_state.entity_id', 'friendly_name', 'Giorgio') %}
          {% if is_state('device_tracker.s9', 'home') %}
            true
          {% else %}
            false
          {% endif %}

        {# Laura #}
        {% elif is_state_attr('trigger.to_state.entity_id', 'friendly_name', 'Laura') %}
          {% if is_state('device_tracker.a5', 'home') %}
            true
          {% else %}
            false
          {% endif %}

        {# Anna #}
        {% elif is_state_attr('trigger.to_state.entity_id', 'friendly_name', 'Anna') %}
          {% if is_state('device_tracker.a3', 'home') %}
            true
          {% else %}
            false
          {% endif %}

        {# Others #}
        {% else %}
          false
        {% endif %}

      timeout: '00:10:00'
      continue_on_timeout: 'false'

    - service: script.speech_engine
      data_template:
        language: 'it'
        message: >
          {% set name = trigger.to_state.entity_id.split('.')[1]|replace('_', ' ') %}
          {% set name = state_attr('trigger.to_state.entity_id', 'friendly_name') %}
          {%- macro greeting_sentence(name) -%}
          {{ [
          "Ciao " ~ name + " è un piacere rivederti a casa",
          "Finalmente a casa " ~ name + "!",
          "Indovina chi è a casa? " ~ name + "!",
          name + " è ora a casa!",
          "Che bello! " ~ name + " è a casa",
          name + " sei a casa!",
          "Il sistema di domotica Casa Ravera-Testa notifica che " ~ name + " è a casa!",
          "Annuncio: " ~ name + " è ora a casa!",
          "Rilevo una presenza! " ~ name + " è a casa!",
          "Ciao " ~ name + " che la forza sia con te",
          "Sento un tremito nella forza! " ~ name + " è a casa",
          "Sento un interferenza nella Forza! " ~ name + " è qui",
          "Menomale che sei qui " ~ name + "! Mi sentivo solo",
          "Menomale che sei qui " ~ name + "! La casa è vuota senza di te!",
          "Ciao " ~ name + "! Casa è sempre la casa!",
          ] | random }}
          {%- endmacro -%}
          {{ greeting_sentence(name) }}

    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.home_mode_away
