######################################################################
# Sony Bravia TV
######################################################################

- platform: braviatv
  host: tv.giorgioravera.it
  name: TV Sala
