######################################################################
# Device Tracker: Google Maps
######################################################################

- platform: google_maps
  username: !secret google_maps_username
  password: !secret google_maps_password

  # Seconds between each scan for new devices
  # interval_seconds: 60
  # Seconds to wait till marking someone as not home after not being seen
  # consider_home: 600
  new_device_defaults:
    track_new_devices: yes
    hide_if_away: false
