######################################################################
# Device Tracker: Nmap
######################################################################

- platform: nmap_tracker
  hosts:
    - s9.giorgioravera.it
    - a5.giorgioravera.it
    - a3.giorgioravera.it
  scan_options: " --privileged -sP "
  # The number of minutes Nmap will not scan this device
  home_interval: 30

  # Seconds between each scan for new devices
  interval_seconds: 60
  # Seconds to wait till marking someone as not home after not being seen
  consider_home: 300
  new_device_defaults:
    track_new_devices: true
    hide_if_away: false
