######################################################################
# Central Heating Package - Binary Sensor
######################################################################

binary_sensor:
  # Central Heating
  - platform: template
    sensors:
      central_heating:
        friendly_name: Riscaldamento Centralizzato
        value_template: >-
          {{ is_state('input_boolean.central_heating', 'on') }}
        icon_template: >-
          {% if is_state('input_boolean.central_heating', 'on') %}
              mdi:radiator
          {% else %}
              mdi:radiator-disabled
          {% endif %}

######################################################################
# Central Heating Package - Binary Sensor
######################################################################

input_boolean:
  # Central Heating
  central_heating:
    name: Riscaldamento Centralizzato
    icon: mdi:home-thermometer

######################################################################
# Central Heating    
######################################################################

automation:
  ######################################################################
  # Climate: Schedule according to Condominium
  # - script.turn_on
  ######################################################################
  - alias: "Riscaldamento Centralizzato"

    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: '00:00:00'
      - platform: state
        entity_id: input_boolean.central_heating
        to: 'on'
      - platform: state
        entity_id: input_boolean.central_heating
        to: 'off'

    condition: []

    action:
      - choose:
        # Switch on
        - conditions: "{{ now().month == 11 and now().day == 1 }}"
          sequence:
            - service: input_boolean.turn_on
              data_template:
                entity_id: input_boolean.central_heating
            - service: script.notify_text
              data_template:
                title: "Home Assistant - Riscaldamento Centralizzato"
                message: "Il riscaldamento centralizzato è stato acceso"
      
        # Switch off
        - conditions: "{{ now().month == 4 and now().day == 15 }}"
          sequence:
            - service: input_boolean.turn_on
              data_template:
                entity_id: input_boolean.central_heating
            - service: script.notify_text
              data_template:
                title: "Home Assistant - Riscaldamento Centralizzato"
                message: "Il riscaldamento centralizzato è stato spento"

######################################################################
# Netatmo Package - History
######################################################################

history:
  exclude:
    entities:
      - binary_sensor.central_heating

######################################################################
# Netatmo Package - Logbook
######################################################################
logbook:
  exclude:
    entities:
      - binary_sensor.central_heating

######################################################################
# Netatmo Package - Recorder
######################################################################
recorder:
  exclude:
    entities:
      - binary_sensor.central_heating
