######################################################################
# Central Heating Package - Binary Sensor
######################################################################

binary_sensor:
  - platform: template
    sensors:
      central_heating:
        friendly_name: Riscaldamento Centralizzato
        value_template: >-
          {{ is_state('input_boolean.central_heating', 'on') }}
        icon_template: >-
          {% if is_state('input_boolean.central_heating', 'on') %}
              mdi:radiator
          {% else %}
              mdi:radiator-disabled
          {% endif %}

######################################################################
# Central Heating Package - Input Boolean Sensor
######################################################################

input_boolean:
  central_heating:
    name: Riscaldamento Centralizzato
    icon: mdi:home-thermometer

######################################################################
# Central Heating - Automations
######################################################################

automation:
  ######################################################################
  # Climate: Schedule according to Condominium
  # - script.turn_on
  ######################################################################
  - alias: "Riscaldamento Centralizzato"

    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        at: '00:00:00'

    condition: []

    action:
      - choose:
        # Switch on
        - conditions: "{{ now().month == 11 and now().day == 1 and is_state('input_boolean.central_heating', 'off') }}"
          sequence:
            - service: input_boolean.turn_on
              data_template:
                entity_id: input_boolean.central_heating
            - service: script.notify_text
              data_template:
                title: "Home Assistant - Riscaldamento Centralizzato"
                message: "Il riscaldamento centralizzato è stato acceso"

        # Switch off
        - conditions: "{{ now().month == 4 and now().day == 15 and is_state('input_boolean.central_heating', 'on')}}"
          sequence:
            - service: input_boolean.turn_off
              data_template:
                entity_id: input_boolean.central_heating
            - service: script.notify_text
              data_template:
                title: "Home Assistant - Riscaldamento Centralizzato"
                message: "Il riscaldamento centralizzato è stato spento"

######################################################################
# Central Heating Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - binary_sensor.central_heating

######################################################################
# Central Heating Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - binary_sensor.central_heating
