######################################################################
# Errors Package - Binary Sensor
######################################################################

binary_sensor:
  - platform: template
    sensors:
      home_assistant_error:
        friendly_name: Errore Generale
        value_template: >-
          {{ is_state('input_boolean.home_assistant_error', 'on') }}
        icon_template: >-
          {% if is_state('input_boolean.home_assistant_error', 'on') %}
              mdi:alert-circle-outline
          {% else %}
              mdi:alert-circle-check-outline
          {% endif %}

######################################################################
# Errors Package - Input Boolean Sensor
######################################################################

input_boolean:
  home_assistant_error:
    name: Errore Generale
    icon: mdi:home-alert-outline

######################################################################
# Errors Package - Automations
######################################################################

automation:
  ######################################################################
  # Climate: Schedule according to Condominium
  # - script.turn_on
  ######################################################################
  - alias: "Errori Home Assistant: Insorgenza Errore"

    trigger:
    - event_data:
        domain: persistent_notification
        service: create
      event_type: call_service
      platform: event
    - event_data:
        domain: persistent_notification
        service: dimiss
      event_type: call_service
      platform: event

    condition: []

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.home_assistant_error

  ######################################################################
  # Climate: Schedule according to Condominium
  # - script.turn_on
  ######################################################################
  - alias: "Errori Home Assistant: Scomparsa Errore"

    trigger:
    - event_data:
        domain: persistent_notification
        service: create
      event_type: call_service
      platform: event
    - event_data:
        domain: persistent_notification
        service: dimiss
      event_type: call_service
      platform: event

    condition: []

    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.home_assistant_error

######################################################################
# Errors Package - History
######################################################################

history:
  exclude:
    entities:
      - binary_sensor.home_assistant_error

######################################################################
# Errors Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - binary_sensor.home_assistant_error

######################################################################
# Errors Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - binary_sensor.home_assistant_error
