######################################################################
# Errors Package - Customizations
######################################################################

homeassistant:
  customize:

    ######################################################################
    # Errors Package - Customizations - General Package Settings
    ######################################################################

    package.errors:
      customize: &customize
        package: 'errors'
        version: 1.0.0

    ######################################################################
    # Errors Package - Customizations - Entities
    ######################################################################

    binary_sensor.home_assistant_error:
      friendly_name: "Errore Generale"
      <<: *customize
    input_boolean.home_assistant_error:
      <<: *customize
    automation.home_assistant_errori_insorgenza_errore:
      <<: *customize
    automation.home_assistant_errori_scomparsa_errore:
      <<: *customize

######################################################################
# Errors Package - Binary Sensor
######################################################################

template:
  - binary_sensor:
      - name: "home_assistant_error"
        unique_id: home_assistant_error
        state: "{{ is_state('input_boolean.home_assistant_error', 'on') }}"
        device_class: problem
        icon: >
          {% if is_state('input_boolean.home_assistant_error', 'on') %}
            mdi:alert-circle-outline
          {% else %}
            mdi:alert-circle-check-outline
          {% endif %}

######################################################################
# Errors Package - Input Boolean Sensor
######################################################################

input_boolean:
  home_assistant_error:
    name: Errore Generale
    icon: mdi:home-alert-outline

######################################################################
# Errors Package - Automations
######################################################################

automation:

  ######################################################################
  # Error generation
  # - input_boolean.turn_on
  ######################################################################
  - alias: "Home Assistant - Errori: Insorgenza Errore"
    id: "home_assistant_errori_insorgenza_errore"

    trigger:
      - event_data:
          domain: persistent_notification
          service: create
        event_type: call_service
        trigger: event
      - event_data:
          domain: persistent_notification
          service: dimiss
        event_type: call_service
        trigger: event

    condition: []

    action:
      - action: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.home_assistant_error

  ######################################################################
  # Error removal
  # - input_boolean.turn_off
  ######################################################################
  - alias: "Home Assistant - Errori: Scomparsa Errore"
    id: "home_assistant_errori_scomparsa_errore"

    trigger:
      - event_data:
          domain: persistent_notification
          service: create
        event_type: call_service
        trigger: event
      - event_data:
          domain: persistent_notification
          service: dimiss
        event_type: call_service
        trigger: event

    condition: []

    action:
      - action: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.home_assistant_error

######################################################################
# Errors Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - binary_sensor.home_assistant_error

######################################################################
# Errors Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - binary_sensor.home_assistant_error
