######################################################################
# Guard Mode Package - Customizations
######################################################################

homeassistant:
  customize:

    ######################################################################
    # Guard Mode Package - Customizations - General Package Settings
    ######################################################################

    package.guard_mode:
      customize: &customize
        package: 'guard_mode'
        version: 1.1.0

    ######################################################################
    # Guard Mode Package - Customizations - Entities
    ######################################################################

    binary_sensor.guard_mode:
      friendly_name: Modalità Guardia
      <<: *customize
    input_boolean.guard_mode:
      <<: *customize
    automation.modalita_guardia_attivazione:
      <<: *customize
    automation.modalita_guardia_disattivazione:
      <<: *customize

######################################################################
# Guard Mode Package - Binary Sensor
######################################################################

template:
  - binary_sensor:
      - name: "guard_mode"
        unique_id: guard_mode
        state: "{{ is_state('input_boolean.guard_mode', 'on') }}"
        icon: >
          {% if is_state('input_boolean.guard_mode', 'on') %}
            mdi:shield-home
          {% else %}
            mdi:shield-off
          {% endif %}

######################################################################
# Guard Mode Package - Input Booleans
######################################################################

input_boolean:
  # Guard Mode
  guard_mode:
    name: Modalità Guardia
    icon: mdi:shield-home

######################################################################
# Guard Mode Package - Automations
######################################################################

automation:

  ######################################################################
  # Guard Mode: Enable
  ######################################################################
  - alias: "Modalità Guardia: Attivazione"
    id: "modalita_guardia_attivazione"

    trigger:
      - trigger: state
        entity_id: group.residents
        from: 'home'
      - trigger: homeassistant
        event: start

    condition: "{{ not is_state('group.residents', 'home') }}"

    action:
      - action: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.guard_mode

  ######################################################################
  # Guard Mode: Disable
  ######################################################################
  - alias: "Modalità Guardia: Disattivazione"
    id: "modalita_guardia_disattivazione"

    trigger:
      - trigger: state
        entity_id: group.residents
        to: 'home'
      - trigger: homeassistant
        event: start

    condition: "{{ is_state('group.residents', 'home') }}"

    action:
      - action: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.guard_mode
