######################################################################
# Proxmox Package: Customizations
######################################################################

homeassistant:
  customize:
    binary_sensor.pve_server:
        friendly_name: VM Server
        icon: mdi:debian

    binary_sensor.pve_docker:
        friendly_name: VM Docker
        icon: mdi:docker

    binary_sensor.pve_firewall:
        friendly_name: VM Firewall
        icon: mdi:freebsd

    binary_sensor.pve_asterisk:
        friendly_name: VM Asterisk
        icon: mdi:asterisk-circle-outline

######################################################################
# Proxmox Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - binary_sensor.pve_server
      - binary_sensor.pve_docker
      - binary_sensor.pve_firewall
      - binary_sensor.pve_asterisk

######################################################################
# Proxmox Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - binary_sensor.pve_server
      - binary_sensor.pve_docker
      - binary_sensor.pve_firewall
      - binary_sensor.pve_asterisk
