######################################################################
# QNAP Package - Customizations
######################################################################

homeassistant:
  customize:

    ######################################################################
    # QNAP Package - Customizations - General Package Settings
    ######################################################################

    package.qnap:
      customize: &customize
        package: 'qnap'
        version: 1.0.0

    ######################################################################
    # QNAP Package - Customizations - Entities
    ######################################################################

    switch.nas:
      <<: *customize
      icon: mdi:nas
    shell_command.nas_turn_off:
      <<: *customize
      icon: mdi:power-settings
    shell_command.plex_start:
      <<: *customize
      icon: mdi:plex
    shell_command.plex_restart:
      <<: *customize
      icon: mdi:plex
    shell_command.plex_stop:
      <<: *customize
      icon: mdi:plex
    script.plex_start:
      <<: *customize
      icon: mdi:plex
    script.plex_restart:
      <<: *customize
      icon: mdi:plex
    script.plex_stop:
      <<: *customize
      icon: mdi:plex

######################################################################
# QNAP Package - Switch
######################################################################

switch:
  - platform: wake_on_lan
    mac: !secret nas_mac
    name: NAS
    host: !secret nas_host
    turn_off:
      action: shell_command.nas_turn_off
      data:
        nas_host: !secret nas_host
        nas_username: !secret nas_username

######################################################################
# QNAP Package - Shell Command
######################################################################

shell_command:
  nas_turn_off: 'ssh {{ nas_username }}@{{ nas_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_ed25519 /sbin/poweroff'
  plex_start: 'ssh {{ nas_username }}@{{ nas_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_ed25519  /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/plex.sh start'
  plex_restart: 'ssh {{ nas_username }}@{{ nas_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_ed25519  /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/plex.sh restart'
  plex_stop: 'ssh {{ nas_username }}@{{ nas_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_ed25519  /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/plex.sh stop'

######################################################################
# QNAP Package - Script
######################################################################

script:
  plex_start:
    alias: "Avvia Plex"
    sequence:
      - action: shell_command.plex_start
        data:
          nas_host: !secret nas_host
          nas_username: !secret nas_username

  plex_restart:
    alias: "Riavvia Plex"
    sequence:
      - action: shell_command.plex_restart
        data:
          nas_host: !secret nas_host
          nas_username: !secret nas_username

  plex_stop:
    alias: "Ferma Plex"
    sequence:
      - action: shell_command.plex_stop
        data:
          nas_host: !secret nas_host
          nas_username: !secret nas_username

######################################################################
# QNAP Package - Google Assistant
######################################################################

google_assistant:
  entity_config:
    switch.nas:
      name: NAS
      expose: true
      room: Studio
    script.plex_start:
      name: Avvia Plex
      expose: true
      room: Routine
    script.plex_stop:
      name: Ferma Plex
      expose: true
      room: Routine
