######################################################################
# Zigbee2mqtt Package - Customizations
######################################################################

homeassistant:
  customize:

    ######################################################################
    # Zigbee2mqtt Package - Customizations - General Package Settings
    ######################################################################

    package.zigbee2mqtt:
      customize: &customize
        package: 'zigbee2mqtt'
        version: 1.2.0

    ######################################################################
    # Zigbee2mqtt Package - Customizations - Entities
    ######################################################################

    binary_sensor.zigbee2mqtt_bridge_connection_state:
      friendly_name: "Stato bridge"
    binary_sensor.zigbee2mqtt_bridge_restart_required:
      friendly_name: "Richiesto riavvio"
    button.zigbee2mqtt_bridge_restart:
      friendly_name: "Riavvia bridge"
    input_number.zigbee2mqtt_join_minutes:
      friendly_name: "Tempo di join"
      <<: *customize
    input_text.zigbee2mqtt_old_name:
      friendly_name: "Dispositivo da rinominare"
      <<: *customize
    input_text.zigbee2mqtt_new_name:
      friendly_name: "Nome nuovo del dispositivo"
      <<: *customize
    input_text.zigbee2mqtt_remove:
      friendly_name: "Dispositivo da rimuovere"
      <<: *customize
    input_boolean.zigbee2mqtt_force_remove:
      friendly_name: "Rimozione forzata"
      <<: *customize
    select.zigbee2mqtt_bridge_log_level:
      friendly_name: "Log level"
    script.zigbee2mqtt_rename:
      friendly_name: "Rinomina dispositivo"
      <<: *customize
    script.zigbee2mqtt_remove:
      friendly_name: "Rimuovi dispositivo"
      <<: *customize
    sensor.zigbee2mqtt_bridge_channel:
      friendly_name: "Canale"
      <<: *customize
    sensor.zigbee2mqtt_bridge_coordinator_type:
      friendly_name: "Tipo Coordinator"
      <<: *customize
    sensor.zigbee2mqtt_bridge_coordinator_version:
      friendly_name: "Versione Coordinator"
    sensor.zigbee2mqtt_bridge_network_map:
      friendly_name: "Mappa della rete Zigbee"
    sensor.zigbee2mqtt_bridge_panid:
      friendly_name: "PanID"
      <<: *customize
    #sensor.zigbee2mqtt_bridge_permit_join:
    #  friendly_name: "Stato permesso join"
    #  <<: *customize
    sensor.zigbee2mqtt_bridge_permit_join_timeout:
      friendly_name: "Tempo rimasto per il join (bridge)"
    sensor.zigbee2mqtt_bridge_version:
      friendly_name: "Versione bridge"
    shell_command.zigbee2mqtt_restart:
      friendly_name: "Riavvia bridge"
      <<: *customize
    switch.zigbee2mqtt_bridge_permit_join:
      friendly_name: "Permetti join"
    timer.zigbee_permit_join:
      friendly_name: "Tempo rimasto per il join (hass)"
      <<: *customize
    automation.zigbee2mqtt_abilita_join:
      <<: *customize
    automation.zigbee2mqtt_disabilita_join:
      <<: *customize
    automation.zigbee2mqtt_device_aggiunto_alla_rete_zigbee2mqtt:
      <<: *customize
    automation.zigbee2mqtt_restart_automation:
      <<: *customize

######################################################################
# Zigbee2mqtt Package - Input Number
######################################################################

# Input number for joining time remaining (in minutes)
input_number:
  zigbee2mqtt_join_minutes:
    name: "Zigbee2MQTT: Tempo per il join"
    initial: 2
    min: 1
    max: 5
    step: 1
    mode: slider

######################################################################
# Zigbee2mqtt Package - Input Text
######################################################################

input_text:
  zigbee2mqtt_old_name:
    name: "Device da Rinominare"
    initial: ""

  zigbee2mqtt_new_name:
    name: "Nuovo nome Device"
    initial: ""

  zigbee2mqtt_remove:
    name: "Device da Rimuovere"
    initial: ""

######################################################################
# Zigbee2mqtt Package - Input boolean
######################################################################

input_boolean:
  zigbee2mqtt_force_remove:
    name: "Zigbee2MQTT: Rimozione Forzata"
    initial: false
    icon: mdi:alert-remove

######################################################################
# Zigbee2mqtt Package - Script
######################################################################

script:
  ######################################################################
  # Rename Device
  ######################################################################
  zigbee2mqtt_rename:
    alias: "Zigbee2MQTT: Rinomina Device"
    sequence:
      action: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/request/device/rename
        payload_template: >-
          {
            "from": "{{ states.input_text.zigbee2mqtt_old_name.state | string }}",
            "to": "{{ states.input_text.zigbee2mqtt_new_name.state | string }}"
          }
    icon: mdi:form-textbox

  ######################################################################
  # Delete Device
  ######################################################################
  zigbee2mqtt_remove:
    alias: "Zigbee2MQTT: Rimuovi Device"
    sequence:
      action: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/request/device/remove
        payload_template: >-
          {
            "id": "{{ states.input_text.zigbee2mqtt_remove.state | string }}",
            "force": {% if states.input_boolean.zigbee2mqtt_force_remove.state == "off" %}false{% else %}true{% endif %}
          }
    icon: mdi:link-variant-remove

######################################################################
# Zigbee2mqtt Package - Timer
######################################################################

timer:
  # Timer for joining time remaining (120 sec = 2 min)
  zigbee_permit_join:
    name: Tempo rimasto per il join
    duration: 120

######################################################################
# Zigbee2mqtt Package - Sensor
######################################################################

mqtt:
  sensor:
    ######################################################################
    # MQTT Sensor for Showing the Coordinator Type
    ######################################################################
    - name: "Zigbee2MQTT Bridge Coordinator Type"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.coordinator.type }}"
      icon: mdi:chip

    ######################################################################
    # MQTT Sensor for monitoring the permit_join state
    ######################################################################
    #- name: "Zigbee2MQTT Bridge Permit Join"
    #  state_topic: "zigbee2mqtt/bridge/info"
    #  value_template: "{{ value_json.permit_join }}"
    #  icon: mdi:link-lock

    ######################################################################
    # MQTT Sensor for Showing the Channel
    ######################################################################
    - name: "Zigbee2MQTT Bridge Channel"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.network.channel }}"
      icon: mdi:access-point-network

    ######################################################################
    # MQTT Sensor for Showing the PanID
    ######################################################################
    - name: "Zigbee2MQTT Bridge PanID"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.network.pan_id }}"
      icon: mdi:lan

######################################################################
# Zigbee2mqtt Package - Shell Command
######################################################################

shell_command:
  zigbee2mqtt_restart: 'ssh {{ docker_username }}@{{ docker_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_rsa docker container restart zigbee2mqtt'

######################################################################
# Zigbee2mqtt Package - Automation
######################################################################

automation:
  ######################################################################
  # Automation to start timer when enable join is turned on
  ######################################################################
  - alias: "Zigbee2MQTT: Abilita Join"
    id: "zigbee2mqtt_abilita_join"
    trigger:
      trigger: state
      entity_id: switch.zigbee2mqtt_bridge_permit_join
      to: "on"
    action:
      action: timer.start
      entity_id: timer.zigbee_permit_join
      data_template:
        duration: "{{ '00:0%i:00' % (states('input_number.zigbee2mqtt_join_minutes') | int ) }}"

  ######################################################################
  # Automation to stop timer when switch turned off and turn off switch when timer finished
  ######################################################################
  - alias: "Zigbee2MQTT: Disabilita Join"
    id: "zigbee2mqtt_disabilita_join"
    trigger:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
      - trigger: state
        entity_id: switch.zigbee2mqtt_bridge_permit_join
        to: "off"
    action:
      - action: timer.cancel
        data:
          entity_id: timer.zigbee_permit_join
      - action: switch.turn_off
        entity_id: switch.zigbee2mqtt_bridge_permit_join

  ######################################################################
  # Automation to notify when a device joined zigbee2mqtt network
  ######################################################################
  - alias: "Zigbee2MQTT: Device aggiunto alla rete Zigbee2mqtt"
    id: "zigbee2mqtt_device_aggiunto_alla_rete_zigbee2mqtt"
    trigger:
      trigger: mqtt
      topic: 'zigbee2mqtt/bridge/event'
    condition:
      condition: template
      value_template: '{{trigger.payload_json.type == "device_interview" and trigger.payload_json.data.status == "successful" and trigger.payload_json.data.supported}}'
    action:
      - action: persistent_notification.create
        data_template:
          title: "Device aggiunto alla rete Zigbee2mqtt"
          message: "Name: {{trigger.payload_json.data.friendly_name}},
                    Vendor: {{trigger.payload_json.data.definition.vendor}},
                    Model: {{trigger.payload_json.data.definition.model}},
                    Description: {{trigger.payload_json.data.definition.description}}"

  ######################################################################
  # Automation to restart zigbee2mqtt (startup or bridge offline for 1m)
  ######################################################################
  - alias: "Zigbee2MQTT: Restart Automation"
    id: "zigbee2mqtt_restart_automation"
    trigger:
      - trigger: homeassistant
        event: start
      - trigger: state
        entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
        to: "off"
        for: "00:01:00"
    action:
      - action: shell_command.zigbee2mqtt_restart
        data:
          docker_host: !secret docker_host
          docker_username: !secret docker_username

######################################################################
# Zigbee2mqtt Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - binary_sensor.zigbee2mqtt_bridge_connection_state
      - select.zigbee2mqtt_bridge_log_level
      - sensor.zigbee2mqtt_bridge_permit_join
      - sensor.zigbee2mqtt_bridge_permit_join_timeout
      - sensor.zigbee2mqtt_bridge_version
      - sensor.zigbee2mqtt_bridge_coordinator_version
      - sensor.zigbee2mqtt_bridge_coordinator_type
      - sensor.zigbee2mqtt_bridge_channel
      - sensor.zigbee2mqtt_bridge_panid
      - sensor.zigbee2mqtt_bridge_network_map
      - timer.zigbee_permit_join

######################################################################
# Zigbee2mqtt Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - binary_sensor.zigbee2mqtt_bridge_connection_state
      - select.zigbee2mqtt_bridge_log_level
      - sensor.zigbee2mqtt_bridge_permit_join
      - sensor.zigbee2mqtt_bridge_permit_join_timeout
      - sensor.zigbee2mqtt_bridge_version
      - sensor.zigbee2mqtt_bridge_coordinator_version
      - sensor.zigbee2mqtt_bridge_coordinator_type
      - sensor.zigbee2mqtt_bridge_channel
      - sensor.zigbee2mqtt_bridge_panid
      - sensor.zigbee2mqtt_bridge_network_map
      - timer.zigbee_permit_join
