######################################################################
# Zigbee2mqtt Package - Sensor
######################################################################

sensor:
  ######################################################################
  # Sensor for monitoring the bridge state
  ######################################################################
  - platform: mqtt
    name: "Zigbee2mqtt: Stato Bridge"
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless

  ######################################################################
  # Sensor for monitoring the permit_join state
  ######################################################################
  - platform: mqtt
    name: "Zigbee2mqtt: Stato permit join"
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.permit_join }}"
    icon: mdi:link-lock
    
  ######################################################################
  # Sensor for monitoring the log_level state
  ######################################################################
  - platform: mqtt
    name: "Zigbee2mqtt: Stato log level"
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.log_level }}"
    icon: mdi:file-document-outline

  ######################################################################
  # Sensor for Showing the Zigbee2mqtt Version
  ######################################################################
  - platform: mqtt
    name: "Zigbee2mqtt: Versione Bridge"
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.version }}"
    icon: mdi:zigbee

  ######################################################################
  # Sensor for Showing the Coordinator Version
  ######################################################################
  - platform: mqtt
    name: "Zigbee2mqtt: Versione Coordinator"
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator.meta.revision }}"
    icon: mdi:chip

  ######################################################################
  # Sensor for Showing the new Zigbee2mqtt Version
  ######################################################################
  #  - platform: command_line
  #    name: "Zigbee2mqtt: nuova versione disponibile"
  #    command: 'curl https://api.github.com/repos/Koenkk/zigbee2mqtt/releases/latest'
  #    scan_interval: 3600
  #    value_template: '{{ value_json.tag_name }}'
  #    #icon: mdi:folder-download

  ######################################################################
  # Zigbee2mqtt Networkmap
  ######################################################################
  - platform: mqtt
    name: "Zigbee2mqtt: Networkmap"
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

######################################################################
# Zigbee2mqtt Package - Switch
######################################################################

switch:
  # Switch for enabling joining 
  - platform: mqtt
    name: "Zigbee2mqtt: Abilita join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

######################################################################
# Zigbee2mqtt Package - Input select
######################################################################

input_select:
  # Zigbee2mqtt log level
  zigbee2mqtt_log_level:
    name: "Zigbee2mqtt Log Level"
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted
    
######################################################################
# Zigbee2mqtt Package - Input Text
######################################################################

input_text:
  zigbee2mqtt_old_name:
    name: "Device da Rinominare"

  zigbee2mqtt_new_name:
    name: "Nuovo nome Device"

  zigbee2mqtt_remove:
    name: "Device da Rimuovere"

######################################################################
# Zigbee2mqtt Package - Timer
######################################################################

timer:
  # Timer for joining time remaining (120 sec = 2 min)
  zigbee_permit_join:
    name: Tempo rimasto per il join
    duration: 120

######################################################################
# Zigbee2mqtt Package - Shell Command
######################################################################

shell_command:
  zigbee2mqtt_restart: 'ssh {{ docker_username }}@{{ docker_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_rsa docker container restart zigbee2mqtt'

######################################################################
# Zigbee2mqtt Package - Script
######################################################################

script:
  ######################################################################
  # Restart Bridge
  ######################################################################
  zigbee2mqtt_restart:
    alias: "Zigbee2mqtt: Riavvia Bridge"
    sequence:
      - service: shell_command.zigbee2mqtt_restart
        data:
          docker_host: !secret docker_host
          docker_username: !secret docker_username

  ######################################################################
  # Rename Device
  ######################################################################
  zigbee2mqtt_rename:
    alias: "Zigbee2mqtt: Rinomina Device"
    sequence:
      service: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/config/rename
        payload_template: >-
          {
            "old": "{{ states.input_text.zigbee2mqtt_old_name.state | string }}",
            "new": "{{ states.input_text.zigbee2mqtt_new_name.state | string }}"
          }

  ######################################################################
  # Delete Device
  ######################################################################
  zigbee2mqtt_remove:
    alias: "Zigbee2mqtt: Rimuovi Device"
    sequence:
      service: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/config/remove
        payload_template: "{{ states.input_text.zigbee2mqtt_remove.state | string }}"


######################################################################
# Zigbee2mqtt Package - Automation
######################################################################

automation:
  ######################################################################
  # Automation to change log level
  ######################################################################
  - id: zigbee2mqtt_change_log_level
    alias: "Zigbee2mqtt: Cambia Log Level"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: input_select.zigbee2mqtt_log_level
    action:
      - service: mqtt.publish
        data:
          payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
          topic: zigbee2mqtt/bridge/config/log_level

  ######################################################################
  # Automation to start timer when enable join is turned on
  ######################################################################
  - id: zigbee2mqtt_join_enabled
    alias: "Zigbee2mqtt: Abilita Join"
    initial_state: "on"
    trigger:
      platform: state
      entity_id: switch.Zigbee2mqtt_Abilita_join
      to: "on"
    action:
      service: timer.start
      entity_id: timer.zigbee_permit_join

  ######################################################################
  # Automation to stop timer when switch turned off and turn off switch when timer finished
  ######################################################################
  - id: zigbee2mqtt_join_disabled
    alias: "Zigbee2mqtt: Disabilita Join"
    initial_state: "on"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
      - platform: state
        entity_id: switch.Zigbee2mqtt_Abilita_join
        to: "off"
    action:
      - service: timer.cancel
        data:
          entity_id: timer.zigbee_permit_join
      - service: switch.turn_off
        entity_id: switch.Zigbee2mqtt_Abilita_join

  ######################################################################
  # Automation to restart zigbee2mqtt to refresh sensor state
  ######################################################################
  - id: zigbee2mqtt_startup_automation
    alias: "Zigbee2mqtt: Startup Automation"
    initial_state: "on"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.zigbee2mqtt_restart

######################################################################
# Zigbee2mqtt Package - History
######################################################################

history:
  exclude:
    entities:
      - sensor.zigbee2mqtt_stato_bridge
      - sensor.zigbee2mqtt_stato_permit_join
      - sensor.zigbee2mqtt_stato_log_level
      - sensor.zigbee2mqtt_versione_bridge
      - sensor.zigbee2mqtt_versione_coordinator
      #- sensor.zigbee2mqtt_nuova_versione_disponibile
      - sensor.zigbee2mqtt_networkmap
      - timer.zigbee_permit_join

######################################################################
# Zigbee2mqtt Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - sensor.zigbee2mqtt_stato_bridge
      - sensor.zigbee2mqtt_stato_permit_join
      - sensor.zigbee2mqtt_stato_log_level
      - sensor.zigbee2mqtt_versione_bridge
      - sensor.zigbee2mqtt_versione_coordinator
      #- sensor.zigbee2mqtt_nuova_versione_disponibile
      - sensor.zigbee2mqtt_networkmap
      - timer.zigbee_permit_join

######################################################################
# Zigbee2mqtt Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - sensor.zigbee2mqtt_stato_bridge
      - sensor.zigbee2mqtt_stato_permit_join
      - sensor.zigbee2mqtt_stato_log_level
      - sensor.zigbee2mqtt_versione_bridge
      - sensor.zigbee2mqtt_versione_coordinator
      #- sensor.zigbee2mqtt_nuova_versione_disponibile
      - sensor.zigbee2mqtt_networkmap
      - timer.zigbee_permit_join
