######################################################################
# Zigbee2mqtt Package - Input select
######################################################################

input_select:
  # Zigbee2mqtt log level
  zigbee2mqtt_log_level:
    name: "Zigbee2MQTT: Log Level"
    options:
      - debug
      - info
      - warn
      - error
    initial: info
    icon: mdi:format-list-bulleted

######################################################################
# Zigbee2mqtt Package - Input Number
######################################################################

# Input number for joining time remaining (in minutes)
input_number:
  zigbee2mqtt_join_minutes:
    name: "Zigbee2MQTT: Tempo per il join"
    initial: 2
    min: 1
    max: 5
    step: 1
    mode: slider

######################################################################
# Zigbee2mqtt Package - Input Text
######################################################################

input_text:
  zigbee2mqtt_old_name:
    name: "Device da Rinominare"
    initial: ""

  zigbee2mqtt_new_name:
    name: "Nuovo nome Device"
    initial: ""

  zigbee2mqtt_remove:
    name: "Device da Rimuovere"
    initial: ""

######################################################################
# Zigbee2mqtt Package - Input boolean
######################################################################

input_boolean:
  zigbee2mqtt_force_remove:
    name: "Zigbee2MQTT: Rimozione Forzata"
    initial: false
    icon: mdi:alert-remove

######################################################################
# Zigbee2mqtt Package - Script
######################################################################

script:
  ######################################################################
  # Restart Bridge
  ######################################################################
  zigbee2mqtt_restart:
    alias: "Zigbee2MQTT: Riavvia Bridge"
    sequence:
      - service: shell_command.zigbee2mqtt_restart
        data:
          docker_host: !secret docker_host
          docker_username: !secret docker_username
    icon: mdi:restart

  ######################################################################
  # Rename Device
  ######################################################################
  zigbee2mqtt_rename:
    alias: "Zigbee2MQTT: Rinomina Device"
    sequence:
      service: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/request/device/rename
        payload_template: >-
          {
            "from": "{{ states.input_text.zigbee2mqtt_old_name.state | string }}",
            "to": "{{ states.input_text.zigbee2mqtt_new_name.state | string }}"
          }
    icon: mdi:form-textbox

  ######################################################################
  # Delete Device
  ######################################################################
  zigbee2mqtt_remove:
    alias: "Zigbee2MQTT: Rimuovi Device"
    sequence:
      service: mqtt.publish
      data_template:
        topic: zigbee2mqtt/bridge/request/device/remove
        payload_template: >-
          {
            "id": "{{ states.input_text.zigbee2mqtt_remove.state | string }}",
            "force": {% if states.input_boolean.zigbee2mqtt_force_remove.state == "off" %}false{% else %}true{% endif %}
          }
    icon: mdi:link-variant-remove

######################################################################
# Zigbee2mqtt Package - Timer
######################################################################

timer:
  # Timer for joining time remaining (120 sec = 2 min)
  zigbee_permit_join:
    name: Tempo rimasto per il join
    duration: 120

######################################################################
# Zigbee2mqtt Package - Sensor
######################################################################

mqtt:
  sensor:
    ######################################################################
    # MQTT Sensor for monitoring the bridge state
    ######################################################################
    - name: "Zigbee2MQTT: Stato Bridge"
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless

    ######################################################################
    # MQTT Sensor for Showing the Zigbee2MQTT Version
    ######################################################################
    - name: "Zigbee2MQTT: Versione Bridge"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.version }}"
      icon: mdi:zigbee

    ######################################################################
    # MQTT Sensor for Showing the Coordinator Type
    ######################################################################
    #- name: "Zigbee2MQTT: Tipo Coordinator"
    #  state_topic: "zigbee2mqtt/bridge/info"
    #  value_template: "{{ value_json.coordinator.type }}"
    #  icon: mdi:chip

    ######################################################################
    # MQTT Sensor for Showing the Coordinator Version
    ######################################################################
    - name: "Zigbee2MQTT: Versione Coordinator"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.coordinator.meta.revision }}"
      icon: mdi:chip

    ######################################################################
    # MQTT Sensor for monitoring the permit_join state
    ######################################################################
    - name: "Zigbee2MQTT: Stato permit join"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.permit_join }}"
      icon: mdi:link-lock

    ######################################################################
    # MQTT Sensor for monitoring the log_level state
    ######################################################################
    - name: "Zigbee2MQTT: Stato log level"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.log_level }}"
      icon: mdi:file-document-outline

    ######################################################################
    # MQTT Sensor for Showing the Channel
    ######################################################################
    - name: "Zigbee2MQTT: Canale"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.network.channel }}"
      icon: mdi:access-point-network

    ######################################################################
    # MQTT Sensor for Showing the PanID
    ######################################################################
    - name: "Zigbee2MQTT: PanID"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: "{{ value_json.network.pan_id }}"
      icon: mdi:lan

    ######################################################################
    # MQTT Sensor for Showing the Extended PanID
    ######################################################################
    #- name: "Zigbee2mqtt: Extended PanID"
    #  state_topic: "zigbee2mqtt/bridge/info"
    #  value_template: "{{ value_json.network.extended_pan_id }}"
    #  icon: mdi:lan

    ######################################################################
    # Zigbee2mqtt Networkmap
    ######################################################################
    - name: Zigbee2MQTT Networkmap
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: >-
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: "{{ value_json.data.value | tojson }}"

  ######################################################################
  # Zigbee2mqtt Package - Switch
  ######################################################################
  switch:
    # Switch for enabling joining
    - name: "Zigbee2MQTT: Abilita join"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: '{{ value_json.permit_join | lower }}'
      command_topic: "zigbee2mqtt/bridge/request/permit_join"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:link-lock

######################################################################
# Zigbee2mqtt Package - Shell Command
######################################################################

shell_command:
  zigbee2mqtt_restart: 'ssh {{ docker_username }}@{{ docker_host }} -oStrictHostKeyChecking=no -i /config/credentials/id_rsa docker container restart zigbee2mqtt'

######################################################################
# Zigbee2mqtt Package - Automation
######################################################################

automation:
  ######################################################################
  # Automation to change log level
  ######################################################################
  - id: zigbee2mqtt_change_log_level
    alias: "Zigbee2MQTT: Cambia Log Level"
    trigger:
      platform: state
      entity_id: input_select.zigbee2mqtt_log_level
    action:
      - service: mqtt.publish
        data:
          payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
          topic: zigbee2mqtt/bridge/request/config/log_level

  ######################################################################
  # Automation to start timer when enable join is turned on
  ######################################################################
  - id: zigbee2mqtt_join_enabled
    alias: "Zigbee2MQTT: Abilita Join"
    trigger:
      platform: state
      entity_id: switch.zigbee2mqtt_abilita_join
      to: "on"
    action:
      service: timer.start
      entity_id: timer.zigbee_permit_join
      data_template:
        duration: "{{ '00:0%i:00' % (states('input_number.zigbee2mqtt_join_minutes') | int ) }}"

  ######################################################################
  # Automation to stop timer when switch turned off and turn off switch when timer finished
  ######################################################################
  - id: zigbee2mqtt_join_disabled
    alias: "Zigbee2MQTT: Disabilita Join"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
      - platform: state
        entity_id: switch.zigbee2mqtt_abilita_join
        to: "off"
    action:
      - service: timer.cancel
        data:
          entity_id: timer.zigbee_permit_join
      - service: switch.turn_off
        entity_id: switch.zigbee2mqtt_abilita_join

  ######################################################################
  # Automation to notify when a device joined zigbee2mqtt network
  ######################################################################
  - id: "zigbee2mqtt_notification_on_successfull_interview"
    alias: "Zigbee2MQTT: Device aggiunto alla rete Zigbee2mqtt"
    trigger:
      platform: mqtt
      topic: 'zigbee2mqtt/bridge/event'
    condition:
      condition: template
      value_template: '{{trigger.payload_json.type == "device_interview" and trigger.payload_json.data.status == "successful" and trigger.payload_json.data.supported}}'
    action:
      - service: persistent_notification.create
        data_template:
          title: "Device aggiunto alla rete Zigbee2mqtt"
          message: "Name: {{trigger.payload_json.data.friendly_name}},
                    Vendor: {{trigger.payload_json.data.definition.vendor}},
                    Model: {{trigger.payload_json.data.definition.model}},
                    Description: {{trigger.payload_json.data.definition.description}}"

  ######################################################################
  # Automation to restart zigbee2mqtt to refresh sensor state
  ######################################################################
  - id: zigbee2mqtt_startup_automation
    alias: "Zigbee2MQTT: Startup Automation"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.zigbee2mqtt_restart

  ######################################################################
  # Automation to restart zigbee2mqtt in case of bridge offline for 1m
  ######################################################################
  - id: zigbee2mqtt_restart_automation
    alias: "Zigbee2MQTT: Restart Automation"
    trigger:
      - platform: state
        entity_id: sensor.zigbee2mqtt_stato_bridge
        to: "offline"
        for: "00:01:00"
    action:
      - service: script.zigbee2mqtt_restart
      - service: script.notify_text
        data:
          title: "Restart Zigbee2mqtt"
          message: "Zigbee2mqtt bridge offline: force restart"

######################################################################
# Zigbee2mqtt Package - Logbook
######################################################################

logbook:
  exclude:
    entities:
      - sensor.zigbee2mqtt_stato_bridge
      - sensor.zigbee2mqtt_stato_permit_join
      - sensor.zigbee2mqtt_stato_log_level
      - sensor.zigbee2mqtt_versione_bridge
      - sensor.zigbee2mqtt_versione_coordinator
      - sensor.zigbee2mqtt_tipo_coordinator
      - sensor.zigbee2mqtt_canale
      - sensor.zigbee2mqtt_panid
      - sensor.zigbee2mqtt_extended_panid
      - sensor.zigbee2mqtt_networkmap
      - timer.zigbee_permit_join

######################################################################
# Zigbee2mqtt Package - Recorder
######################################################################

recorder:
  exclude:
    entities:
      - sensor.zigbee2mqtt_stato_bridge
      - sensor.zigbee2mqtt_stato_permit_join
      - sensor.zigbee2mqtt_stato_log_level
      - sensor.zigbee2mqtt_versione_bridge
      - sensor.zigbee2mqtt_versione_coordinator
      - sensor.zigbee2mqtt_tipo_coordinator
      - sensor.zigbee2mqtt_canale
      - sensor.zigbee2mqtt_panid
      - sensor.zigbee2mqtt_extended_panid
      - sensor.zigbee2mqtt_networkmap
      - timer.zigbee_permit_join
