######################################################################
# Shelly Package - Customization
######################################################################

homeassistant:
  customize:

    # Shelly 1 - Tapparella Cucina (shellyswitch_55980f)
    sensor.tapparella_cucina_energy:
      friendly_name: Energia
    sensor.tapparella_cucina_power:
      friendly_name: Potenza
    binary_sensor.tapparella_cucina_channel_1_input:
      friendly_name: Pulsante 1
    binary_sensor.tapparella_cucina_channel_2_input:
      friendly_name: Pulsante 2
    binary_sensor.tapparella_cucina_cloud:
      friendly_name: Connessione Cloud
    update.tapparella_cucina_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.tapparella_cucina_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.tapparella_cucina_rssi:
      friendly_name: Potenza Segnale
    sensor.tapparella_cucina_uptime:
      friendly_name: Uptime
    button.tapparella_cucina_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 2 - Tapparella Sala (shellyswitch25_6919bd)
    sensor.tapparella_sala_energy:
      friendly_name: Energia
    sensor.tapparella_sala_power:
      friendly_name: Potenza
    binary_sensor.tapparella_sala_channel_1_input:
      friendly_name: Pulsante 1
    binary_sensor.tapparella_sala_channel_2_input:
      friendly_name: Pulsante 2
    binary_sensor.tapparella_sala_cloud:
      friendly_name: Connessione Cloud
    sensor.tapparella_sala_device_temperature:
      friendly_name: Temperatura Device
    binary_sensor.tapparella_sala_overheating:
      friendly_name: Surriscaldamento Device
    update.tapparella_sala_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.tapparella_sala_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.tapparella_sala_rssi:
      friendly_name: Potenza Segnale
    sensor.tapparella_sala_uptime:
      friendly_name: Uptime
    button.tapparella_sala_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 3 - Tapparella Studio (shellyswitch_13572b)
    sensor.tapparella_studio_energy:
      friendly_name: Energia
    sensor.tapparella_studio_power:
      friendly_name: Potenza
    binary_sensor.tapparella_studio_channel_1_input:
      friendly_name: Pulsante 1
    binary_sensor.tapparella_studio_channel_2_input:
      friendly_name: Pulsante 2
    binary_sensor.tapparella_studio_cloud:
      friendly_name: Connessione Cloud
    update.tapparella_studio_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.tapparella_studio_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.tapparella_studio_rssi:
      friendly_name: Potenza Segnale
    sensor.tapparella_studio_uptime:
      friendly_name: Uptime
    button.tapparella_studio_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 4 - Tapparella Camera (shellyswitch_559c49)
    sensor.tapparella_camera_energy:
      friendly_name: Energia
    sensor.tapparella_camera_power:
      friendly_name: Potenza
    binary_sensor.tapparella_camera_channel_1_input:
      friendly_name: Pulsante 1
    binary_sensor.tapparella_camera_channel_2_input:
      friendly_name: Pulsante 2
    binary_sensor.tapparella_camera_cloud:
      friendly_name: Connessione Cloud
    update.tapparella_camera_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.tapparella_camera_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.tapparella_camera_rssi:
      friendly_name: Potenza Segnale
    sensor.tapparella_camera_uptime:
      friendly_name: Uptime
    button.tapparella_camera_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 5 - Luce Corridoio (shelly1_24d1ee)
    binary_sensor.luce_corridoio_cloud:
      friendly_name: Connessione Cloud
    update.luce_corridoio_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_corridoio_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_corridoio_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_corridoio_uptime:
      friendly_name: Uptime
    button.luce_corridoio_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 6 - Luce Cucina (shelly1_93B27D)
    binary_sensor.luce_cucina_cloud:
      friendly_name: Connessione Cloud
    update.luce_cucina_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_cucina_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_cucina_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_cucina_uptime:
      friendly_name: Uptime
    button.luce_cucina_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 7 - Luce Sala (shellydimmer_d3ea58)
    binary_sensor.luce_sala_channel_1_input:
      friendly_name: Pulsante 1
    binary_sensor.luce_sala_channel_2_input:
      friendly_name: Pulsante 2
    sensor.luce_sala_energy:
      friendly_name: Energia
    sensor.luce_sala_power:
      friendly_name: Potenza
    binary_sensor.luce_sala_overpowering:
      friendly_name: Sovraccarico Energetico
    binary_sensor.luce_sala_cloud:
      friendly_name: Connessione Cloud
    sensor.luce_sala_device_temperature:
      friendly_name: Temperatura Device
    binary_sensor.luce_sala_overheating:
      friendly_name: Surriscaldamento Device
    update.luce_sala_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_sala_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_sala_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_sala_uptime:
      friendly_name: Uptime
    button.luce_sala_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 8 - Luci Bagno (shellyswitch25_C45BBE6C38D0)
    sensor.luce_bagno_energy:
      friendly_name: Energia
    sensor.luce_bagno_power:
      friendly_name: Potenza
    binary_sensor.luce_bagno_overpowering:
      friendly_name: Sovraccarico Energetico
    sensor.luce_specchio_energy:
      friendly_name: Energia
    sensor.luce_specchio_power:
      friendly_name: Potenza
    binary_sensor.luce_specchio_overpowering:
      friendly_name: Sovraccarico Energetico
    binary_sensor.luci_bagno_cloud:
      friendly_name: Connessione Cloud
    sensor.luci_bagno_device_temperature:
      friendly_name: Temperatura Device
    binary_sensor.luci_bagno_overheating:
      friendly_name: Surriscaldamento Device
    update.luci_bagno_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luci_bagno_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luci_bagno_rssi:
      friendly_name: Potenza Segnale
    sensor.luci_bagno_uptime:
      friendly_name: Uptime
    button.luci_bagno_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 9 - Luce Studio (shelly1_59e18c)
    binary_sensor.luce_studio_cloud:
      friendly_name: Connessione Cloud
    update.luce_studio_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_studio_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_studio_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_studio_uptime:
      friendly_name: Uptime
    button.luce_studio_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 10 - Luce Camera (shellydimmer_d46cf2)
    binary_sensor.luce_camera_channel_1_input:
      friendly_name: Pulsante 1
    binary_sensor.luce_camera_channel_2_input:
      friendly_name: Pulsante 2
    sensor.luce_camera_energy:
      friendly_name: Energia
    sensor.luce_camera_power:
      friendly_name: Potenza
    binary_sensor.luce_camera_overpowering:
      friendly_name: Sovraccarico Energetico
    binary_sensor.luce_camera_cloud:
      friendly_name: Connessione Cloud
    sensor.luce_camera_device_temperature:
      friendly_name: Temperatura Device
    binary_sensor.luce_camera_overheating:
      friendly_name: Surriscaldamento Device
    update.luce_camera_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_camera_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_camera_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_camera_uptime:
      friendly_name: Uptime
    button.luce_camera_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly 11 - Luce Balcone (shelly1_c423c8)
    binary_sensor.luce_balcone_cloud:
      friendly_name: Connessione Cloud
    update.luce_balcone_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_balcone_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_balcone_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_balcone_uptime:
      friendly_name: Uptime
    button.luce_balcone_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly Bulb (shellybulb_bc8610)
    binary_sensor.luce_divano_cloud:
      friendly_name: Connessione Cloud
    update.luce_divano_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_divano_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_divano_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_divano_uptime:
      friendly_name: Uptime
    button.luce_divano_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly EM (shellyem_b9e1a0)
    switch.shelly_em:
      friendly_name: Pulsante
    sensor.shelly_em_channel_1_power:
      friendly_name: Potenza Istantanea
    sensor.shelly_em_channel_1_energy:
      friendly_name: Energia
    sensor.shelly_em_channel_1_energy_cost:
      friendly_name: Costo Energia
    sensor.shelly_em_channel_1_energy_returned:
      friendly_name: Energia Restituita
    sensor.shelly_em_channel_1_voltage:
      friendly_name: Tensione
    sensor.shelly_em_channel_2_power:
      friendly_name: Potenza Istantanea Canale 2
    sensor.shelly_em_channel_2_energy:
      friendly_name: Energia Canale 2
    sensor.shelly_em_channel_2_energy_returned:
      friendly_name: Energia Restituita Canale 2
    sensor.shelly_em_channel_2_voltage:
      friendly_name: Tensione Canale 2
    sensor.shelly_em_channel_1_power_factor:
      friendly_name: Fattore di Potenza Canale 1
    sensor.shelly_em_channel_2_power_factor:
      friendly_name: Fattore di Potenza Canale 2
    binary_sensor.shelly_em_overpowering:
      friendly_name: Sovraccarico Energetico
    binary_sensor.shelly_em_cloud:
      friendly_name: Connessione Cloud
    update.shelly_em_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.shelly_em_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.shelly_em_rssi:
      friendly_name: Potenza Segnale
    sensor.shelly_em_uptime:
      friendly_name: Uptime
    button.shelly_em_reboot:
      friendly_name: Riavvia Dispositivo
