######################################################################
# Shelly Package - Customization
######################################################################

homeassistant:
  customize:

    # Shelly EM Gen4 (ACEBE6C8F2D8)
    switch.shelly_em:
      friendly_name: Pulsante
    update.shelly_em_firmware:
      friendly_name: Aggiornamento Firmware
    update.shelly_em_firmware_beta:
      friendly_name: Aggiornamento Firmware Beta
    button.shelly_em_riavvia:
      friendly_name: Riavvia Dispositivo
    binary_sensor.shelly_em_cloud:
      friendly_name: Connessione Cloud
    sensor.shelly_em_intensita_del_segnale:
      friendly_name: Potenza Segnale
    binary_sensor.shelly_em_riavvio_richiesto:
      friendly_name: Riavvio Richiesto
    sensor.shelly_em_temperatura:
      friendly_name: Temperatura
    sensor.shelly_em_tempo_di_attivita:
      friendly_name: Tempo di Attività
    # Energy Meter A
    sensor.shelly_em_energy_meter_0_potenza:
      friendly_name: Potenza
    sensor.shelly_em_energy_meter_0_energia:
      friendly_name: Energia
    sensor.shelly_em_energy_meter_0_energia_cost:
      friendly_name: Costo Energia
    sensor.shelly_em_energy_meter_0_fattore_di_potenza:
      friendly_name: Fattore di Potenza
    sensor.shelly_em_energy_meter_0_potenza_apparente:
      friendly_name: Potenza Apparente
    sensor.shelly_em_energy_meter_0_corrente:
      friendly_name: Corrente
    sensor.shelly_em_energy_meter_0_energia_restituita:
      friendly_name: Energia Restituita
    sensor.shelly_em_energy_meter_0_frequenza:
      friendly_name: Frequenza
    sensor.shelly_em_energy_meter_0_tensione:
      friendly_name: Tensione
    # Energy Meter B
    sensor.shelly_em_energy_meter_1_potenza:
      friendly_name: Potenza
    sensor.shelly_em_energy_meter_1_energia:
      friendly_name: Energia
    sensor.shelly_em_energy_meter_1_energia_cost:
      friendly_name: Costo Energia
    sensor.shelly_em_energy_meter_1_fattore_di_potenza:
      friendly_name: Fattore di Potenza
    sensor.shelly_em_energy_meter_1_potenza_apparente:
      friendly_name: Potenza Apparente
    sensor.shelly_em_energy_meter_1_corrente:
      friendly_name: Corrente
    sensor.shelly_em_energy_meter_1_energia_restituita:
      friendly_name: Energia Restituita
    sensor.shelly_em_energy_meter_1_frequenza:
      friendly_name: Frequenza
    sensor.shelly_em_energy_meter_1_tensione:
      friendly_name: Tensione

    # Shelly Bulb (shellybulb_bc8610)
    binary_sensor.luce_piantana_cloud:
      friendly_name: Connessione Cloud
    update.luce_piantana_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_piantana_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_piantana_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_piantana_uptime:
      friendly_name: Uptime
    button.luce_piantana_reboot:
      friendly_name: Riavvia Dispositivo
