######################################################################
# Shelly Package - Customization
######################################################################

homeassistant:
  customize:
    script.shelly_upgrade:
      icon: mdi:cellphone-arrow-down

    script.shelly_reboot:
      icon: mdi:restart
