######################################################################
# Shelly Package - Customization
######################################################################

homeassistant:
  customize:

    # Shelly EM (shellyem_b9f0d0)
    switch.shelly_em:
      friendly_name: Pulsante
    sensor.shelly_em_channel_1_power:
      friendly_name: Potenza Istantanea
    sensor.shelly_em_channel_1_energy:
      friendly_name: Energia
    sensor.shelly_em_channel_1_energy_cost:
      friendly_name: Costo Energia
    sensor.shelly_em_channel_1_energy_returned:
      friendly_name: Energia Restituita
    sensor.shelly_em_channel_1_voltage:
      friendly_name: Tensione
    sensor.shelly_em_channel_1_power_factor:
      friendly_name: Fattore di Potenza Canale 1
    sensor.shelly_em_channel_2_power:
      friendly_name: Potenza Istantanea Canale 2
    sensor.shelly_em_channel_2_energy:
      friendly_name: Energia Canale 2
    sensor.shelly_em_channel_2_energy_returned:
      friendly_name: Energia Restituita Canale 2
    sensor.shelly_em_channel_2_voltage:
      friendly_name: Tensione Canale 2
    sensor.shelly_em_channel_2_power_factor:
      friendly_name: Fattore di Potenza Canale 2
    binary_sensor.shelly_em_overpowering:
      friendly_name: Sovraccarico Energetico
    binary_sensor.shelly_em_cloud:
      friendly_name: Connessione Cloud
    update.shelly_em_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.shelly_em_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.shelly_em_rssi:
      friendly_name: Potenza Segnale
    sensor.shelly_em_uptime:
      friendly_name: Uptime
    button.shelly_em_reboot:
      friendly_name: Riavvia Dispositivo

    # Shelly Bulb (shellybulb_bc8610)
    binary_sensor.luce_divano_cloud:
      friendly_name: Connessione Cloud
    update.luce_divano_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_divano_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_divano_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_divano_uptime:
      friendly_name: Uptime
    button.luce_divano_reboot:
      friendly_name: Riavvia Dispositivo
