######################################################################
# Shelly Package - Customization
######################################################################

homeassistant:
  customize:
    script.shelly_upgrade:
      icon: mdi:package-up
    script.shelly_reboot:
      icon: mdi:restart

    # Shelly 1 - Tapparella Cucina (shellyswitch_55980f)
    sensor.tapparella_cucina_energy:
      friendly_name: Tapparella Cucina - Energia
    sensor.tapparella_cucina_power:
      friendly_name: Tapparella Cucina - Potenza
    binary_sensor.tapparella_cucina_channel_1_input:
      friendly_name: Tapparella Cucina - Pulsante 1
    binary_sensor.tapparella_cucina_channel_2_input:
      friendly_name: Tapparella Cucina - Pulsante 2
    binary_sensor.tapparella_cucina_cloud:
      friendly_name: Tapparella Cucina - Connessione Cloud
    update.tapparella_cucina_firmware_update:
      friendly_name: Tapparella Cucina - Aggiornamento Firmware
    update.tapparella_cucina_beta_firmware_update:
      friendly_name: Tapparella Cucina - Aggiornamento Firmware Beta
    sensor.tapparella_cucina_rssi:
      friendly_name: Tapparella Cucina - Potenza Segnale
    sensor.tapparella_cucina_uptime:
      friendly_name: Tapparella Cucina - Uptime
    button.tapparella_cucina_reboot:
      friendly_name: Tapparella Cucina - Riavvia Dispositivo

    # Shelly 2 - Tapparella Sala (shellyswitch25_6919bd)
    sensor.tapparella_sala_energy:
      friendly_name: Tapparella Sala - Energia
    sensor.tapparella_sala_power:
      friendly_name: Tapparella Sala - Potenza
    binary_sensor.tapparella_sala_channel_1_input:
      friendly_name: Tapparella Sala - Pulsante 1
    binary_sensor.tapparella_sala_channel_2_input:
      friendly_name: Tapparella Sala - Pulsante 2
    binary_sensor.tapparella_sala_cloud:
      friendly_name: Tapparella Sala - Connessione Cloud
    sensor.tapparella_sala_device_temperature:
      friendly_name: Tapparella Sala - Temperatura Device
    binary_sensor.tapparella_sala_overheating:
      friendly_name: Tapparella Sala - Surriscaldamento Device
    update.tapparella_sala_firmware_update:
      friendly_name: Tapparella Sala - Aggiornamento Firmware
    update.tapparella_sala_beta_firmware_update:
      friendly_name: Tapparella Sala - Aggiornamento Firmware Beta
    sensor.tapparella_sala_rssi:
      friendly_name: Tapparella Sala - Potenza Segnale
    sensor.tapparella_sala_uptime:
      friendly_name: Tapparella Sala - Uptime
    button.tapparella_sala_reboot:
      friendly_name: Tapparella Sala - Riavvia Dispositivo

    # Shelly 3 - Tapparella Studio (shellyswitch_13572b)
    sensor.tapparella_studio_energy:
      friendly_name: Tapparella Studio - Energia
    sensor.tapparella_studio_power:
      friendly_name: Tapparella Studio - Potenza
    binary_sensor.tapparella_studio_channel_1_input:
      friendly_name: Tapparella Studio - Pulsante 1
    binary_sensor.tapparella_studio_channel_2_input:
      friendly_name: Tapparella Studio - Pulsante 2
    binary_sensor.tapparella_studio_cloud:
      friendly_name: Tapparella Studio - Connessione Cloud
    update.tapparella_studio_firmware_update:
      friendly_name: Tapparella Studio - Aggiornamento Firmware
    update.tapparella_studio_beta_firmware_update:
      friendly_name: Tapparella Studio - Aggiornamento Firmware Beta
    sensor.tapparella_studio_rssi:
      friendly_name: Tapparella Studio - Potenza Segnale
    sensor.tapparella_studio_uptime:
      friendly_name: Tapparella Studio - Uptime
    button.tapparella_studio_reboot:
      friendly_name: Tapparella Studio - Riavvia Dispositivo

    # Shelly 4 - Tapparella Camera (shellyswitch_559c49)
    sensor.tapparella_camera_energy:
      friendly_name: Tapparella Camera - Energia
    sensor.tapparella_camera_power:
      friendly_name: Tapparella Camera - Potenza
    binary_sensor.tapparella_camera_channel_1_input:
      friendly_name: Tapparella Camera - Pulsante 1
    binary_sensor.tapparella_camera_channel_2_input:
      friendly_name: Tapparella Camera - Pulsante 2
    binary_sensor.tapparella_camera_cloud:
      friendly_name: Tapparella Camera - Connessione Cloud
    update.tapparella_camera_firmware_update:
      friendly_name: Tapparella Camera - Aggiornamento Firmware
    update.tapparella_camera_beta_firmware_update:
      friendly_name: Tapparella Camera - Aggiornamento Firmware Beta
    sensor.tapparella_camera_rssi:
      friendly_name: Tapparella Camera - Potenza Segnale
    sensor.tapparella_camera_uptime:
      friendly_name: Tapparella Camera - Uptime
    button.tapparella_camera_reboot:
      friendly_name: Tapparella Camera - Riavvia Dispositivo

    # Shelly 5 - Luce Corridoio (shelly1_24d1ee)
    binary_sensor.luce_corridoio_cloud:
      friendly_name: Luce Corridoio - Connessione Cloud
    update.luce_corridoio_firmware_update:
      friendly_name: Luce Corridoio - Aggiornamento Firmware
    update.luce_corridoio_beta_firmware_update:
      friendly_name: Luce Corridoio - Aggiornamento Firmware Beta
    sensor.luce_corridoio_rssi:
      friendly_name: Luce Corridoio - Potenza Segnale
    sensor.luce_corridoio_uptime:
      friendly_name: Luce Corridoio - Uptime
    button.luce_corridoio_reboot:
      friendly_name: Luce Corridoio - Riavvia Dispositivo

    # Shelly 6 - Luce Cucina (shelly1_93B27D)
    binary_sensor.luce_cucina_cloud:
      friendly_name: Luce Cucina - Connessione Cloud
    update.luce_cucina_firmware_update:
      friendly_name: Luce Cucina - Aggiornamento Firmware
    update.luce_cucina_beta_firmware_update:
      friendly_name: Luce Cucina - Aggiornamento Firmware Beta
    sensor.luce_cucina_rssi:
      friendly_name: Luce Cucina - Potenza Segnale
    sensor.luce_cucina_uptime:
      friendly_name: Luce Cucina - Uptime
    button.luce_cucina_reboot:
      friendly_name: Luce Cucina - Riavvia Dispositivo

    # Shelly 7 - Luce Sala (shellydimmer_d3ea58)
    binary_sensor.luce_sala_channel_1_input:
      friendly_name: Luce Sala - Pulsante 1
    binary_sensor.luce_sala_channel_2_input:
      friendly_name: Luce Sala - Pulsante 2
    sensor.luce_sala_energy:
      friendly_name: Luce Sala - Energia
    sensor.luce_sala_power:
      friendly_name: Luce Sala - Potenza
    binary_sensor.luce_sala_overpowering:
      friendly_name: Luce Sala - Sovraccarico Energetico
    binary_sensor.luce_sala_cloud:
      friendly_name: Luce Sala - Connessione Cloud
    sensor.luce_sala_device_temperature:
      friendly_name: Luce Sala - Temperatura Device
    binary_sensor.luce_sala_overheating:
      friendly_name: Luce Sala - Surriscaldamento Device
    update.luce_sala_firmware_update:
      friendly_name: Luce Sala - Aggiornamento Firmware
    update.luce_sala_beta_firmware_update:
      friendly_name: Luce Sala - Aggiornamento Firmware Beta
    sensor.luce_sala_rssi:
      friendly_name: Luce Sala - Potenza Segnale
    sensor.luce_sala_uptime:
      friendly_name: Luce Sala - Uptime
    button.luce_sala_reboot:
      friendly_name: Luce Sala - Riavvia Dispositivo

    # Shelly 8 - Luci Bagno (shellyswitch25_C45BBE6C38D0)
    sensor.luce_bagno_energy:
      friendly_name: Luci Bagno - Energia Luce Bagno
    binary_sensor.luce_bagno_overpowering:
      friendly_name: Luce Bagno - Sovraccarico Energetico
    sensor.luce_bagno_power:
      friendly_name: Luce Bagno - Potenza
    sensor.luce_specchio_energy:
      friendly_name: Luce Bagno - Energia
    binary_sensor.luce_specchio_overpowering:
      friendly_name: Luce Specchio - Sovraccarico Energetico
    sensor.luce_specchio_power:
      friendly_name: Luce Specchio - Potenza
    binary_sensor.luci_bagno_cloud:
      friendly_name: Luci Bagno - Connessione Cloud
    sensor.luci_bagno_device_temperature:
      friendly_name: Luci Bagno - Temperatura Device
    binary_sensor.luci_bagno_overheating:
      friendly_name: Luci Bagno - Surriscaldamento Device
    update.luci_bagno_firmware_update:
      friendly_name: Luci Bagno - Aggiornamento Firmware
    update.luci_bagno_beta_firmware_update:
      friendly_name: Luci Bagno - Aggiornamento Firmware Beta
    sensor.luci_bagno_rssi:
      friendly_name: Luci Bagno - Potenza Segnale
    sensor.luci_bagno_uptime:
      friendly_name: Luci Bagno - Uptime
    button.luci_bagno_reboot:
      friendly_name: Luci Bagno - Riavvia Dispositivo

    # Shelly 9 - Luce Studio (shelly1_59e18c)
    binary_sensor.luce_studio_cloud:
      friendly_name: Luce Studio - Connessione Cloud
    update.luce_studio_firmware_update:
      friendly_name: Luce Studio - Aggiornamento Firmware
    update.luce_studio_beta_firmware_update:
      friendly_name: Luce Studio - Aggiornamento Firmware Beta
    sensor.luce_studio_rssi:
      friendly_name: Luce Studio - Potenza Segnale
    sensor.luce_studio_uptime:
      friendly_name: Luce Studio - Uptime
    button.luce_studio_reboot:
      friendly_name: Luce Studio - Riavvia Dispositivo

    # Shelly 10 - Luce Camera (shellydimmer_d46cf2)
    binary_sensor.luce_camera_channel_1_input:
      friendly_name: Luce Camera - Pulsante 1
    binary_sensor.luce_camera_channel_2_input:
      friendly_name: Luce Camera - Pulsante 2
    sensor.luce_camera_energy:
      friendly_name: Luce Camera - Energia
    sensor.luce_camera_power:
      friendly_name: Luce Camera - Potenza
    binary_sensor.luce_camera_overpowering:
      friendly_name: Luce Camera - Sovraccarico Energetico
    binary_sensor.luce_camera_cloud:
      friendly_name: Luce Camera - Connessione Cloud
    sensor.luce_camera_device_temperature:
      friendly_name: Luce Camera - Temperatura Device
    binary_sensor.luce_camera_overheating:
      friendly_name: Luce Camera - Surriscaldamento Device
    update.luce_camera_firmware_update:
      friendly_name: Luce Camera - Aggiornamento Firmware
    update.luce_camera_beta_firmware_update:
      friendly_name: Luce Camera - Aggiornamento Firmware Beta
    sensor.luce_camera_rssi:
      friendly_name: Luce Camera - Potenza Segnale
    sensor.luce_camera_uptime:
      friendly_name: Luce Camera - Uptime
    button.luce_camera_reboot:
      friendly_name: Luce Camera - Riavvia Dispositivo

    # Shelly 11 - Luce Balcone (shelly1_c423c8)
    binary_sensor.luce_balcone_cloud:
      friendly_name: Luce Balcone - Connessione Cloud
    update.luce_balcone_firmware_update:
      friendly_name: Luce Balcone - Aggiornamento Firmware
    update.luce_balcone_beta_firmware_update:
      friendly_name: Luce Balcone - Aggiornamento Firmware Beta
    sensor.luce_balcone_rssi:
      friendly_name: Luce Balcone - Potenza Segnale
    sensor.luce_balcone_uptime:
      friendly_name: Luce Balcone - Uptime
    button.luce_balcone_reboot:
      friendly_name: Luce Balcone - Riavvia Dispositivo

    # Shelly Bulb (shellybulb_bc8610)
    binary_sensor.luce_divano_cloud:
      friendly_name: Luce Divano - Connessione Cloud
    update.luce_divano_firmware_update:
      friendly_name: Luce Divano - Aggiornamento Firmware
    update.luce_divano_beta_firmware_update:
      friendly_name: Luce Divano - Aggiornamento Firmware Beta
    sensor.luce_divano_rssi:
      friendly_name: Luce Divano - Potenza Segnale
    sensor.luce_divano_uptime:
      friendly_name: Luce Divano - Uptime
    button.luce_divano_reboot:
      friendly_name: Luce Divano - Riavvia Dispositivo

    # Shelly EM (shellyem_b9e1a0)
    switch.shelly_em:
      friendly_name: Shelly EM - Pulsante
    sensor.shelly_em_channel_1_power:
      friendly_name: Potenza Istantanea
    sensor.shelly_em_channel_1_energy:
      friendly_name: Energia
    sensor.shelly_em_channel_1_energy_cost:
      friendly_name: Costo Energia
    sensor.shelly_em_channel_1_energy_returned:
      friendly_name: Energia Restituita
    sensor.shelly_em_channel_1_voltage:
      friendly_name: Tensione
    sensor.shelly_em_channel_2_power:
      friendly_name: Potenza Istantanea Canale 2
    sensor.shelly_em_channel_2_energy:
      friendly_name: Energia Canale 2
    sensor.shelly_em_channel_2_energy_returned:
      friendly_name: Energia Restituita Canale 2
    sensor.shelly_em_channel_2_voltage:
      friendly_name: Tensione Canale 2
    sensor.shelly_em_channel_1_power_factor:
      friendly_name: Fattore di Potenza Canale 1
    sensor.shelly_em_channel_2_power_factor:
      friendly_name: Fattore di Potenza Canale 2
    binary_sensor.shelly_em_overpowering:
      friendly_name: Shelly EM - Sovraccarico Energetico
    binary_sensor.shelly_em_cloud:
      friendly_name: Shelly EM - Connessione Cloud
    update.shelly_em_firmware_update:
      friendly_name: Shelly EM - Aggiornamento Firmware
    update.shelly_em_beta_firmware_update:
      friendly_name: Shelly EM - Aggiornamento Firmware Beta
    sensor.shelly_em_rssi:
      friendly_name: Shelly EM - Potenza Segnale
    sensor.shelly_em_uptime:
      friendly_name: Shelly EM - Uptime
    button.shelly_em_reboot:
      friendly_name: Shelly EM - Riavvia Dispositivo
