######################################################################
# Shelly Package - Customization
######################################################################

homeassistant:
  customize:

    # Shelly EM (shellyem_b9f0d0)
    switch.shelly_em:
      friendly_name: Pulsante
    sensor.shelly_em_channel_1_potenza:
      friendly_name: Potenza Istantanea
    sensor.shelly_em_channel_1_energia:
      friendly_name: Energia
    sensor.shelly_em_channel_1_energia_cost:
      friendly_name: Costo Energia
    sensor.shelly_em_channel_1_energia_restituita:
      friendly_name: Energia Restituita
    sensor.shelly_em_channel_1_tensione:
      friendly_name: Tensione
    sensor.shelly_em_channel_1_fattore_di_potenza:
      friendly_name: Fattore di Potenza Canale 1
    sensor.shelly_em_channel_2_potenza:
      friendly_name: Potenza Istantanea Canale 2
    sensor.shelly_em_channel_2_energia:
      friendly_name: Energia Canale 2
    sensor.shelly_em_channel_2_energia_restituita:
      friendly_name: Energia Restituita Canale 2
    sensor.shelly_em_channel_2_tensione:
      friendly_name: Tensione Canale 2
    sensor.shelly_em_channel_2_fattore_di_potenza:
      friendly_name: Fattore di Potenza Canale 2
    binary_sensor.shelly_em_sovra_potenza:
      friendly_name: Sovraccarico Energetico
    binary_sensor.shelly_em_cloud:
      friendly_name: Connessione Cloud
    update.shelly_em_firmware:
      friendly_name: Aggiornamento Firmware
    shelly_em_firmware_beta:
      friendly_name: Aggiornamento Firmware Beta
    sensor.shelly_em_intensita_del_segnale:
      friendly_name: Potenza Segnale
    sensor.shelly_em_ultimo_riavvio:
      friendly_name: Ultimo Riavvio
    button.shelly_em_riavvia:
      friendly_name: Riavvia Dispositivo

    # Shelly Bulb (shellybulb_bc8610)
    binary_sensor.luce_piantana_cloud:
      friendly_name: Connessione Cloud
    update.luce_piantana_firmware_update:
      friendly_name: Aggiornamento Firmware
    update.luce_piantana_beta_firmware_update:
      friendly_name: Aggiornamento Firmware Beta
    sensor.luce_piantana_rssi:
      friendly_name: Potenza Segnale
    sensor.luce_piantana_uptime:
      friendly_name: Uptime
    button.luce_piantana_reboot:
      friendly_name: Riavvia Dispositivo
